import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";

const rows = vi.hoisted(() => new Map<string, unknown>());

vi.mock("@/lib/services/comparison-service", () => ({
  getComparisonBySlug: async (slug: string) => rows.get(slug) ?? null,
  isComparisonDbConfigured: () => true,
  saveComparison: vi.fn(),
}));

vi.mock("@/lib/services/ai-comparison-generator", () => ({
  generateComparison: vi.fn(async () => {
    throw new Error("must not generate when a related slug is already live");
  }),
}));

vi.mock("@/lib/services/cache-warming", () => ({
  warmCacheForSlug: vi.fn(async () => {}),
}));

vi.mock("@/lib/posthog-server", () => ({
  getPostHogClient: () => ({ capture: vi.fn() }),
  flushPostHog: vi.fn(async () => {}),
}));

import { POST } from "@/app/api/comparisons/generate/route";

function live(slug: string) {
  return {
    id: `id-${slug}`,
    slug,
    title: slug,
    category: "general",
    shortAnswer: "Answer",
    verdict: "Verdict",
    entities: [
      { id: "a", slug: "a", name: "A", pros: [], cons: [] },
      { id: "b", slug: "b", name: "B", pros: [], cons: [] },
    ],
    keyDifferences: [],
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      status: "published",
      metaTitle: slug,
      metaDescription: slug,
      publishedAt: null,
      updatedAt: new Date().toISOString(),
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 1,
    },
  };
}

function post(slug: string) {
  return new NextRequest("http://localhost/api/comparisons/generate", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "x-generation-client": "browser",
    },
    body: JSON.stringify({ slug }),
  });
}

describe("POST /api/comparisons/generate duplicate check", () => {
  beforeEach(() => {
    rows.clear();
    vi.stubEnv("USER_GENERATION_ENABLED", "true");
    vi.stubEnv("USER_GENERATION_ENTITY_CHECK", "off");
  });

  it.each([
    ["dc-vs-marvel", "marvel-vs-dc"],
    ["china-vs-united-states", "usa-vs-china"],
    ["firefox-vs-google-chrome", "chrome-vs-firefox"],
    ["disney-vs-hulu", "disney-plus-vs-hulu"],
    ["javascript-vs-python", "python-vs-javascript"],
    ["netflix-vs-peacock-comparison-2026", "netflix-vs-peacock"],
  ])("for %s returns the live page %s", async (requested, existing) => {
    rows.set(existing, live(existing));
    const response = await POST(post(requested));
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body.status).toBe("ready");
    expect(body.canonicalSlug).toBe(existing);
  });
});
