import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";

vi.mock("@/lib/services/ai-comparison-generator", () => ({
  generateComparison: vi.fn(async () => ({
    success: true,
    comparison: {
      id: "cmp",
      slug: "alpha-thing-vs-beta-thing",
      title: "Alpha Thing vs Beta Thing",
      shortAnswer: "Alpha is larger (2 vs 1).",
      verdict: "Pick either.",
      category: "general",
      entities: [
        { id: "1", slug: "alpha-thing", name: "Alpha Thing", pros: [], cons: [] },
        { id: "2", slug: "beta-thing", name: "Beta Thing", pros: [], cons: [] },
      ],
      keyDifferences: [],
      attributes: [],
      faqs: [],
      relatedComparisons: [],
      relatedBlogPosts: [],
      metadata: {
        metaTitle: "Alpha vs Beta",
        metaDescription: "Alpha vs Beta",
        publishedAt: null,
        updatedAt: new Date().toISOString(),
        isAutoGenerated: true,
        isHumanReviewed: false,
        viewCount: 0,
      },
    },
  })),
}));

vi.mock("@/lib/services/cache-warming", () => ({
  warmCacheForSlug: vi.fn(async () => {}),
}));

vi.mock("@/lib/posthog-server", () => ({
  getPostHogClient: () => ({ capture: vi.fn() }),
  flushPostHog: vi.fn(async () => {}),
}));

import { POST } from "@/app/api/comparisons/generate/route";

function request() {
  return new NextRequest("http://localhost/api/comparisons/generate", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "x-generation-client": "browser",
    },
    body: JSON.stringify({ slug: "alpha-thing-vs-beta-thing" }),
  });
}

describe("POST /api/comparisons/generate when saveComparison returns null", () => {
  beforeEach(() => {
    vi.stubEnv("USER_GENERATION_ENABLED", "true");
    vi.stubEnv("USER_GENERATION_ENTITY_CHECK", "off");
  });

  it("reports failure instead of success", async () => {
    const response = await POST(request());
    expect(response.status).toBe(500);
    const body = await response.json();
    expect(body.status).toBe("error");
    expect(body.reason).toBe("save_rejected");
    expect(body.errorStage).toBe("save");
  });
});
