import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";

const state = vi.hoisted(() => ({ row: null as unknown }));
const generateComparison = vi.hoisted(() => vi.fn(async () => ({
  success: false,
  comparison: null,
  error: "stopped",
  errorStage: "quality",
})));

vi.mock("@/lib/services/comparison-service", () => ({
  getComparisonBySlug: async () => state.row,
  isComparisonDbConfigured: () => true,
  saveComparison: vi.fn(),
}));

vi.mock("@/lib/services/ai-comparison-generator", () => ({
  generateComparison,
}));

vi.mock("@/lib/services/cache-warming", () => ({
  warmCacheForSlug: vi.fn(async () => {}),
  warmCacheForPaths: vi.fn(async () => {}),
}));

vi.mock("@/lib/posthog-server", () => ({
  getPostHogClient: () => ({ capture: vi.fn() }),
  flushPostHog: vi.fn(async () => {}),
}));

import { POST } from "@/app/api/comparisons/generate/route";

function request() {
  return new NextRequest("http://localhost/api/comparisons/generate", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "user-agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "x-generation-client": "browser",
    },
    body: JSON.stringify({ slug: "canoe-vs-kayak" }),
  });
}

function row(visitorTableSaved: boolean) {
  return {
    id: "cmp",
    slug: "canoe-vs-kayak",
    title: "Canoe vs Kayak",
    category: "general",
    shortAnswer: "Answer",
    verdict: "Verdict",
    entities: [
      { id: "a", slug: "canoe", name: "Canoe", pros: [], cons: [] },
      { id: "b", slug: "kayak", name: "Kayak", pros: [], cons: [] },
    ],
    keyDifferences: [],
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      status: "provisional",
      metaTitle: "Canoe vs Kayak",
      metaDescription: "Canoe vs Kayak",
      publishedAt: null,
      updatedAt: new Date().toISOString(),
      isAutoGenerated: true,
      isHumanReviewed: false,
      viewCount: 0,
      visitorTableSaved,
    },
  };
}

describe("POST /api/comparisons/generate stale provisional row", () => {
  beforeEach(() => {
    generateComparison.mockClear();
    vi.stubEnv("USER_GENERATION_ENABLED", "true");
    vi.stubEnv("USER_GENERATION_ENTITY_CHECK", "off");
  });

  it("builds again when the provisional row has no visitor table", async () => {
    state.row = row(false);
    const response = await POST(request());
    expect(generateComparison).toHaveBeenCalled();
    const body = await response.json();
    expect(body.status).not.toBe("ready");
  });

  it("returns a provisional row that already has its visitor table", async () => {
    state.row = row(true);
    const response = await POST(request());
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body.status).toBe("ready");
    expect(generateComparison).not.toHaveBeenCalled();
  });
});
