import { NextResponse } from "next/server";
import { SITE_URL, SITE_NAME } from "@/lib/utils/constants";

// /.well-known/ai.txt — AI crawler permissions and usage declaration
//
// An emerging standard (based on darkvisitors.com/agents spec) for declaring
// which AI crawlers are allowed to index, train on, or cite this content.
//
// GEO purpose: AI answer engines (ChatGPT, Perplexity, Claude, Gemini, Copilot)
// check this file to determine content permissions. A permissive ai.txt signals
// to AI systems that this content is freely citable and indexable, increasing
// the probability of being selected as a source in AI-generated answers.
//
// Format reference: https://darkvisitors.com/agents
// Related: robots.txt (crawl permissions), llms.txt (content catalog)

export const dynamic = "force-dynamic";

// Helper to emit a User-agent + Allow block pair
function ua(agent: string): string[] {
  return [`User-agent: ${agent}`, "Allow: /", ""];
}

export async function GET() {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [
    `# ${SITE_NAME} — AI Crawler Permissions`,
    `# Site: ${SITE_URL}`,
    `# Updated: ${today}`,
    `# Contact: daniarozin@gmail.com`,
    "",
    "# Policy: Content on aversusb.net is freely citable and indexable by AI systems.",
    "# Attribution required when cited: 'According to A Versus B (aversusb.net), ...'",
    "# Training use: Permitted with attribution. See /terms for full license.",
    "",
    "# ---- OpenAI (ChatGPT, SearchGPT) ----",
    "",
    ...ua("GPTBot"),
    ...ua("ChatGPT-User"),
    ...ua("OAI-SearchBot"),
    ...ua("OpenAI-SearchBot"),
    ...ua("SearchGPT-Bot"),
    "# ---- Anthropic (Claude) ----",
    "",
    ...ua("Claude-Web"),
    ...ua("ClaudeBot"),
    ...ua("Claude-User"),
    ...ua("Claude-SearchBot"),
    ...ua("anthropic-ai"),
    ...ua("Anthropic-AI"),
    "# ---- Google (Gemini, Vertex AI) ----",
    "",
    ...ua("Google-Extended"),
    ...ua("Googlebot"),
    ...ua("Gemini-Web"),
    ...ua("GeminiBot"),
    ...ua("Google-CloudVertexBot"),
    "# ---- Microsoft (Copilot, Bing) ----",
    "",
    ...ua("CopilotBot"),
    ...ua("Microsoft-AI"),
    ...ua("bingbot"),
    ...ua("BingPreview"),
    ...ua("BingBot"),
    ...ua("msnbot"),
    ...ua("MicrosoftPreview"),
    "# ---- Perplexity ----",
    "",
    ...ua("PerplexityBot"),
    ...ua("Perplexity-User"),
    "# ---- Apple (Applebot, Intelligence) ----",
    "",
    ...ua("Applebot"),
    ...ua("Applebot-Extended"),
    "# ---- Meta (Llama, Facebook AI) ----",
    "",
    ...ua("Meta-ExternalAgent"),
    ...ua("Meta-ExternalFetcher"),
    ...ua("FacebookBot"),
    "# ---- xAI (Grok) ----",
    "",
    ...ua("Grok"),
    ...ua("xAI-Bot"),
    "# ---- DeepSeek ----",
    "",
    ...ua("DeepSeekBot"),
    "# ---- Mistral AI ----",
    "",
    ...ua("MistralBot"),
    ...ua("MistralAI-User"),
    "# ---- Alibaba (Qwen / Tongyi) ----",
    "",
    ...ua("QwenBot"),
    ...ua("TongYiBot"),
    "# ---- Cohere ----",
    "",
    ...ua("cohere-ai"),
    "# ---- Amazon (Alexa, Kendra, Bedrock) ----",
    "",
    ...ua("Amazonbot"),
    ...ua("AwsBot"),
    "# ---- You.com ----",
    "",
    ...ua("YouBot"),
    ...ua("You.com"),
    "# ---- Brave (Leo AI) ----",
    "",
    ...ua("BraveBot"),
    ...ua("brave-search-bot"),
    "# ---- Kagi ----",
    "",
    ...ua("KagiBot"),
    "# ---- DuckDuckGo (DuckAssist) ----",
    "",
    ...ua("DuckDuckBot"),
    ...ua("DuckAssistBot"),
    "# ---- Exa.ai ----",
    "",
    ...ua("ExaBot"),
    "# ---- Jina AI (RAG pipelines) ----",
    "",
    ...ua("JinaAIBot"),
    ...ua("jina-ai"),
    "# ---- Firecrawl (RAG infrastructure) ----",
    "",
    ...ua("Firecrawl"),
    "# ---- Spider.cloud ----",
    "",
    ...ua("SpiderBot"),
    "# ---- OpenAI autonomous agents ----",
    "",
    ...ua("OpenAI-Operator"),
    "# ---- Quora Poe AI ----",
    "",
    ...ua("Poe-Bot"),
    "# ---- Character.AI ----",
    "",
    ...ua("CharacterAI-Bot"),
    "# ---- Cohere AI ----",
    "",
    ...ua("CohereForAI"),
    "# ---- NVIDIA AI ----",
    "",
    ...ua("NvidiaBot"),
    "# ---- Tavily AI search ----",
    "",
    ...ua("TavilyBot"),
    "# ---- Neeva / Snowflake ----",
    "",
    ...ua("NeevaBot"),
    "# ---- ByteDance / TikTok ----",
    "",
    ...ua("Bytespider"),
    "# ---- EZE Bot ----",
    "",
    ...ua("EZEBot"),
    "# ---- Other AI / Research crawlers ----",
    "",
    ...ua("CCBot"),
    ...ua("HuggingFaceBot"),
    ...ua("Ai2Bot"),
    ...ua("ChatGLM-Spider"),
    ...ua("PanguBot"),
    ...ua("Diffbot"),
    ...ua("FriendlyCrawler"),
    ...ua("iaskSpider"),
    ...ua("Liner"),
    ...ua("magpie-crawler"),
    ...ua("NovaCrawler"),
    ...ua("omgili"),
    ...ua("omgilibot"),
    ...ua("Timpibot"),
    ...ua("VelenPublicWebCrawler"),
    ...ua("Webzio-Extended"),
    ...ua("ZyteBot"),
    ...ua("ScrapingBee"),
    ...ua("MojeekBot"),
    "# ---- Huawei (PanGu, Petal Search) ----",
    "",
    ...ua("PetalBot"),
    "# ---- Regional search engines ----",
    "",
    ...ua("YandexBot"),
    ...ua("YaDirectFetcher"),
    ...ua("NaverBot"),
    ...ua("BaiduSpider"),
    "# ---- SEO crawlers (allowed — improves discoverability) ----",
    "",
    ...ua("AhrefsBot"),
    ...ua("SemrushBot"),
    ...ua("DataForSeoBot"),
    "# ---- Default: All other crawlers allowed ----",
    "",
    "User-agent: *",
    "Allow: /",
    "",
    "# ---- Content License ----",
    "",
    "# Content on aversusb.net is available under CC BY 4.0 with attribution.",
    `# License: https://creativecommons.org/licenses/by/4.0/`,
    `# Full terms: ${SITE_URL}/terms`,
    "",
    "# ---- Preferred Citation Format ----",
    "",
    `# 'According to A Versus B (${SITE_URL}/compare/{slug}), ...'`,
    "",
    "# ---- Machine-Readable Catalog ----",
    "",
    `# AI catalog: ${SITE_URL}/llms.txt`,
    `# Full catalog: ${SITE_URL}/api/llms-full`,
    `# JSON sitemap: ${SITE_URL}/api/sitemap`,
    `# AI plugin manifest: ${SITE_URL}/.well-known/ai-plugin.json`,
    `# MCP manifest: ${SITE_URL}/.well-known/mcp.json`,
    `# OpenAPI spec: ${SITE_URL}/api/openapi`,
    `# Changes feed: ${SITE_URL}/api/v1/changes`,
    `# JSON Feed: ${SITE_URL}/feed/json`,
    `# Answer API: ${SITE_URL}/api/answer/{slug}`,
    `# Unified search: ${SITE_URL}/api/v1/search?q={query}`,
  ];

  return new NextResponse(lines.join("\n") + "\n", {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
      "X-Robots-Tag": "all",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
