import { describe, it, expect } from "vitest";
import {
  applyEditorialAeoOverlay,
  getEditorialAeoOverlay,
} from "../editorial-aeo-overlays";
import type { ComparisonPageData } from "@/types";

const BRIEF_GDP_FAQS = [
  "Is China’s economy bigger than the US in 2026?",
  "What is US vs China GDP (nominal) in 2026?",
  "What is US vs China GDP (PPP) in 2026?",
  "Why do nominal and PPP rankings disagree?",
  "What is GDP per capita for the US vs China?",
  "Will China overtake the US in nominal GDP this decade?",
  "Which GDP measure should journalists and students cite?",
];

const BRIEF_JAPAN_CHINA_FAQS = [
  "Is China’s economy bigger than Japan’s?",
  "What is Japan vs China GDP?",
  "What is Japan vs China GDP (PPP)?",
  "What is GDP per capita for Japan vs China?",
  "Which country is larger in land area and population?",
  "Which country has a stronger military?",
  "Which country has a higher quality of life, and which is safer to visit?",
];

function stubGdpPage(): ComparisonPageData {
  return {
    id: "us-vs-china-gdp",
    slug: "us-vs-china-gdp",
    title: "USA vs China GDP 2026",
    shortAnswer: "Old buried answer.",
    verdict: "Existing verdict.",
    category: "countries",
    entities: [
      { id: "us", slug: "united-states-economy", name: "United States Economy", shortDesc: null, imageUrl: null, entityType: "country", position: 0, pros: [], cons: [], bestFor: null },
      { id: "cn", slug: "china-economy", name: "China Economy", shortDesc: null, imageUrl: null, entityType: "country", position: 1, pros: [], cons: [], bestFor: null },
    ],
    attributes: [],
    keyDifferences: [
      { label: "Nominal GDP Size", entityAValue: "$30+ trillion", entityBValue: "$19 trillion", winner: "a" },
    ],
    faqs: [{ question: "Old Q", answer: "Old A" }],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "USA vs China GDP",
      metaDescription: "Compare US and China GDP.",
      publishedAt: "2026-03-27T00:00:00Z",
      updatedAt: "2026-09-15T00:00:00Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 1,
      status: "published",
    },
  };
}

function stubJapanChinaPage(): ComparisonPageData {
  return {
    id: "japan-vs-china",
    slug: "japan-vs-china",
    title: "Japan vs China",
    shortAnswer: "Old buried answer.",
    verdict: "Existing verdict.",
    category: "countries",
    entities: [
      { id: "ent-3", slug: "japan", name: "Japan", shortDesc: null, imageUrl: null, entityType: "country", position: 0, pros: [], cons: [], bestFor: null },
      { id: "ent-4", slug: "china", name: "China", shortDesc: null, imageUrl: null, entityType: "country", position: 1, pros: [], cons: [], bestFor: null },
    ],
    attributes: [],
    keyDifferences: [
      { label: "Population", entityAValue: "125M", entityBValue: "1.4B", winner: "b" },
      { label: "GDP", entityAValue: "$4.2T", entityBValue: "$17.7T", winner: "b" },
      { label: "GDP per Capita", entityAValue: "$33,800", entityBValue: "$12,500", winner: "a" },
    ],
    faqs: [{ question: "Old Q", answer: "Old A" }],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "Japan vs China",
      metaDescription: "Compare Japan and China.",
      publishedAt: "2024-03-01T00:00:00Z",
      updatedAt: "2026-03-15T00:00:00Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 1,
      status: "published",
    },
  };
}

describe("ROO-27 GDP AEO overlay", () => {
  it("rewrites speakable Quick Answer and FAQ to the brief’s 7 questions", () => {
    const overlay = getEditorialAeoOverlay("us-vs-china-gdp");
    expect(overlay).toBeTruthy();
    expect(overlay!.faqs.map((f) => f.question)).toEqual(BRIEF_GDP_FAQS);

    const next = applyEditorialAeoOverlay(stubGdpPage());
    expect(next.shortAnswer).toBe(overlay!.shortAnswer);
    expect(next.quickAnswer?.tldr).toBe(overlay!.shortAnswer);
    expect(next.faqs.map((f) => f.question)).toEqual(BRIEF_GDP_FAQS);
    expect(next.keyDifferences).toEqual(stubGdpPage().keyDifferences);
  });

  it("does not invent a PPP dollar total the live page does not print", () => {
    const overlay = getEditorialAeoOverlay("us-vs-china-gdp")!;
    const ppp = overlay.faqs.find((f) => f.question.includes("(PPP)"));
    expect(ppp?.answer).toMatch(/does not print a single PPP dollar total/i);
  });

  it("leaves unrelated slugs untouched", () => {
    const page = stubGdpPage();
    page.slug = "messi-vs-ronaldo";
    expect(applyEditorialAeoOverlay(page)).toBe(page);
  });
});

describe("japan-vs-china citation AEO overlay", () => {
  it("rewrites speakable Quick Answer and FAQ to 7 citation questions", () => {
    const overlay = getEditorialAeoOverlay("japan-vs-china");
    expect(overlay).toBeTruthy();
    expect(overlay!.faqs).toHaveLength(7);
    expect(overlay!.faqs.map((f) => f.question)).toEqual(BRIEF_JAPAN_CHINA_FAQS);

    const original = stubJapanChinaPage();
    const next = applyEditorialAeoOverlay(original);
    expect(next.shortAnswer).toBe(overlay!.shortAnswer);
    expect(next.quickAnswer?.tldr).toBe(overlay!.shortAnswer);
    expect(next.faqs.map((f) => f.question)).toEqual(BRIEF_JAPAN_CHINA_FAQS);
    expect(next.keyDifferences).toEqual(original.keyDifferences);
    expect(next.verdict).toBe(original.verdict);
  });

  it("does not invent a PPP dollar total the in-repo page does not print", () => {
    const overlay = getEditorialAeoOverlay("japan-vs-china")!;
    const ppp = overlay.faqs.find((f) => f.question.includes("(PPP)"));
    expect(ppp?.answer).toMatch(/unknown/i);
    expect(ppp?.answer).toMatch(/do not print a PPP dollar total/i);
    expect(ppp?.answer).toMatch(/instead of inventing a PPP figure/i);
  });

  it("reuses only in-repo GDP totals ($17.7T vs $4.2T) and per capita", () => {
    const overlay = getEditorialAeoOverlay("japan-vs-china")!;
    const blob = [overlay.shortAnswer, ...overlay.faqs.map((f) => f.answer)].join("\n");
    expect(blob).toMatch(/\$17\.7 trillion/);
    expect(blob).toMatch(/\$4\.2 trillion/);
    expect(blob).toMatch(/\$33,800/);
    expect(blob).toMatch(/\$12,500/);
    const trillionFigures = blob.match(/\$[\d.]+ trillion/gi) ?? [];
    const unique = [...new Set(trillionFigures.map((s) => s.toLowerCase()))];
    expect(unique.sort()).toEqual(["$17.7 trillion", "$4.2 trillion"].sort());
  });

  it("marks defense-budget dollars and crime-rate figures as unknown", () => {
    const overlay = getEditorialAeoOverlay("japan-vs-china")!;
    const military = overlay.faqs.find((f) => f.question.includes("military"));
    const qol = overlay.faqs.find((f) => f.question.includes("quality of life"));
    expect(military?.answer).toMatch(/defense-budget total is unknown/i);
    expect(qol?.answer).toMatch(/crime-rate figures are unknown/i);
  });
});
