import { describe, it, expect } from "vitest";
import {
  applyEditorialAeoOverlay,
  getEditorialAeoOverlay,
} from "../editorial-aeo-overlays";
import type { ComparisonPageData } from "@/types";

const BRIEF_GDP_FAQS = [
  "Is China’s economy bigger than the US in 2026?",
  "What is US vs China GDP (nominal) in 2026?",
  "What is US vs China GDP (PPP) in 2026?",
  "Why do nominal and PPP rankings disagree?",
  "What is GDP per capita for the US vs China?",
  "Will China overtake the US in nominal GDP this decade?",
  "Which GDP measure should journalists and students cite?",
];

function stubGdpPage(): ComparisonPageData {
  return {
    id: "us-vs-china-gdp",
    slug: "us-vs-china-gdp",
    title: "USA vs China GDP 2026",
    shortAnswer: "Old buried answer.",
    verdict: "Existing verdict.",
    category: "countries",
    entities: [
      { id: "us", slug: "united-states-economy", name: "United States Economy", shortDesc: null, imageUrl: null, entityType: "country", position: 0, pros: [], cons: [], bestFor: null },
      { id: "cn", slug: "china-economy", name: "China Economy", shortDesc: null, imageUrl: null, entityType: "country", position: 1, pros: [], cons: [], bestFor: null },
    ],
    attributes: [],
    keyDifferences: [
      { label: "Nominal GDP Size", entityAValue: "$30+ trillion", entityBValue: "$19 trillion", winner: "a" },
    ],
    faqs: [{ question: "Old Q", answer: "Old A" }],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "USA vs China GDP",
      metaDescription: "Compare US and China GDP.",
      publishedAt: "2026-03-27T00:00:00Z",
      updatedAt: "2026-09-15T00:00:00Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 1,
      status: "published",
    },
  };
}

describe("ROO-27 GDP AEO overlay", () => {
  it("rewrites speakable Quick Answer and FAQ to the brief’s 7 questions", () => {
    const overlay = getEditorialAeoOverlay("us-vs-china-gdp");
    expect(overlay).toBeTruthy();
    expect(overlay!.faqs.map((f) => f.question)).toEqual(BRIEF_GDP_FAQS);

    const next = applyEditorialAeoOverlay(stubGdpPage());
    expect(next.shortAnswer).toBe(overlay!.shortAnswer);
    expect(next.quickAnswer?.tldr).toBe(overlay!.shortAnswer);
    expect(next.faqs.map((f) => f.question)).toEqual(BRIEF_GDP_FAQS);
    expect(next.keyDifferences).toEqual(stubGdpPage().keyDifferences);
  });

  it("does not invent a PPP dollar total the live page does not print", () => {
    const overlay = getEditorialAeoOverlay("us-vs-china-gdp")!;
    const ppp = overlay.faqs.find((f) => f.question.includes("(PPP)"));
    expect(ppp?.answer).toMatch(/does not print a single PPP dollar total/i);
  });

  it("leaves unrelated slugs untouched", () => {
    const page = stubGdpPage();
    page.slug = "messi-vs-ronaldo";
    expect(applyEditorialAeoOverlay(page)).toBe(page);
  });
});
