import { describe, expect, it } from "vitest";
import { applyEditorialAeoOverlay, getEditorialAeoOverlay } from "@/lib/data/editorial-aeo-overlays";
import { buildPageTitle, clampDescription } from "@/lib/seo/metadata";
import { findSelfContradictions } from "@/lib/services/numeric-claim-guard";
import type { ComparisonPageData } from "@/types";

function stub(slug: string, first: "lebron" | "other"): ComparisonPageData {
  const lebron = {
    id: "uuid-lebron",
    slug: "lebron-james",
    name: "LeBron James",
    shortDesc: "28.3 PPG in 2025-26",
    imageUrl: null,
    entityType: "person",
    position: 0,
    pros: ["28.3 points per game"],
    cons: ["23rd season"],
    bestFor: "Fans who want a winner",
  };
  const other =
    slug === "lebron-vs-jordan"
      ? {
          id: "uuid-jordan",
          slug: "michael-jordan",
          name: "Michael Jordan",
          shortDesc: "6-0 in the Finals",
          imageUrl: null,
          entityType: "person",
          position: 1,
          pros: ["Perfect 6-0 Finals record"],
          cons: [],
          bestFor: "The GOAT",
        }
      : {
          id: "uuid-kobe",
          slug: "kobe-bryant",
          name: "Kobe Bryant",
          shortDesc: "35.4 PPG",
          imageUrl: null,
          entityType: "person",
          position: 1,
          pros: ["50-40-90"],
          cons: [],
          bestFor: "Peak scoring",
        };
  const entities = first === "lebron" ? [lebron, other] : [other, lebron];
  entities.forEach((entity, index) => {
    entity.position = index;
  });
  return {
    id: "db-row",
    slug,
    title: "LeBron vs Jordan: Complete Comparison (2026)",
    shortAnswer: "LeBron is averaging 28.3 points per game in his 23rd season.",
    verdict: "Jordan is the winner.",
    category: "sports",
    entities,
    keyDifferences: [{ label: "2026 Season PPG", entityAValue: "28.3", entityBValue: "30.1", winner: "a" }],
    attributes: [
      {
        id: "bad",
        slug: "ppg",
        name: "2026 Season / Peak Season PPG",
        unit: null,
        category: "Statistics",
        dataType: "number",
        higherIsBetter: true,
        values: entities.map((entity) => ({
          entityId: entity.id,
          valueText: entity.slug === "lebron-james" ? "28.3 PPG (2025-26)" : "33.4",
          valueNumber: 28.3,
          valueBoolean: null,
          winner: entity.slug === "lebron-james",
        })),
      },
    ],
    faqs: [{ question: "Who wins?", answer: "Jordan, because LeBron averages 28.3." }],
    relatedComparisons: [{ slug: "federer-vs-nadal", title: "Federer vs Nadal", category: "sports" }],
    relatedBlogPosts: [],
    schemaMarkup: { "@type": "FAQPage" },
    metadata: {
      metaTitle: "LeBron vs Jordan: Complete Comparison (2026) | A Versus B",
      metaDescription: "Old description that still says 28.3 points per game for the 2025-26 season.",
      publishedAt: "2024-02-01T00:00:00Z",
      updatedAt: "2026-09-29T00:00:00Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 99,
      status: "published",
    },
  };
}

function pageText(page: ComparisonPageData): string {
  return [
    page.title,
    page.shortAnswer,
    page.verdict,
    page.expertAnalysis,
    page.quickAnswer?.tldr,
    page.quickAnswer?.keyFact,
    page.quickAnswer?.winnerReason,
    ...page.faqs.map((faq) => `${faq.question} ${faq.answer}`),
    ...page.entities.flatMap((entity) => [entity.shortDesc, entity.bestFor, ...entity.pros, ...entity.cons]),
    ...page.keyDifferences.flatMap((row) => [row.label, row.entityAValue, row.entityBValue]),
    ...page.attributes.flatMap((attr) => [attr.name, attr.category, ...attr.values.map((value) => value.valueText)]),
  ].join("\n");
}

describe("NBA 2026-27 season overlays", () => {
  for (const slug of ["lebron-vs-jordan", "kobe-bryant-vs-lebron-james"] as const) {
    it(`replaces the 28.3 scorecard on ${slug} and keeps winnerName null`, () => {
      const overlay = getEditorialAeoOverlay(slug);
      expect(overlay?.quickAnswer.winnerName).toBeNull();
      expect(overlay?.faqs).toHaveLength(6);
      const next = applyEditorialAeoOverlay(stub(slug, "lebron"));
      const text = pageText(next);
      expect(text).not.toMatch(/28\.3/);
      expect(text).not.toMatch(/\b23\.0\b/);
      expect(text).not.toMatch(/\$8/);
      expect(text).not.toMatch(/9-1/);
      expect(text).not.toMatch(/6-0/);
      expect(text).toContain("20.9");
      expect(text).toContain("Stats as of October 3, 2026");
      expect(text).toContain("24th season");
      expect(text).toContain("Philadelphia 76ers");
      expect(next.quickAnswer?.winnerName).toBeNull();
      expect(next.quickAnswer?.tldr).toBe(next.shortAnswer);
      expect(next.metadata.publishedAt).toBe("2024-02-01T00:00:00Z");
      expect(next.metadata.updatedAt).toBe("2026-10-03T00:00:00Z");
      expect(next.metadata.viewCount).toBe(99);
      expect(next.schemaMarkup).toBeUndefined();
      expect(buildPageTitle(next.metadata.metaTitle).length).toBeLessThanOrEqual(60);
      const description = clampDescription(next.metadata.metaDescription);
      expect(description.length).toBeGreaterThanOrEqual(70);
      expect(description.length).toBeLessThanOrEqual(160);
      expect(findSelfContradictions(next)).toEqual([]);
      const lebronPpg = next.attributes.find((attr) => attr.slug === "season-2526-ppg");
      expect(lebronPpg?.values.find((value) => value.entityId === "uuid-lebron")?.valueText).toBe("20.9");
      expect(lebronPpg?.dataType).toBe("text");
      expect(next.resources?.map((resource) => resource.url).join("\n")).not.toMatch(/philadelphia-76ers/);
      expect(next.relatedComparisons.map((item) => item.slug)).not.toContain("federer-vs-nadal");
      expect(next.relatedComparisons.map((item) => item.slug)).toContain("messi-vs-ronaldo");
    });
  }

  it("keeps LeBron's 20.9 on LeBron when the database lists Jordan first", () => {
    const next = applyEditorialAeoOverlay(stub("lebron-vs-jordan", "other"));
    const ppg = next.attributes.find((attr) => attr.slug === "season-2526-ppg");
    expect(ppg?.values.find((value) => value.entityId === "uuid-lebron")?.valueText).toBe("20.9");
    expect(ppg?.values.find((value) => value.entityId === "uuid-jordan")?.valueText).toMatch(/No 2025-26/);
    const careerPpg = next.keyDifferences.find((row) => row.label === "Career points per game");
    expect(careerPpg?.entityAValue).toBe("30.1");
    expect(careerPpg?.entityBValue).toBe("26.8");
    expect(careerPpg?.winner).toBe("a");
  });

  it("does not replace an unrelated scorecard", () => {
    const page = stub("messi-vs-ronaldo", "lebron");
    page.slug = "messi-vs-ronaldo";
    expect(applyEditorialAeoOverlay(page).attributes).toEqual(page.attributes);
  });
});
