import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock all external services
vi.mock('@sentry/nextjs', () => ({
  captureCheckIn: vi.fn().mockReturnValue('check-in-id'),
}))

vi.mock('@/lib/services/pipeline-service', () => ({
  recordPipelineRun: vi.fn().mockResolvedValue(undefined),
  mergeOpportunities: vi.fn().mockResolvedValue(undefined),
}))

vi.mock('@/lib/services/email', () => ({
  sendNotificationEmail: vi.fn().mockResolvedValue(undefined),
}))

vi.mock('@/lib/services/content-discovery', () => ({
  discoverTopics: vi.fn().mockResolvedValue([
    {
      topic: 'Python vs JavaScript',
      source: 'reddit',
      type: 'comparison',
      entityA: 'Python',
      entityB: 'JavaScript',
      opportunityScore: 85,
      searchVolume: 5000,
    },
    {
      topic: 'Best AI tools 2026',
      source: 'tavily',
      type: 'blog',
      entityA: null,
      entityB: null,
      opportunityScore: 60,
    },
  ]),
}))

vi.mock('@/lib/services/ai-comparison-generator', () => ({
  generateComparison: vi.fn().mockResolvedValue({
    success: true,
    comparison: {
      slug: 'javascript-vs-python',
      title: 'Python vs JavaScript',
      shortAnswer: 'Both are great.',
      keyDifferences: [{ label: 'Use Case', entityAValue: 'ML', entityBValue: 'Web', winner: 'tie' }],
      verdict: 'Choose based on use case.',
      category: 'technology',
      entities: [
        { id: 'e1', slug: 'python', name: 'Python', shortDesc: 'A language', imageUrl: null, entityType: 'technology', position: 0, pros: ['Easy'], cons: ['Slow'], bestFor: 'ML' },
        { id: 'e2', slug: 'javascript', name: 'JavaScript', shortDesc: 'Web lang', imageUrl: null, entityType: 'technology', position: 1, pros: ['Fast'], cons: ['Complex'], bestFor: 'Web' },
      ],
      attributes: [],
      faqs: [{ question: 'Which is better?', answer: 'Depends on use case.' }],
      relatedComparisons: [],
      relatedBlogPosts: [],
      metadata: { metaTitle: 'Python vs JS', metaDescription: 'Compare them.', publishedAt: null, updatedAt: new Date().toISOString(), isAutoGenerated: true, isHumanReviewed: false, viewCount: 0 },
    },
  }),
}))

vi.mock('@/lib/services/comparison-service', () => ({
  getComparisonBySlug: vi.fn().mockResolvedValue(null),
  saveComparison: vi.fn().mockResolvedValue({ id: 'saved-1' }),
}))

vi.mock('@/lib/services/content-quality', () => ({
  scoreComparison: vi.fn().mockReturnValue({ totalScore: 75, grade: 'B' }),
}))

vi.mock('@/lib/services/blog-generator', () => ({
  generateBlogArticle: vi.fn().mockResolvedValue({
    slug: 'best-ai-tools-2026',
    title: 'Best AI Tools 2026',
    content: 'Article content here.',
    category: 'technology',
  }),
  saveBlogArticle: vi.fn().mockResolvedValue({ id: 'blog-1' }),
}))

vi.mock('@/lib/services/generation-queue', () => ({
  enqueueBatch: vi.fn().mockResolvedValue({ enqueued: 1, skipped: 0 }),
  processQueue: vi.fn().mockResolvedValue({
    succeeded: 1,
    failed: 0,
    slugs: ['javascript-vs-python'],
    errors: [],
  }),
}))

import { GET } from '../auto-generate/route'
import { NextRequest } from 'next/server'

function makeRequest(cronSecret?: string): NextRequest {
  const url = 'http://localhost:3000/api/cron/auto-generate'
  const headers: Record<string, string> = {}
  if (cronSecret) {
    headers['authorization'] = `Bearer ${cronSecret}`
  }
  return new NextRequest(url, { headers })
}

describe('GET /api/cron/auto-generate', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    delete process.env.CRON_SECRET
  })

  it('runs pipeline successfully without CRON_SECRET', async () => {
    const res = await GET(makeRequest())
    const body = await res.json()

    expect(res.status).toBe(200)
    expect(body.success).toBe(true)
    expect(body.discovered).toBe(2)
    expect(body.generated).toBe(1)
    expect(body.blogArticlesCreated).toBe(1)
    expect(body.category).toBeDefined()
  })

  it('returns 401 when CRON_SECRET is set but not provided', async () => {
    process.env.CRON_SECRET = 'my-secret'

    const res = await GET(makeRequest())
    expect(res.status).toBe(401)
  })

  it('allows access with correct CRON_SECRET', async () => {
    process.env.CRON_SECRET = 'my-secret'

    const res = await GET(makeRequest('my-secret'))
    const body = await res.json()

    expect(res.status).toBe(200)
    expect(body.success).toBe(true)
  })

  it('reports discovery source breakdown', async () => {
    const res = await GET(makeRequest())
    const body = await res.json()

    expect(body.discoveryBySource).toBeDefined()
    expect(body.discoveryBySource.reddit).toBe(1)
    expect(body.discoveryBySource.tavily).toBe(1)
  })

  it('includes generated page slugs in response', async () => {
    const res = await GET(makeRequest())
    const body = await res.json()

    expect(body.newPages).toContain('javascript-vs-python')
    expect(body.newBlogArticles).toContain('best-ai-tools-2026')
  })

  it('records pipeline run', async () => {
    const { recordPipelineRun } = await import('@/lib/services/pipeline-service')
    await GET(makeRequest())

    expect(recordPipelineRun).toHaveBeenCalledOnce()
    expect(vi.mocked(recordPipelineRun).mock.calls[0][0]).toMatchObject({
      mode: 'full',
    })
  })

  it('sends email notification', async () => {
    const { sendNotificationEmail } = await import('@/lib/services/email')
    await GET(makeRequest())

    expect(sendNotificationEmail).toHaveBeenCalledOnce()
    const call = vi.mocked(sendNotificationEmail).mock.calls[0][0]
    expect(call.subject).toContain('Auto-Gen')
    expect(call.type).toBe('cron-report')
  })

  it('handles discovery failure gracefully', async () => {
    const { discoverTopics } = await import('@/lib/services/content-discovery')
    vi.mocked(discoverTopics).mockRejectedValueOnce(new Error('API down'))

    const res = await GET(makeRequest())
    const body = await res.json()

    expect(res.status).toBe(200)
    expect(body.success).toBe(true)
    expect(body.discovered).toBe(0)
    expect(body.errors.some((e: string) => e.includes('Discovery failed'))).toBe(true)
  })
})
