import { describe, expect, it } from "vitest";
import {
  attributesForGeneratedComparison,
  buildUserComparisonContent,
  provisionalPageNeedsRegeneration,
  readPromotionState,
  readSnapshotAttributes,
  withRecheckResult,
} from "@/lib/generation/comparison-content";
import type { ComparisonAttribute } from "@/types";

const attributes: ComparisonAttribute[] = [
  {
    id: "attr-length",
    slug: "length",
    name: "Length",
    unit: "ft",
    category: "Size",
    dataType: "number",
    higherIsBetter: null,
    values: [
      { entityId: "gen-ent-0-5", valueText: "16 ft", valueNumber: 16, valueBoolean: null },
      { entityId: "gen-ent-1-9", valueText: "12 ft", valueNumber: 12, valueBoolean: null },
    ],
  },
];

describe("user comparison content", () => {
  it("stores sources and remaps attribute values onto the database entity ids", () => {
    const content = buildUserComparisonContent({
      citationStats: {
        sourceCount: 2,
        dataPointCount: 4,
        reviewsAnalyzed: null,
        preferencePercent: null,
        preferenceEntity: null,
        lastResearched: "2026-10-03T00:00:00.000Z",
        sources: [
          { name: "rei.com", url: "https://rei.com/canoe" },
          { name: "wikipedia.org", url: "https://en.wikipedia.org/wiki/Canoe" },
        ],
      },
      attributes,
      entityIdMap: new Map([
        ["gen-ent-0-5", "db-canoe"],
        ["gen-ent-1-9", "db-kayak"],
      ]),
      promoted: false,
      reasons: ["only 0 sources (need 2)"],
      now: new Date("2026-10-03T17:00:00.000Z"),
    });

    expect(content.citationStats?.sourceCount).toBe(2);
    expect(content.attributes?.[0].values.map((value) => value.entityId)).toEqual(["db-canoe", "db-kayak"]);
    expect(content.promotion.attempts).toBe(1);
    expect(readSnapshotAttributes(content)).toHaveLength(1);
  });

  it("keeps the original attribute snapshot when a recheck only adds sources", () => {
    const previous = buildUserComparisonContent({
      attributes,
      entityIdMap: new Map([
        ["gen-ent-0-5", "db-canoe"],
        ["gen-ent-1-9", "db-kayak"],
      ]),
      promoted: false,
      reasons: ["only 0 sources (need 2)"],
      now: new Date("2026-10-03T17:00:00.000Z"),
    });
    const next = withRecheckResult(previous, {
      citationStats: {
        sourceCount: 2,
        dataPointCount: 2,
        reviewsAnalyzed: null,
        preferencePercent: null,
        preferenceEntity: null,
        lastResearched: "2026-10-03T21:00:00.000Z",
        sources: [{ name: "nps.gov", url: "https://nps.gov/canoe" }],
      },
      reasons: [],
      now: new Date("2026-10-03T21:00:00.000Z"),
    });
    expect(next.attributes?.[0].values[0].entityId).toBe("db-canoe");
    expect(next.promotion.attempts).toBe(2);
    expect(readPromotionState(next).attempts).toBe(2);
    expect(next.citationStats?.sources).toHaveLength(1);
  });
});

describe("attributes shown on a generated comparison", () => {
  const travelMetrics: ComparisonAttribute[] = Array.from({ length: 71 }, (_, index) => ({
    id: `flight-${index}`,
    slug: `flight-metric-${index}`,
    name: `Flight metric ${index}`,
    unit: null,
    category: "Travel",
    dataType: "number",
    higherIsBetter: null,
    values: [{ entityId: "kayak-com", valueText: String(index), valueNumber: index, valueBoolean: null }],
  }));

  it("shows the comparison snapshot, not the shared entity's stored metrics", () => {
    const shown = attributesForGeneratedComparison(
      { attributes, promotion: { attempts: 1, lastAttemptAt: null, lastReasons: [] } },
      travelMetrics,
      { isAutoGenerated: true, status: "provisional" },
    );
    expect(shown.map((row) => row.slug)).toEqual(["length"]);
  });

  it("shows no rows when a provisional generated page has no snapshot yet", () => {
    const shown = attributesForGeneratedComparison(null, travelMetrics, {
      isAutoGenerated: true,
      status: "provisional",
    });
    expect(shown).toEqual([]);
  });

  it("keeps entity metrics for a page that was not visitor-generated", () => {
    const shown = attributesForGeneratedComparison(null, travelMetrics, {
      isAutoGenerated: false,
      status: "published",
    });
    expect(shown).toHaveLength(71);
  });

  it("keeps entity rows for a published week2 page whose content.attributes lack values", () => {
    // scripts/batch-insert-week2-compare.mjs stored this shape on published,
    // human-reviewed pages such as figma-vs-sketch.
    const week2 = {
      intro: "",
      entities: [
        { id: "figma", name: "Figma" },
        { id: "sketch", name: "Sketch" },
      ],
      attributes: [
        { name: "Platform", winner: "figma", figma: "Web", sketch: "macOS" },
      ],
      verdict: {},
      updatedDate: "2026-07-14",
    };
    const entityRows: ComparisonAttribute[] = [
      {
        id: "platform",
        slug: "platform",
        name: "Platform",
        unit: null,
        category: "Product",
        dataType: "text",
        higherIsBetter: null,
        values: [
          { entityId: "figma", valueText: "Web", valueNumber: null, valueBoolean: null },
          { entityId: "sketch", valueText: "macOS", valueNumber: null, valueBoolean: null },
        ],
      },
    ];
    const shown = attributesForGeneratedComparison(week2, entityRows, {
      isAutoGenerated: false,
      status: "published",
    });
    expect(shown).toEqual(entityRows);
  });

  it("keeps entity rows for a published editorial page", () => {
    const editorial = { expertAnalysis: "Figma wins for teams that design together." };
    const shown = attributesForGeneratedComparison(editorial, travelMetrics, {
      isAutoGenerated: false,
      status: "published",
    });
    expect(shown).toHaveLength(71);
  });

  it("does not treat an empty content.attributes list as the page table", () => {
    const shown = attributesForGeneratedComparison(
      { attributes: [] },
      travelMetrics,
      { isAutoGenerated: false, status: "published" },
    );
    expect(shown).toHaveLength(71);
  });
});

describe("provisional pages without a visitor table", () => {
  it("are regenerable only when a fresh read recorded that the table is missing", () => {
    expect(provisionalPageNeedsRegeneration({
      status: "provisional",
      isAutoGenerated: true,
      visitorTableSaved: false,
    })).toBe(true);
    expect(provisionalPageNeedsRegeneration({
      status: "provisional",
      isAutoGenerated: true,
      visitorTableSaved: true,
    })).toBe(false);
    expect(provisionalPageNeedsRegeneration({
      status: "published",
      isAutoGenerated: false,
      visitorTableSaved: false,
    })).toBe(false);
    // Older cached payloads omit the flag. Leave those pages alone.
    expect(provisionalPageNeedsRegeneration({
      status: "provisional",
      isAutoGenerated: true,
    })).toBe(false);
  });
});
