/**
 * The stored isHumanReviewed column still publishes an auto-generated batch
 * save. The allowlist is what the page and the history route read.
 */
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import type { ComparisonPageData } from "@/types";
import { ExpertAnalysis } from "@/components/comparison/ExpertAnalysis";
import { ComparisonHero } from "@/components/comparison/ComparisonHero";
import { HUMAN_REVIEWED_SLUGS } from "@/lib/editorial/human-reviewed";
import { decidePersistedStatus } from "@/lib/generation/promotion";

vi.mock("@/lib/services/comparison-service", () => ({
  getComparisonBySlug: vi.fn(),
}));

vi.mock("@/lib/services/version-service", async () => {
  const actual = await vi.importActual<typeof import("@/lib/services/version-service")>(
    "@/lib/services/version-service",
  );
  return {
    ...actual,
    getComparisonHistory: vi.fn(async () => []),
  };
});

import { GET } from "@/app/api/comparisons/[slug]/history/route";
import { getComparisonBySlug } from "@/lib/services/comparison-service";

beforeAll(() => {
  const view = window as Window & {
    matchMedia: typeof window.matchMedia;
    IntersectionObserver: typeof IntersectionObserver;
  };
  if (!view.matchMedia) {
    view.matchMedia = ((query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: () => {},
      removeListener: () => {},
      addEventListener: () => {},
      removeEventListener: () => {},
      dispatchEvent: () => false,
    })) as unknown as typeof window.matchMedia;
  }
  if (!view.IntersectionObserver) {
    class Observer {
      observe() {}
      unobserve() {}
      disconnect() {}
    }
    view.IntersectionObserver = Observer as unknown as typeof IntersectionObserver;
  }
});

afterEach(() => {
  HUMAN_REVIEWED_SLUGS.length = 0;
  vi.clearAllMocks();
});

function page(slug: string): ComparisonPageData {
  return {
    id: "cmp-1",
    slug,
    title: "Alpha Widget vs Beta Widget",
    shortAnswer: "Alpha Widget is the better pick for most people.",
    verdict: "Alpha Widget",
    keyDifferences: [],
    category: "products",
    entities: [
      {
        id: "a",
        slug: "alpha-widget",
        name: "Alpha Widget",
        shortDesc: "A widget",
        imageUrl: null,
        entityType: "product",
        position: 0,
        pros: ["Light"],
        cons: ["Slow"],
        bestFor: "Everyday use",
      },
      {
        id: "b",
        slug: "beta-widget",
        name: "Beta Widget",
        shortDesc: "Another widget",
        imageUrl: null,
        entityType: "product",
        position: 1,
        pros: ["Fast"],
        cons: ["Heavy"],
        bestFor: "Power users",
      },
    ],
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    expertAnalysis: "First paragraph of the analysis.\n\nSecond paragraph with a sourced figure.",
    metadata: {
      metaTitle: "Alpha Widget vs Beta Widget",
      metaDescription: "Compare the two widgets.",
      publishedAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-06-01T00:00:00.000Z",
      isAutoGenerated: true,
      isHumanReviewed: true,
      viewCount: 0,
      status: "published",
    },
  };
}

describe("legacy indexing flag", () => {
  it("publishes an auto-generated batch save when the stored flag is true, with no byline and no history review entry", async () => {
    expect(HUMAN_REVIEWED_SLUGS).toEqual([]);
    const slug = "alpha-widget-vs-beta-widget";
    const comparison = page(slug);

    expect(
      decidePersistedStatus(
        { isAutoGenerated: true, isHumanReviewed: true },
        "batch",
        false,
      ),
    ).toBe("published");

    render(
      <>
        <ComparisonHero comparison={comparison} />
        <ExpertAnalysis
          analysis={comparison.expertAnalysis!}
          slug={slug}
          entityAName="Alpha Widget"
          entityBName="Beta Widget"
          updatedAt={comparison.metadata.updatedAt}
        />
      </>,
    );
    expect(screen.queryByRole("link", { name: /Daniel Rozin/ })).not.toBeInTheDocument();
    expect(screen.queryByText(/Human reviewed/)).not.toBeInTheDocument();
    expect(screen.getByText("A Versus B")).toBeInTheDocument();

    vi.mocked(getComparisonBySlug).mockResolvedValue({
      metadata: {
        publishedAt: comparison.metadata.publishedAt,
        updatedAt: comparison.metadata.updatedAt,
        isAutoGenerated: true,
        isHumanReviewed: true,
      },
    } as never);
    const res = await GET(new Request(`http://localhost/api/comparisons/${slug}/history`), {
      params: Promise.resolve({ slug }),
    });
    const body = await res.json();
    expect(body.versions.some((version: { action: string }) => version.action === "reviewed")).toBe(false);
    expect(JSON.stringify(body)).not.toContain("Content reviewed and verified by human editor");
  });
});
