import { describe, expect, it } from "vitest";
import { assessUserGenerationPromotion, decidePersistedStatus } from "@/lib/generation/promotion";

const passing = {
  shortAnswer: "Alpha leads on price and speed in every published benchmark we checked.",
  verdict:
    "Choose Alpha when you want the faster option. Choose Beta when you want the cheaper one and can wait a little longer.",
  keyDifferences: [
    { label: "Price", entityAValue: "$10", entityBValue: "$20" },
    { label: "Speed", entityAValue: "3 GHz", entityBValue: "2 GHz" },
    { label: "Weight", entityAValue: "150 g", entityBValue: "180 g" },
  ],
  attributes: [
    { name: "Price", values: [{ valueNumber: 10 }, { valueNumber: 20 }] },
    { name: "Speed", values: [{ valueText: "3 GHz" }] },
    { name: "Weight", values: [{ valueText: "150 grams" }] },
    { name: "Year", values: [{ valueNumber: 2024 }] },
  ],
  entities: [
    { pros: ["fast", "cheap"], cons: ["loud"] },
    { pros: ["quiet", "light"], cons: ["slow"] },
  ],
  citationStats: { sourceCount: 2, sources: [{ name: "Maker spec" }, { name: "Lab note" }] },
};

describe("assessUserGenerationPromotion", () => {
  it("passes a comparison with depth, sources, numbers, and no contradictions", () => {
    const decision = assessUserGenerationPromotion(passing);
    expect(decision.pass).toBe(true);
    expect(decision.reasons).toEqual([]);
  });

  it("fails closed when there are not enough sources or numeric data", () => {
    const decision = assessUserGenerationPromotion({
      ...passing,
      citationStats: { sourceCount: 0, sources: [] },
      attributes: [],
      keyDifferences: passing.keyDifferences.map((row) => ({
        ...row,
        entityAValue: "better",
        entityBValue: "worse",
      })),
    });
    expect(decision.pass).toBe(false);
    expect(decision.reasons.some((reason) => reason.includes("sources"))).toBe(true);
  });
});

describe("decidePersistedStatus", () => {
  const auto = { isAutoGenerated: true, isHumanReviewed: false };

  it("publishes a visitor request only when promotion passes", () => {
    expect(decidePersistedStatus(auto, "user", true)).toBe("published");
    expect(decidePersistedStatus(auto, "user", false)).toBe("provisional");
  });

  it("keeps cron and batch auto-generated pages archived", () => {
    expect(decidePersistedStatus(auto, "batch", true)).toBe("archived");
    expect(decidePersistedStatus({ isAutoGenerated: false, isHumanReviewed: true }, "batch", false)).toBe(
      "published",
    );
  });
});
