import { afterEach, describe, expect, it } from "vitest";
import { HUMAN_REVIEWED_SLUGS } from "@/lib/editorial/human-reviewed";
import { assessUserGenerationPromotion, decidePersistedStatus } from "@/lib/generation/promotion";

const passing = {
  shortAnswer: "Alpha leads on price and speed in every published benchmark we checked.",
  verdict:
    "Choose Alpha when you want the faster option. Choose Beta when you want the cheaper one and can wait a little longer.",
  keyDifferences: [
    { label: "Price", entityAValue: "$10", entityBValue: "$20" },
    { label: "Speed", entityAValue: "3 GHz", entityBValue: "2 GHz" },
    { label: "Weight", entityAValue: "150 g", entityBValue: "180 g" },
  ],
  attributes: [
    { name: "Price", values: [{ valueNumber: 10 }, { valueNumber: 20 }] },
    { name: "Speed", values: [{ valueText: "3 GHz" }, { valueText: "2 GHz" }] },
    { name: "Weight", values: [{ valueText: "150 grams" }, { valueText: "180 grams" }] },
    { name: "Year", values: [{ valueNumber: 2024 }, { valueNumber: 2020 }] },
  ],
  entities: [
    { pros: ["fast", "cheap"], cons: ["loud"] },
    { pros: ["quiet", "light"], cons: ["slow"] },
  ],
  citationStats: { sourceCount: 2, sources: [{ name: "Maker spec" }, { name: "Lab note" }] },
};

describe("assessUserGenerationPromotion", () => {
  it("passes a comparison with depth, sources, numbers, and no contradictions", () => {
    const decision = assessUserGenerationPromotion(passing);
    expect(decision.pass).toBe(true);
    expect(decision.reasons).toEqual([]);
  });

  it("counts distinct source URLs even when the stored sourceCount is 0", () => {
    const decision = assessUserGenerationPromotion({
      ...passing,
      citationStats: {
        sourceCount: 0,
        sources: [
          { name: "rei.com", url: "https://www.rei.com/canoe" },
          { name: "rei.com", url: "https://rei.com/kayak" },
          { name: "wikipedia.org", url: "https://en.wikipedia.org/wiki/Kayak" },
        ],
      },
    });
    expect(decision.pass).toBe(true);
  });

  it("does not treat one-sided inherited attributes as this comparison's data", () => {
    const decision = assessUserGenerationPromotion({
      ...passing,
      attributes: Array.from({ length: 8 }, (_, index) => ({
        name: `Airline metric ${index}`,
        values: [{ valueNumber: 100 + index, entityId: "kayak-travel-site" }],
      })),
    });
    expect(decision.pass).toBe(false);
    expect(decision.reasons.some((reason) => reason.includes("one side"))).toBe(true);
    expect(decision.reasons.some((reason) => reason.includes("substantive attributes"))).toBe(true);
  });

  it("fails a canoe-shaped page that has numbers and depth but no sources", () => {
    const decision = assessUserGenerationPromotion({
      ...passing,
      shortAnswer:
        "Canoes feature an open design and typically seat 2-3 people, while kayaks usually accommodate 1-2 paddlers.",
      citationStats: { sourceCount: 0, sources: [] },
    });
    expect(decision.pass).toBe(false);
    expect(decision.reasons).toEqual(["only 0 sources (need 2)"]);
  });

  it("fails closed when there are not enough sources or numeric data", () => {
    const decision = assessUserGenerationPromotion({
      ...passing,
      citationStats: { sourceCount: 0, sources: [] },
      attributes: [],
      keyDifferences: passing.keyDifferences.map((row) => ({
        ...row,
        entityAValue: "better",
        entityBValue: "worse",
      })),
    });
    expect(decision.pass).toBe(false);
    expect(decision.reasons.some((reason) => reason.includes("sources"))).toBe(true);
  });
});

describe("decidePersistedStatus", () => {
  const auto = { isAutoGenerated: true, isHumanReviewed: false };

  afterEach(() => {
    HUMAN_REVIEWED_SLUGS.length = 0;
  });

  it("publishes a visitor request only when promotion passes", () => {
    expect(decidePersistedStatus(auto, "user", true)).toBe("published");
    expect(decidePersistedStatus(auto, "user", false)).toBe("provisional");
  });

  it("archives auto-generated batch pages even when the stored review flag is true", () => {
    expect(decidePersistedStatus(auto, "batch", true, "messi-vs-ronaldo")).toBe("archived");
    expect(
      decidePersistedStatus(
        { isAutoGenerated: true, isHumanReviewed: true },
        "batch",
        false,
        "figma-vs-sketch",
      ),
    ).toBe("archived");
    expect(decidePersistedStatus({ isAutoGenerated: false, isHumanReviewed: true }, "batch", false)).toBe(
      "published",
    );
  });

  it("publishes an auto-generated batch page only when its slug is allowlisted", () => {
    HUMAN_REVIEWED_SLUGS.push("figma-vs-sketch");
    expect(
      decidePersistedStatus(
        { isAutoGenerated: true, isHumanReviewed: false },
        "batch",
        false,
        "figma-vs-sketch",
      ),
    ).toBe("published");
  });
});
