import { describe, expect, it, vi } from "vitest";
import {
  anthropicCallsAllowed,
  eligiblePromotionCandidates,
  promotionRecheckLimitsFromEnv,
  runPromotionRecheck,
  type PromotionRecheckDeps,
} from "@/lib/generation/promotion-recheck";
import type { ComparisonPageData } from "@/types";

function page(overrides: Partial<ComparisonPageData> = {}): ComparisonPageData {
  return {
    id: "cmp",
    slug: "canoe-vs-kayak",
    title: "Canoe vs Kayak",
    shortAnswer: "Canoes seat 2-3 people and carry more gear. Kayaks are faster for one or two paddlers.",
    verdict:
      "Choose a canoe if you want cargo and easy entry. Choose a kayak if you want speed and a covered cockpit.",
    category: "outdoors",
    entities: [
      {
        id: "db-canoe",
        slug: "canoe",
        name: "Canoe",
        shortDesc: "Open boat",
        imageUrl: null,
        entityType: "product",
        position: 0,
        pros: ["More cargo", "Easier entry"],
        cons: ["Slower"],
        bestFor: "Families",
      },
      {
        id: "db-kayak",
        slug: "kayak",
        name: "Kayak",
        shortDesc: "Covered boat",
        imageUrl: null,
        entityType: "product",
        position: 1,
        pros: ["Faster", "Tracks straighter"],
        cons: ["Less cargo"],
        bestFor: "Solo paddlers",
      },
    ],
    keyDifferences: [
      { label: "Seats", entityAValue: "2-3 people", entityBValue: "1-2 people" },
      { label: "Cargo", entityAValue: "40-80 lbs", entityBValue: "25-50 lbs" },
      { label: "Speed", entityAValue: "3-4 mph", entityBValue: "4-6 mph" },
    ],
    attributes: [
      { id: "a1", slug: "seats", name: "Seats", unit: "people", category: "Size", dataType: "number", higherIsBetter: null, values: [{ entityId: "db-canoe", valueText: "2-3", valueNumber: 3, valueBoolean: null }, { entityId: "db-kayak", valueText: "1-2", valueNumber: 2, valueBoolean: null }] },
      { id: "a2", slug: "cargo", name: "Cargo", unit: "lbs", category: "Size", dataType: "number", higherIsBetter: true, values: [{ entityId: "db-canoe", valueText: "60 lbs", valueNumber: 60, valueBoolean: null }, { entityId: "db-kayak", valueText: "35 lbs", valueNumber: 35, valueBoolean: null }] },
      { id: "a3", slug: "speed", name: "Speed", unit: "mph", category: "Performance", dataType: "number", higherIsBetter: true, values: [{ entityId: "db-canoe", valueText: "3.5 mph", valueNumber: 3.5, valueBoolean: null }, { entityId: "db-kayak", valueText: "5 mph", valueNumber: 5, valueBoolean: null }] },
      { id: "a4", slug: "length", name: "Length", unit: "ft", category: "Size", dataType: "number", higherIsBetter: null, values: [{ entityId: "db-canoe", valueText: "16 ft", valueNumber: 16, valueBoolean: null }, { entityId: "db-kayak", valueText: "12 ft", valueNumber: 12, valueBoolean: null }] },
    ],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "Canoe vs Kayak",
      metaDescription: "Canoe vs Kayak",
      publishedAt: null,
      updatedAt: "2026-10-03T17:00:00.000Z",
      isAutoGenerated: true,
      isHumanReviewed: false,
      viewCount: 0,
      status: "provisional",
    },
    citationStats: { sourceCount: 0, dataPointCount: 4, reviewsAnalyzed: null, preferencePercent: null, preferenceEntity: null, lastResearched: "2026-10-03T17:00:00.000Z", sources: [] },
    ...overrides,
  };
}

function harness(pages: Record<string, ComparisonPageData>, limits?: Partial<PromotionRecheckDeps["limits"]>) {
  const enrich = vi.fn(async () => [
    { name: "rei.com", url: "https://www.rei.com/canoe" },
    { name: "wikipedia.org", url: "https://en.wikipedia.org/wiki/Kayak" },
  ]);
  const save = vi.fn<PromotionRecheckDeps["save"]>(async () => true);
  const revalidate = vi.fn(async () => {});
  const log = vi.fn(async () => {});
  const deps: PromotionRecheckDeps = {
    loadCandidates: async () => Object.keys(pages).map((slug) => ({ slug, content: { promotion: { attempts: 0, lastReasons: [], lastAttemptAt: null } } })),
    loadComparison: async (slug) => pages[slug] ?? null,
    enrich,
    save,
    revalidate,
    log,
    limits: { batch: 10, maxAttempts: 5, tavilyCap: 6, anthropicCap: 0, ...limits },
    now: () => new Date("2026-10-03T21:00:00.000Z"),
  };
  return { deps, enrich, save, revalidate, log };
}

describe("runPromotionRecheck", () => {
  it("promotes a page once Tavily supplies two sources and does not call Anthropic", async () => {
    vi.stubEnv("GENERATION_FREEZE", "true");
    const { deps, enrich, save, revalidate, log } = harness({ "canoe-vs-kayak": page() });
    const report = await runPromotionRecheck(deps);

    expect(report.promoted).toEqual(["canoe-vs-kayak"]);
    expect(report.anthropicCalls).toBe(0);
    expect(enrich).toHaveBeenCalledTimes(1);
    expect(save).toHaveBeenCalledWith(expect.objectContaining({ slug: "canoe-vs-kayak", status: "published" }));
    const savedContent = save.mock.calls[0][0].content as {
      citationStats: { sourceCount: number };
      attributes?: unknown;
    };
    expect(savedContent.citationStats.sourceCount).toBe(2);
    expect(savedContent.attributes).toBeUndefined();
    expect(revalidate).toHaveBeenCalledWith("canoe-vs-kayak", true);
    expect(log).toHaveBeenCalledWith("generation_promoted", expect.objectContaining({ slug: "canoe-vs-kayak" }));
  });

  it("stops enriching after the Tavily cap and does not burn an attempt on the deferred row", async () => {
    const pages = {
      "one-vs-two": page({ slug: "one-vs-two" }),
      "three-vs-four": page({ slug: "three-vs-four" }),
    };
    const { deps, enrich, save } = harness(pages, { tavilyCap: 1, batch: 10 });
    const report = await runPromotionRecheck(deps);
    expect(enrich).toHaveBeenCalledTimes(1);
    expect(save).toHaveBeenCalledTimes(1);
    expect(report.deferred).toBe(1);
    expect(report.processed).toBe(1);
  });

  it("does not spend Tavily when the attribute table cannot pass", async () => {
    const polluted = page({
      attributes: Array.from({ length: 6 }, (_, index) => ({
        id: `travel-${index}`,
        slug: `travel-${index}`,
        name: `Airline metric ${index}`,
        unit: "count",
        category: "Travel",
        dataType: "number",
        higherIsBetter: null,
        values: [{ entityId: "db-kayak", valueText: "100", valueNumber: 100, valueBoolean: null }],
      })),
    });
    const { deps, enrich, save } = harness({ "canoe-vs-kayak": polluted });
    const report = await runPromotionRecheck(deps);
    expect(enrich).not.toHaveBeenCalled();
    expect(report.promoted).toEqual([]);
    expect(save).toHaveBeenCalledWith(expect.objectContaining({ status: "provisional" }));
  });

  it("skips slugs that already used their attempts", () => {
    const rows = eligiblePromotionCandidates(
      [
        { slug: "fresh-vs-page", content: { promotion: { attempts: 1 } } },
        { slug: "stuck-vs-page", content: { promotion: { attempts: 5 } } },
      ],
      5,
    );
    expect(rows.map((row) => row.slug)).toEqual(["fresh-vs-page"]);
  });

  it("keeps the Anthropic cap closed unless it is raised", () => {
    expect(anthropicCallsAllowed(0, promotionRecheckLimitsFromEnv().anthropicCap)).toBe(false);
    expect(anthropicCallsAllowed(0, 0)).toBe(false);
    expect(anthropicCallsAllowed(0, 1)).toBe(true);
  });
});
