import { NextResponse } from "next/server";
import { getComparisonBySlug } from "@/lib/services/comparison-service";
import {
  getComparisonHistory,
  generateSyntheticHistory,
} from "@/lib/services/version-service";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;

  // Try to get real history from Redis first
  const realHistory = await getComparisonHistory(slug);

  if (realHistory.length > 0) {
    return NextResponse.json({ versions: realHistory });
  }

  // Fall back to synthetic history from comparison metadata
  const comparison = await getComparisonBySlug(slug);

  if (!comparison) {
    return NextResponse.json(
      { error: "Comparison not found" },
      { status: 404 }
    );
  }

  const syntheticHistory = generateSyntheticHistory({
    publishedAt: comparison.metadata.publishedAt || undefined,
    updatedAt: comparison.metadata.updatedAt,
    isAutoGenerated: comparison.metadata.isAutoGenerated,
    isHumanReviewed: comparison.metadata.isHumanReviewed,
  });

  return NextResponse.json({ versions: syntheticHistory });
}
