import { afterEach, describe, expect, it, vi } from "vitest";
import { HUMAN_REVIEWED_SLUGS } from "@/lib/editorial/human-reviewed";

vi.mock("@/lib/services/comparison-service", () => ({
  getComparisonBySlug: vi.fn(),
}));

vi.mock("@/lib/services/version-service", async () => {
  const actual = await vi.importActual<typeof import("@/lib/services/version-service")>(
    "@/lib/services/version-service",
  );
  return {
    ...actual,
    getComparisonHistory: vi.fn(async () => []),
  };
});

import { GET } from "../route";
import { getComparisonBySlug } from "@/lib/services/comparison-service";

const storedReviewed = {
  metadata: {
    publishedAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-06-01T00:00:00.000Z",
    isAutoGenerated: true,
    isHumanReviewed: true,
  },
};

describe("GET /api/comparisons/[slug]/history", () => {
  afterEach(() => {
    HUMAN_REVIEWED_SLUGS.length = 0;
    vi.clearAllMocks();
  });

  it("omits the review entry when the stored flag is true but the slug is not allowlisted", async () => {
    vi.mocked(getComparisonBySlug).mockResolvedValue(storedReviewed as never);

    const res = await GET(new Request("http://localhost/api/comparisons/messi-vs-ronaldo/history"), {
      params: Promise.resolve({ slug: "messi-vs-ronaldo" }),
    });
    const body = await res.json();

    expect(body.versions.some((version: { action: string }) => version.action === "reviewed")).toBe(false);
    expect(JSON.stringify(body)).not.toContain("Content reviewed and verified by human editor");
  });

  it("includes the review entry when the slug is allowlisted", async () => {
    HUMAN_REVIEWED_SLUGS.push("figma-vs-sketch");
    vi.mocked(getComparisonBySlug).mockResolvedValue(storedReviewed as never);

    const res = await GET(new Request("http://localhost/api/comparisons/figma-vs-sketch/history"), {
      params: Promise.resolve({ slug: "figma-vs-sketch" }),
    });
    const body = await res.json();

    expect(body.versions.some((version: { action: string }) => version.action === "reviewed")).toBe(true);
  });
});
