/**
 * JSON-LD Schema Validation Tests
 * Validates all schema generators produce valid schema.org structured data
 */

import { describe, it, expect } from "vitest";
import {
  organizationSchema,
  webSiteSchema,
  webPageSchema,
  speakableSchema,
  comparisonPageSchema,
  faqSchema,
  breadcrumbSchema,
  categoryPageSchema,
  entityPageSchema,
  aggregateRatingSchema,
  newsArticleSchema,
  blogArticleSchema,
  type ComparisonVoteData,
} from "@/lib/seo/schema";
import type {
  ComparisonPageData,
  FAQData,
  CategoryData,
} from "@/types";

// ============================================================
// Test fixtures
// ============================================================

const sampleFaqs: FAQData[] = [
  { question: "Which is better, A or B?", answer: "It depends on your needs." },
  { question: "What is the main difference?", answer: "A is faster, B is cheaper." },
];

const sampleComparison: ComparisonPageData = {
  id: "test-id-1",
  slug: "iphone-vs-samsung",
  title: "iPhone vs Samsung Galaxy",
  shortAnswer: "iPhone excels in ecosystem, Samsung in customization.",
  keyDifferences: [
    { label: "OS", entityAValue: "iOS", entityBValue: "Android", winner: "tie" },
  ],
  verdict: "Both are excellent choices.",
  category: "technology",
  entities: [
    {
      id: "e1",
      slug: "iphone",
      name: "iPhone",
      shortDesc: "Apple's flagship smartphone",
      imageUrl: "https://example.com/iphone.jpg",
      entityType: "product",
      position: 1,
      pros: ["Great ecosystem"],
      cons: ["Expensive"],
      bestFor: "Apple users",
    },
    {
      id: "e2",
      slug: "samsung-galaxy",
      name: "Samsung Galaxy",
      shortDesc: "Samsung's flagship smartphone",
      imageUrl: "https://example.com/samsung.jpg",
      entityType: "product",
      position: 2,
      pros: ["Customizable"],
      cons: ["Bloatware"],
      bestFor: "Android enthusiasts",
    },
  ],
  attributes: [
    {
      id: "a1",
      slug: "price",
      name: "Price",
      unit: "USD",
      category: "specs",
      dataType: "number",
      higherIsBetter: false,
      values: [
        { entityId: "e1", valueText: "$999", valueNumber: 999, valueBoolean: null },
        { entityId: "e2", valueText: "$899", valueNumber: 899, valueBoolean: null, winner: true },
      ],
    },
  ],
  faqs: sampleFaqs,
  relatedComparisons: [{ slug: "pixel-vs-iphone", title: "Pixel vs iPhone", category: "technology" }],
  relatedBlogPosts: [],
  metadata: {
    metaTitle: "iPhone vs Samsung Galaxy - Comparison",
    metaDescription: "Compare iPhone and Samsung Galaxy side by side.",
    publishedAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
    isAutoGenerated: true,
    isHumanReviewed: false,
    viewCount: 1000,
  },
  citationStats: {
    sourceCount: 5,
    dataPointCount: 42,
    reviewsAnalyzed: 200,
    preferencePercent: 55,
    preferenceEntity: "iPhone",
    lastResearched: "2025-06-01",
    sources: [
      { name: "TechRadar", url: "https://techradar.com/review" },
      { name: "CNET", url: "https://cnet.com/review" },
    ],
  },
};

const sampleCategory: CategoryData = {
  slug: "technology",
  name: "Technology",
  description: "Compare tech products and services.",
  icon: "laptop",
  comparisonCount: 150,
  topComparisons: [
    { slug: "iphone-vs-samsung", title: "iPhone vs Samsung Galaxy", category: "technology" },
    { slug: "mac-vs-pc", title: "Mac vs PC", category: "technology" },
  ],
  subcategories: [{ slug: "smartphones", name: "Smartphones", count: 45 }],
};

const sampleVoteData: ComparisonVoteData = {
  votes: { iPhone: 60, "Samsung Galaxy": 40 },
  total: 100,
};

// ============================================================
// Shared validators
// ============================================================

function expectValidContext(schema: Record<string, unknown>) {
  expect(schema["@context"]).toBe("https://schema.org");
}

function expectValidType(schema: Record<string, unknown>, type: string) {
  expect(schema["@type"]).toBe(type);
}

function expectNonEmptyString(value: unknown, field: string) {
  expect(typeof value).toBe("string");
  expect((value as string).length).toBeGreaterThan(0);
}

function expectValidUrl(value: unknown, field: string) {
  expect(typeof value).toBe("string");
  expect((value as string)).toMatch(/^https?:\/\/.+/);
}

function validateSchemaBase(schema: Record<string, unknown>, expectedType: string) {
  expectValidContext(schema);
  expectValidType(schema, expectedType);
}

// ============================================================
// Tests
// ============================================================

describe("JSON-LD Schema Validation", () => {
  describe("organizationSchema", () => {
    it("produces valid Organization schema", () => {
      const schema = organizationSchema();
      validateSchemaBase(schema, "Organization");
      expectNonEmptyString(schema.name, "name");
      expectValidUrl(schema.url, "url");
      expectValidUrl(schema.logo, "logo");
      expect(Array.isArray(schema.sameAs)).toBe(true);
      expect((schema.sameAs as string[]).length).toBeGreaterThan(0);
      for (const url of schema.sameAs as string[]) {
        expectValidUrl(url, "sameAs entry");
      }
      expectNonEmptyString(schema.description, "description");
    });
  });

  describe("webSiteSchema", () => {
    it("produces valid WebSite schema with SearchAction", () => {
      const schema = webSiteSchema();
      validateSchemaBase(schema, "WebSite");
      expectNonEmptyString(schema.name, "name");
      expectValidUrl(schema.url, "url");

      const action = schema.potentialAction as Record<string, unknown>;
      expect(action["@type"]).toBe("SearchAction");
      const target = action.target as Record<string, unknown>;
      expect(target["@type"]).toBe("EntryPoint");
      expect(typeof target.urlTemplate).toBe("string");
      expect((target.urlTemplate as string)).toContain("{search_term_string}");
      expect(action["query-input"]).toBe("required name=search_term_string");
    });
  });

  describe("webPageSchema", () => {
    it("produces valid WebPage schema with all fields", () => {
      const schema = webPageSchema({
        title: "Test Page",
        description: "A test page",
        url: "https://www.aversusb.net/test",
        datePublished: "2025-01-01",
        dateModified: "2025-06-01",
      });
      validateSchemaBase(schema, "WebPage");
      expect(schema.name).toBe("Test Page");
      expect(schema.description).toBe("A test page");
      expectValidUrl(schema.url, "url");
      expect(schema.datePublished).toBe("2025-01-01");
      expect(schema.dateModified).toBe("2025-06-01");

      const isPartOf = schema.isPartOf as Record<string, unknown>;
      expect(isPartOf["@type"]).toBe("WebSite");
    });

    it("omits optional date fields when null", () => {
      const schema = webPageSchema({
        title: "Test Page",
        description: "A test page",
        url: "https://www.aversusb.net/test",
        datePublished: null,
      });
      expect(schema).not.toHaveProperty("datePublished");
      expect(schema).not.toHaveProperty("dateModified");
    });
  });

  describe("speakableSchema", () => {
    it("produces valid SpeakableSpecification schema", () => {
      const url = "https://www.aversusb.net/compare/a-vs-b";
      const schema = speakableSchema(url);
      validateSchemaBase(schema, "WebPage");
      expect(schema["@id"]).toBe(url);
      expect(schema.url).toBe(url);

      const speakable = schema.speakable as Record<string, unknown>;
      expect(speakable["@type"]).toBe("SpeakableSpecification");
      expect(Array.isArray(speakable.cssSelector)).toBe(true);
      expect((speakable.cssSelector as string[]).length).toBeGreaterThan(0);
    });
  });

  describe("faqSchema", () => {
    it("produces valid FAQPage schema", () => {
      const schema = faqSchema(sampleFaqs);
      validateSchemaBase(schema, "FAQPage");

      const entities = schema.mainEntity as Record<string, unknown>[];
      expect(entities).toHaveLength(2);
      for (const entity of entities) {
        expect(entity["@type"]).toBe("Question");
        expectNonEmptyString(entity.name, "question name");
        const answer = entity.acceptedAnswer as Record<string, unknown>;
        expect(answer["@type"]).toBe("Answer");
        expectNonEmptyString(answer.text, "answer text");
      }
    });

    it("handles empty FAQ array", () => {
      const schema = faqSchema([]);
      validateSchemaBase(schema, "FAQPage");
      expect(schema.mainEntity).toHaveLength(0);
    });
  });

  describe("breadcrumbSchema", () => {
    it("produces valid BreadcrumbList schema", () => {
      const items = [
        { name: "Home", url: "https://www.aversusb.net" },
        { name: "Technology", url: "https://www.aversusb.net/category/technology" },
      ];
      const schema = breadcrumbSchema(items);
      validateSchemaBase(schema, "BreadcrumbList");

      const elements = schema.itemListElement as Record<string, unknown>[];
      expect(elements).toHaveLength(2);
      elements.forEach((el, i) => {
        expect(el["@type"]).toBe("ListItem");
        expect(el.position).toBe(i + 1);
        expectNonEmptyString(el.name, "breadcrumb name");
        expectValidUrl(el.item, "breadcrumb item url");
      });
    });

    it("has sequential positions starting at 1", () => {
      const items = [
        { name: "A", url: "https://a.com" },
        { name: "B", url: "https://b.com" },
        { name: "C", url: "https://c.com" },
      ];
      const schema = breadcrumbSchema(items);
      const elements = schema.itemListElement as Record<string, unknown>[];
      elements.forEach((el, i) => {
        expect(el.position).toBe(i + 1);
      });
    });
  });

  describe("comparisonPageSchema", () => {
    it("produces an array of valid schemas", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      expect(Array.isArray(schemas)).toBe(true);
      expect(schemas.length).toBeGreaterThanOrEqual(5); // Article, ItemList, FAQ, Breadcrumb, Dataset, Speakable

      for (const schema of schemas) {
        expectValidContext(schema as Record<string, unknown>);
        expectNonEmptyString((schema as Record<string, unknown>)["@type"], "@type");
      }
    });

    it("includes Article schema with required fields", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      const article = schemas.find((s) => (s as Record<string, unknown>)["@type"] === "Article") as Record<string, unknown>;
      expect(article).toBeDefined();
      expectNonEmptyString(article.headline, "headline");
      expectNonEmptyString(article.description, "description");
      expectValidUrl(article.url, "url");
      expect(article.datePublished).toBeTruthy();
      expect(article.dateModified).toBeTruthy();

      const author = article.author as Record<string, unknown>;
      expect(author["@type"]).toBe("Organization");

      const publisher = article.publisher as Record<string, unknown>;
      expect(publisher["@type"]).toBe("Organization");
      const logo = publisher.logo as Record<string, unknown>;
      expect(logo["@type"]).toBe("ImageObject");
      expectValidUrl(logo.url, "publisher logo url");

      const about = article.about as Record<string, unknown>[];
      expect(about).toHaveLength(2);
      for (const entity of about) {
        expectNonEmptyString(entity["@type"], "entity @type");
        expectNonEmptyString(entity.name, "entity name");
      }
    });

    it("includes ItemList schema with entities", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      const itemList = schemas.find((s) => (s as Record<string, unknown>)["@type"] === "ItemList") as Record<string, unknown>;
      expect(itemList).toBeDefined();
      expect(itemList.numberOfItems).toBe(2);

      const elements = itemList.itemListElement as Record<string, unknown>[];
      expect(elements).toHaveLength(2);
      elements.forEach((el, i) => {
        expect(el["@type"]).toBe("ListItem");
        expect(el.position).toBe(i + 1);
        expectNonEmptyString(el.name, "entity name");
        expectValidUrl(el.url, "entity url");
      });
    });

    it("includes FAQPage schema when FAQs exist", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      const faq = schemas.find((s) => (s as Record<string, unknown>)["@type"] === "FAQPage");
      expect(faq).toBeDefined();
    });

    it("omits FAQPage schema when no FAQs", () => {
      const noFaqComparison = { ...sampleComparison, faqs: [] };
      const schemas = comparisonPageSchema(noFaqComparison);
      const faq = schemas.find((s) => (s as Record<string, unknown>)["@type"] === "FAQPage");
      expect(faq).toBeUndefined();
    });

    it("includes BreadcrumbList with category", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      const breadcrumb = schemas.find((s) => (s as Record<string, unknown>)["@type"] === "BreadcrumbList") as Record<string, unknown>;
      expect(breadcrumb).toBeDefined();

      const elements = breadcrumb.itemListElement as Record<string, unknown>[];
      // Home + category + comparison title = 3
      expect(elements).toHaveLength(3);
    });

    it("includes Dataset schema with citation sources", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      const dataset = schemas.find((s) => (s as Record<string, unknown>)["@type"] === "Dataset") as Record<string, unknown>;
      expect(dataset).toBeDefined();
      expectNonEmptyString(dataset.name, "dataset name");
      expect(dataset.description).toContain("5 sources");
      expect(Array.isArray(dataset.variableMeasured)).toBe(true);

      const basedOn = dataset.isBasedOn as Record<string, unknown>[];
      expect(basedOn.length).toBeGreaterThan(0);
      for (const source of basedOn) {
        expect(source["@type"]).toBe("CreativeWork");
        expectNonEmptyString(source.name, "source name");
        expectValidUrl(source.url, "source url");
      }
    });

    it("includes SpeakableSpecification", () => {
      const schemas = comparisonPageSchema(sampleComparison);
      const speakable = schemas.find(
        (s) => (s as Record<string, unknown>)["@type"] === "WebPage" && (s as Record<string, unknown>).speakable
      );
      expect(speakable).toBeDefined();
    });

    it("includes AggregateRating when vote data has >= 10 votes", () => {
      const schemas = comparisonPageSchema(sampleComparison, sampleVoteData);
      const ratings = schemas.filter(
        (s) => (s as Record<string, unknown>).aggregateRating
      );
      expect(ratings.length).toBeGreaterThan(0);

      for (const rating of ratings) {
        const r = rating as Record<string, unknown>;
        const agg = r.aggregateRating as Record<string, unknown>;
        expect(agg["@type"]).toBe("AggregateRating");
        expect(parseFloat(agg.ratingValue as string)).toBeGreaterThanOrEqual(1);
        expect(parseFloat(agg.ratingValue as string)).toBeLessThanOrEqual(5);
        expect(agg.bestRating).toBe(5);
        expect(agg.worstRating).toBe(1);
        expect(agg.ratingCount).toBeGreaterThan(0);
      }
    });

    it("omits AggregateRating when vote total < 10", () => {
      const lowVotes: ComparisonVoteData = { votes: { iPhone: 3 }, total: 3 };
      const schemas = comparisonPageSchema(sampleComparison, lowVotes);
      const ratings = schemas.filter(
        (s) => (s as Record<string, unknown>).aggregateRating
      );
      expect(ratings).toHaveLength(0);
    });
  });

  describe("categoryPageSchema", () => {
    it("produces valid CollectionPage + BreadcrumbList", () => {
      const schemas = categoryPageSchema(sampleCategory, "2025-06-01");
      expect(schemas).toHaveLength(2);

      const collection = schemas[0];
      validateSchemaBase(collection, "CollectionPage");
      expect(collection.name).toBe("Technology");
      expectValidUrl(collection.url, "url");
      expect(collection.dateModified).toBe("2025-06-01");

      const mainEntity = collection.mainEntity as Record<string, unknown>;
      expect(mainEntity["@type"]).toBe("ItemList");
      expect(mainEntity.numberOfItems).toBe(150);

      const items = mainEntity.itemListElement as Record<string, unknown>[];
      expect(items).toHaveLength(2);
      items.forEach((item, i) => {
        expect(item.position).toBe(i + 1);
        expectNonEmptyString(item.name, "comparison name");
        expectValidUrl(item.url, "comparison url");
      });

      const breadcrumb = schemas[1];
      validateSchemaBase(breadcrumb, "BreadcrumbList");
    });
  });

  describe("entityPageSchema", () => {
    it("produces valid entity schema with correct @type mapping", () => {
      const schema = entityPageSchema({
        name: "iPhone",
        slug: "iphone",
        shortDesc: "Apple's flagship",
        entityType: "product",
        imageUrl: "https://example.com/iphone.jpg",
        dateModified: "2025-06-01",
      });
      validateSchemaBase(schema, "Product");
      expect(schema.name).toBe("iPhone");
      expectValidUrl(schema.url, "url");
      expectValidUrl(schema.image as string, "image");
      expect(schema.dateModified).toBe("2025-06-01");
    });

    it("maps entity types to schema.org types correctly", () => {
      const typeMap: Record<string, string> = {
        person: "Person",
        country: "Country",
        product: "Product",
        team: "SportsTeam",
        company: "Organization",
        technology: "SoftwareApplication",
        brand: "Brand",
        software: "SoftwareApplication",
        place: "Place",
        event: "Event",
        war: "Event",
      };

      for (const [entityType, expectedSchemaType] of Object.entries(typeMap)) {
        const schema = entityPageSchema({
          name: "Test",
          slug: "test",
          shortDesc: "Test entity",
          entityType,
          imageUrl: null,
        });
        expectValidType(schema, expectedSchemaType);
      }
    });

    it("falls back to Thing for unknown entity types", () => {
      const schema = entityPageSchema({
        name: "Unknown",
        slug: "unknown",
        shortDesc: "Unknown type",
        entityType: "alien",
        imageUrl: null,
      });
      expectValidType(schema, "Thing");
    });

    it("omits image when null", () => {
      const schema = entityPageSchema({
        name: "Test",
        slug: "test",
        shortDesc: "Test",
        entityType: "product",
        imageUrl: null,
      });
      expect(schema).not.toHaveProperty("image");
    });
  });

  describe("aggregateRatingSchema", () => {
    it("produces valid AggregateRating schema", () => {
      const schema = aggregateRatingSchema({
        name: "iPhone",
        slug: "iphone",
        entityType: "product",
        ratingValue: 4.5,
        reviewCount: 200,
      });
      validateSchemaBase(schema, "Product");
      expect(schema.name).toBe("iPhone");
      expectValidUrl(schema.url, "url");

      const agg = schema.aggregateRating as Record<string, unknown>;
      expect(agg["@type"]).toBe("AggregateRating");
      expect(agg.ratingValue).toBe("4.5");
      expect(agg.bestRating).toBe(5);
      expect(agg.worstRating).toBe(1);
      expect(agg.reviewCount).toBe(200);
    });

    it("allows custom bestRating and worstRating", () => {
      const schema = aggregateRatingSchema({
        name: "Test",
        slug: "test",
        entityType: "product",
        ratingValue: 8.5,
        reviewCount: 50,
        bestRating: 10,
        worstRating: 0,
      });
      const agg = schema.aggregateRating as Record<string, unknown>;
      expect(agg.bestRating).toBe(10);
      expect(agg.worstRating).toBe(0);
    });
  });

  describe("newsArticleSchema", () => {
    it("produces valid NewsArticle schema", () => {
      const schema = newsArticleSchema({
        title: "Breaking: New Comparison",
        description: "A timely comparison article.",
        url: "https://www.aversusb.net/blog/breaking-comparison",
        datePublished: "2025-06-01",
        dateModified: "2025-06-02",
      });
      validateSchemaBase(schema, "NewsArticle");
      expect(schema.headline).toBe("Breaking: New Comparison");
      expectNonEmptyString(schema.description, "description");
      expectValidUrl(schema.url, "url");

      const author = schema.author as Record<string, unknown>;
      expect(author["@type"]).toBe("Organization");

      const publisher = schema.publisher as Record<string, unknown>;
      expect(publisher["@type"]).toBe("Organization");
      const logo = publisher.logo as Record<string, unknown>;
      expect(logo["@type"]).toBe("ImageObject");
    });
  });

  describe("blogArticleSchema", () => {
    it("uses NewsArticle type when timely", () => {
      const schema = blogArticleSchema({
        title: "Trending Topic",
        description: "A trending article.",
        url: "https://www.aversusb.net/blog/trending",
        isTimely: true,
      });
      expectValidType(schema, "NewsArticle");
    });

    it("uses Article type when not timely", () => {
      const schema = blogArticleSchema({
        title: "Evergreen Post",
        description: "An evergreen article.",
        url: "https://www.aversusb.net/blog/evergreen",
        isTimely: false,
      });
      expectValidType(schema, "Article");
    });

    it("omits dates when not provided", () => {
      const schema = blogArticleSchema({
        title: "No Dates",
        description: "Article without dates.",
        url: "https://www.aversusb.net/blog/no-dates",
        isTimely: false,
      });
      expect(schema).not.toHaveProperty("datePublished");
      expect(schema).not.toHaveProperty("dateModified");
    });
  });

  describe("cross-schema consistency", () => {
    it("all schemas use the same site URL base", () => {
      const org = organizationSchema();
      const website = webSiteSchema();
      const page = webPageSchema({
        title: "T",
        description: "D",
        url: `${org.url}/test`,
      });

      expect(org.url).toBe(website.url);
      expect((page.isPartOf as Record<string, unknown>).url).toBe(org.url);
    });

    it("all schemas use https://schema.org context", () => {
      const allSchemas = [
        organizationSchema(),
        webSiteSchema(),
        webPageSchema({ title: "T", description: "D", url: "https://test.com" }),
        faqSchema(sampleFaqs),
        breadcrumbSchema([{ name: "Home", url: "https://test.com" }]),
        entityPageSchema({ name: "T", slug: "t", shortDesc: "d", entityType: "product", imageUrl: null }),
        ...comparisonPageSchema(sampleComparison),
        ...categoryPageSchema(sampleCategory),
      ];

      for (const schema of allSchemas) {
        expect((schema as Record<string, unknown>)["@context"]).toBe("https://schema.org");
      }
    });
  });
});
