// ============================================================
// Core domain types
// ============================================================

export interface RelatedBlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string | null;
}

export interface CitationStats {
  sourceCount: number;
  dataPointCount: number;
  reviewsAnalyzed: number | null;
  preferencePercent: number | null;
  preferenceEntity: string | null;
  lastResearched: string;
  sources: { name: string; url?: string }[];
}

export interface QuickAnswerTLDR {
  tldr: string;
  winnerName: string | null;
  winnerReason: string | null;
  keyFact: string;
}

export interface ComparisonPageData {
  id: string;
  slug: string;
  title: string;
  shortAnswer: string | null;
  keyDifferences: KeyDifference[];
  verdict: string | null;
  category: string | null;
  entities: ComparisonEntityData[];
  attributes: ComparisonAttribute[];
  faqs: FAQData[];
  relatedComparisons: RelatedComparison[];
  relatedBlogPosts: RelatedBlogPost[];
  metadata: ComparisonMetadata;
  resources?: ComparisonResource[];
  citationStats?: CitationStats;
  quickAnswer?: QuickAnswerTLDR;
}

export interface ComparisonResource {
  type: "wikipedia" | "blog" | "external" | "affiliate" | "video";
  label: string;
  url: string;
  description?: string;
  partner?: string;
}

export interface AffiliateLink {
  url: string;
  partner: string;
  label: string;
}

export interface ComparisonEntityData {
  id: string;
  slug: string;
  name: string;
  shortDesc: string | null;
  imageUrl: string | null;
  entityType: string;
  position: number;
  pros: string[];
  cons: string[];
  bestFor: string | null;
  affiliateLinks?: AffiliateLink[];
}

export interface ComparisonAttribute {
  id: string;
  slug: string;
  name: string;
  unit: string | null;
  category: string | null;
  dataType: string;
  higherIsBetter: boolean | null;
  values: {
    entityId: string;
    valueText: string | null;
    valueNumber: number | null;
    valueBoolean: boolean | null;
    winner?: boolean;
  }[];
}

export interface KeyDifference {
  label: string;
  entityAValue: string;
  entityBValue: string;
  winner?: "a" | "b" | "tie";
}

export interface FAQData {
  question: string;
  answer: string;
}

export interface RelatedComparison {
  slug: string;
  title: string;
  category: string | null;
}

export interface ComparisonMetadata {
  metaTitle: string;
  metaDescription: string;
  publishedAt: string | null;
  updatedAt: string;
  isAutoGenerated: boolean;
  isHumanReviewed: boolean;
  viewCount: number;
}

// ============================================================
// Search & Discovery
// ============================================================

export interface SearchResult {
  type: "comparison" | "entity" | "category";
  slug: string;
  title: string;
  subtitle?: string;
  imageUrl?: string;
  category?: string;
}

export interface TrendingComparison {
  slug: string;
  title: string;
  category: string;
  viewCount: number;
  entityImages: string[];
  updatedAt?: string | null;
}

export interface CategoryData {
  slug: string;
  name: string;
  description: string | null;
  icon: string | null;
  comparisonCount: number;
  topComparisons: RelatedComparison[];
  subcategories: { slug: string; name: string; count: number }[];
}

// ============================================================
// DataForSEO types
// ============================================================

export interface KeywordData {
  keyword: string;
  searchVolume: number | null;
  cpc: number | null;
  competition: number | null;
  difficulty: number | null;
  intent: string | null;
  entityA: string | null;
  entityB: string | null;
  queryPattern: string | null;
}

export interface KeywordOpportunityData {
  id: string;
  keyword: string;
  searchVolume: number | null;
  opportunityScore: number | null;
  status: string;
  category: string | null;
  hasExistingPage: boolean;
}

// ============================================================
// Schema / Structured Data
// ============================================================

export interface SchemaConfig {
  type: string;
  data: Record<string, unknown>;
}

// ============================================================
// Admin types
// ============================================================

export interface DashboardStats {
  totalEntities: number;
  totalComparisons: number;
  publishedComparisons: number;
  totalKeywords: number;
  pendingBriefs: number;
  totalViews: number;
}

export interface JobStatus {
  id: string;
  jobType: string;
  status: string;
  startedAt: string | null;
  completedAt: string | null;
  error: string | null;
}
