/**
 * Compare template SEO:
 *  - noindex entity pages are not linked from the hero, Explore More, or JSON-LD
 *  - a dropped /entity URL does not leave an empty ProfilePage mainEntityOfPage
 *  - indexable entity pages keep those links
 *  - an editorial compare emits exactly one ClaimReview
 *  - a compare page emits exactly one FAQPage
 */
import { beforeAll, describe, expect, it } from "vitest";
import { render } from "@testing-library/react";
import type { ComparisonPageData, ComparisonEntityData } from "@/types";
import { ComparisonHero } from "@/components/comparison/ComparisonHero";
import { InternalLinks } from "@/components/comparison/InternalLinks";
import { IPHONE_16E_VS_IPHONE_17E } from "@/lib/data/editorial-compares/iphone-16e-vs-iphone-17e";
import { assembleCompareJsonLd, stripNoindexEntityPageUrls } from "@/lib/seo/compare-jsonld";
import { entityPageRobotsStatus, isEntityPageIndexable } from "@/lib/seo/entity-page-indexable";

beforeAll(() => {
  const view = window as Window & {
    matchMedia: typeof window.matchMedia;
    IntersectionObserver: typeof IntersectionObserver;
  };
  if (!view.matchMedia) {
    view.matchMedia = ((query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: () => {},
      removeListener: () => {},
      addEventListener: () => {},
      removeEventListener: () => {},
      dispatchEvent: () => false,
    })) as unknown as typeof window.matchMedia;
  }
  if (!view.IntersectionObserver) {
    class Observer {
      observe() {}
      unobserve() {}
      disconnect() {}
    }
    view.IntersectionObserver = Observer as unknown as typeof IntersectionObserver;
  }
});

function entity(slug: string, name: string, status: string): ComparisonEntityData {
  return {
    id: slug,
    slug,
    name,
    shortDesc: `${name} short description`,
    imageUrl: null,
    entityType: "product",
    position: 0,
    pros: ["Light"],
    cons: ["Slow"],
    bestFor: "Everyday use",
    status,
  };
}

function comparison(status: string): ComparisonPageData {
  return {
    id: "cmp-widgets",
    slug: "alpha-widget-vs-beta-widget",
    title: "Alpha Widget vs Beta Widget",
    shortAnswer: "Alpha Widget is the better pick for most people.",
    verdict: "Alpha Widget",
    keyDifferences: [],
    category: "products",
    entities: [
      entity("alpha-widget", "Alpha Widget", status),
      { ...entity("beta-widget", "Beta Widget", status), position: 1 },
    ],
    attributes: [],
    faqs: [{ question: "Which widget?", answer: "Alpha Widget for most people." }],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "Alpha Widget vs Beta Widget",
      metaDescription: "Compare the two widgets.",
      publishedAt: "2026-09-21T00:00:00.000Z",
      updatedAt: "2026-09-21T00:00:00.000Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 0,
      status: "published",
    },
  };
}

function collectTypes(node: unknown, types: string[] = []): string[] {
  if (Array.isArray(node)) {
    for (const item of node) collectTypes(item, types);
    return types;
  }
  if (!node || typeof node !== "object") return types;
  const record = node as Record<string, unknown>;
  const type = record["@type"];
  if (typeof type === "string") types.push(type);
  else if (Array.isArray(type)) {
    for (const item of type) if (typeof item === "string") types.push(item);
  }
  for (const child of Object.values(record)) collectTypes(child, types);
  return types;
}

function collectNodes(
  node: unknown,
  match: (record: Record<string, unknown>) => boolean,
  found: Record<string, unknown>[] = [],
): Record<string, unknown>[] {
  if (Array.isArray(node)) {
    for (const item of node) collectNodes(item, match, found);
    return found;
  }
  if (!node || typeof node !== "object") return found;
  const record = node as Record<string, unknown>;
  if (match(record)) found.push(record);
  for (const child of Object.values(record)) collectNodes(child, match, found);
  return found;
}

function faqPages(documents: unknown[]): Record<string, unknown>[] {
  return documents.flatMap((doc) =>
    collectNodes(doc, (record) => {
      const type = record["@type"];
      return type === "FAQPage" || (Array.isArray(type) && type.includes("FAQPage"));
    }),
  );
}

function questionNames(faq: Record<string, unknown>): string[] {
  const main = faq.mainEntity;
  const questions = Array.isArray(main) ? main : main ? [main] : [];
  return questions.map((question) => {
    const record = question as Record<string, unknown>;
    return typeof record.name === "string" ? record.name : "";
  });
}

function renderCompareSurface(page: ComparisonPageData) {
  const assembled = assembleCompareJsonLd({
    comparison: page,
    voteData: null,
    videoNode: null,
    fallbackDescription: page.shortAnswer || page.title,
  });
  const view = render(
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(assembled.document) }}
      />
      {assembled.claimReview && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(assembled.claimReview) }}
        />
      )}
      {page.entities.length === 2 && <ComparisonHero comparison={page} />}
      <InternalLinks
        currentSlug={page.slug}
        category={page.category}
        entities={page.entities.map((item) => ({
          name: item.name,
          slug: item.slug,
          status: item.status,
        }))}
        relatedComparisons={page.relatedComparisons}
      />
    </>,
  );

  const scripts = [...view.container.querySelectorAll('script[type="application/ld+json"]')];
  const documents = scripts.map((script) => JSON.parse(script.textContent || "null"));
  const types = documents.flatMap((doc) => collectTypes(doc));
  return { ...view, html: view.container.innerHTML, documents, types };
}

describe("entity page indexability predicate", () => {
  it("matches the entity page: published is indexable, a missing row is draft", () => {
    expect(isEntityPageIndexable("published")).toBe(true);
    expect(isEntityPageIndexable(entityPageRobotsStatus({ lookupFailed: false, status: null }))).toBe(false);
    expect(isEntityPageIndexable(entityPageRobotsStatus({ lookupFailed: false, status: "draft" }))).toBe(false);
    expect(isEntityPageIndexable(entityPageRobotsStatus({ lookupFailed: false, status: "archived" }))).toBe(false);
    expect(isEntityPageIndexable(entityPageRobotsStatus({ lookupFailed: true, status: null }))).toBe(true);
  });
});

describe("compare template entity links", () => {
  it("omits /entity links in the rendered HTML and JSON-LD when the entity page is noindex", () => {
    const { html, types, container } = renderCompareSurface(comparison("draft"));

    expect(html).not.toMatch(/\/entity\//);
    expect(container.textContent).toContain("Alpha Widget");
    expect(container.textContent).toContain("Beta Widget");
    expect(types).toContain("FAQPage");
    expect(types).toContain("BreadcrumbList");
    expect(types).toContain("Product");
    expect(types.filter((type) => type === "ClaimReview")).toHaveLength(1);
  });

  it("keeps the indexable entity link and drops only the noindex sibling", () => {
    const page = comparison("published");
    page.entities = [
      entity("alpha-widget", "Alpha Widget", "published"),
      { ...entity("beta-widget", "Beta Widget", "draft"), position: 1 },
    ];
    const { html, documents } = renderCompareSurface(page);
    const json = JSON.stringify(documents);

    expect(html).toContain('href="/entity/alpha-widget"');
    expect(html).not.toContain("/entity/beta-widget");
    expect(json).toContain("/entity/alpha-widget");
    expect(json).not.toContain("/entity/beta-widget");
    expect(html).toContain("Beta Widget");
  });

  it("keeps /entity links when the entity page is indexable", () => {
    const { html, documents } = renderCompareSurface(comparison("published"));
    const json = JSON.stringify(documents);

    expect(html).toContain('href="/entity/alpha-widget"');
    expect(html).toContain('href="/entity/beta-widget"');
    expect(json).toContain("/entity/alpha-widget");
    expect(json).toContain("/entity/beta-widget");
  });

  it("does not treat a Wikidata /entity/ URL as an AversusB entity page", () => {
    const stripped = stripNoindexEntityPageUrls(
      {
        sameAs: [
          "https://www.wikidata.org/entity/Q312",
          "https://www.aversusb.net/entity/alpha-widget",
        ],
        name: "Alpha Widget",
      },
      [entity("alpha-widget", "Alpha Widget", "draft")],
    );
    expect(stripped).toEqual({
      sameAs: ["https://www.wikidata.org/entity/Q312"],
      name: "Alpha Widget",
    });
  });

  it("removes mainEntityOfPage when the noindex /entity URL is the only content left", () => {
    const stripped = stripNoindexEntityPageUrls(
      {
        "@type": "Product",
        name: "Alpha Widget",
        url: "https://www.aversusb.net/entity/alpha-widget",
        mainEntityOfPage: {
          "@type": "ProfilePage",
          "@id": "https://www.aversusb.net/entity/alpha-widget#profilepage",
          url: "https://www.aversusb.net/entity/alpha-widget",
        },
        subjectOf: {
          "@type": "Article",
          mainEntityOfPage: {
            "@type": "WebPage",
            "@id": "https://www.aversusb.net/compare/alpha-widget-vs-beta-widget",
          },
        },
      },
      [entity("alpha-widget", "Alpha Widget", "draft")],
    );

    expect(stripped).toEqual({
      "@type": "Product",
      name: "Alpha Widget",
      subjectOf: {
        "@type": "Article",
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "https://www.aversusb.net/compare/alpha-widget-vs-beta-widget",
        },
      },
    });
    expect(JSON.stringify(stripped)).not.toContain('{"@type":"ProfilePage"}');
  });

  it("drops empty ProfilePage mainEntityOfPage objects from a noindex compare", () => {
    const { documents } = renderCompareSurface(comparison("draft"));
    const pages = documents.flatMap((doc) =>
      collectNodes(doc, (record) => "mainEntityOfPage" in record).map(
        (record) => record.mainEntityOfPage as Record<string, unknown>,
      ),
    );

    expect(pages.length).toBeGreaterThan(0);
    expect(pages.every((page) => page["@type"] !== "ProfilePage")).toBe(true);
    expect(pages.some((page) => page["@type"] === "WebPage")).toBe(true);
    expect(JSON.stringify(documents)).not.toContain('{"@type":"ProfilePage"}');
  });

  it("keeps ProfilePage mainEntityOfPage when the entity page is indexable", () => {
    const { documents } = renderCompareSurface(comparison("published"));
    const pages = documents.flatMap((doc) =>
      collectNodes(doc, (record) => "mainEntityOfPage" in record).map(
        (record) => record.mainEntityOfPage as Record<string, unknown>,
      ),
    );
    const json = JSON.stringify(pages);

    expect(pages.some((page) => page["@type"] === "ProfilePage")).toBe(true);
    expect(json).toContain("/entity/alpha-widget");
    expect(json).toContain("/entity/beta-widget");
  });
});

describe("editorial compare ClaimReview", () => {
  it("renders exactly one ClaimReview and keeps the other schema types", () => {
    const { types, documents } = renderCompareSurface(IPHONE_16E_VS_IPHONE_17E);
    const reviews = documents.flatMap((doc) => {
      const found: Record<string, unknown>[] = [];
      const walk = (node: unknown) => {
        if (Array.isArray(node)) {
          node.forEach(walk);
          return;
        }
        if (!node || typeof node !== "object") return;
        const record = node as Record<string, unknown>;
        if (record["@type"] === "ClaimReview") {
          found.push(record);
          return;
        }
        Object.values(record).forEach(walk);
      };
      walk(doc);
      return found;
    });

    expect(reviews).toHaveLength(1);
    expect(types.filter((type) => type === "ClaimReview")).toHaveLength(1);
    // The @graph node is the complete one (publisher + #claimreview).
    // The standalone script used #claim-review and had no publisher.
    expect(reviews[0]["@id"]).toMatch(/#claimreview$/);
    expect(reviews[0].publisher).toBeTruthy();
    expect(types).toContain("FAQPage");
    expect(types).toContain("BreadcrumbList");
    expect(types).toContain("Product");
    expect(types.filter((type) => type === "FAQPage")).toHaveLength(1);
  });
});

describe("compare FAQPage", () => {
  it("emits one FAQPage on an ordinary compare such as marvel-vs-dc", () => {
    const page = comparison("published");
    const { documents } = renderCompareSurface(page);
    const faqs = faqPages(documents);

    expect(faqs).toHaveLength(1);
    expect(faqs[0]["@id"]).toBe(
      "https://www.aversusb.net/compare/alpha-widget-vs-beta-widget#faq",
    );
    expect(questionNames(faqs[0])).toEqual(page.faqs.map((faq) => faq.question));
  });

  it("emits one FAQPage on an editorial compare and keeps each question once", () => {
    const page = IPHONE_16E_VS_IPHONE_17E;
    const { documents } = renderCompareSurface(page);
    const faqs = faqPages(documents);
    const names = questionNames(faqs[0]);

    expect(faqs).toHaveLength(1);
    expect(names).toEqual(page.faqs.map((faq) => faq.question));
    expect(new Set(names.map((name) => name.trim().toLowerCase())).size).toBe(names.length);
  });

  it("merges questions from two FAQPage nodes and keeps the first answer", () => {
    const page = comparison("published");
    const url = "https://www.aversusb.net/compare/alpha-widget-vs-beta-widget";
    page.schemaMarkup = {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "FAQPage",
          "@id": `${url}#faq`,
          mainEntity: [
            {
              "@type": "Question",
              name: "Which widget?",
              acceptedAnswer: { "@type": "Answer", text: "Alpha." },
            },
            {
              "@type": "Question",
              name: "Where is it made?",
              acceptedAnswer: { "@type": "Answer", text: "Ohio." },
            },
          ],
        },
        {
          "@type": "FAQPage",
          "@id": `${url}#faq`,
          mainEntity: [
            {
              "@type": "Question",
              name: "Which widget?",
              acceptedAnswer: { "@type": "Answer", text: "Duplicate." },
            },
            {
              "@type": "Question",
              name: "Does it fold?",
              acceptedAnswer: { "@type": "Answer", text: "No." },
            },
          ],
        },
      ],
    };

    const { documents, types } = renderCompareSurface(page);
    const faqs = faqPages(documents);
    const questions = (faqs[0].mainEntity as Record<string, unknown>[]) ?? [];

    expect(faqs).toHaveLength(1);
    expect(types.filter((type) => type === "FAQPage")).toHaveLength(1);
    expect(questionNames(faqs[0])).toEqual([
      "Which widget?",
      "Where is it made?",
      "Does it fold?",
    ]);
    expect((questions[0].acceptedAnswer as Record<string, unknown>).text).toBe("Alpha.");
    expect(JSON.stringify(documents).match(/"@type":"FAQPage"/g)).toHaveLength(1);
  });
});
