/**
 * JSON-LD @id edges must point at a node in the same page graph.
 * A compare with no FAQs emits neither an FAQPage nor a #faq link.
 */
import { beforeAll, describe, expect, it, vi } from "vitest";
import { render } from "@testing-library/react";

vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: () => {}, replace: () => {}, prefetch: () => {} }),
  useSearchParams: () => new URLSearchParams(),
  usePathname: () => "/category/products/ereaders",
  notFound: () => {
    throw new Error("NEXT_NOT_FOUND");
  },
}));
import type { ComparisonPageData, ComparisonEntityData } from "@/types";
import { assembleCompareJsonLd } from "@/lib/seo/compare-jsonld";
import { BRAVE_VS_CHROME } from "@/lib/data/editorial-compares/brave-vs-chrome";
import { HUB_CONFIG } from "@/lib/data/hubs";
import { hubSchemas } from "@/lib/seo/hub-schemas";
import { SITE_URL } from "@/lib/utils/constants";
import BlogPostPage from "@/app/blog/[slug]/page";
import SubcategoryPage from "@/app/category/[slug]/[subcategory]/page";

beforeAll(() => {
  const view = window as Window & {
    matchMedia: typeof window.matchMedia;
    IntersectionObserver: typeof IntersectionObserver;
  };
  if (!view.matchMedia) {
    view.matchMedia = ((query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: () => {},
      removeListener: () => {},
      addEventListener: () => {},
      removeEventListener: () => {},
      dispatchEvent: () => false,
    })) as unknown as typeof window.matchMedia;
  }
  if (!view.IntersectionObserver) {
    class Observer {
      observe() {}
      unobserve() {}
      disconnect() {}
    }
    view.IntersectionObserver = Observer as unknown as typeof IntersectionObserver;
  }
});

function entity(slug: string, name: string): ComparisonEntityData {
  return {
    id: slug,
    slug,
    name,
    shortDesc: `${name} short description`,
    imageUrl: null,
    entityType: "product",
    position: 0,
    pros: ["Light"],
    cons: ["Slow"],
    bestFor: "Everyday use",
    status: "published",
  };
}

function zeroFaqCompare(): ComparisonPageData {
  return {
    id: "cmp-widgets",
    slug: "alpha-widget-vs-beta-widget",
    title: "Alpha Widget vs Beta Widget",
    shortAnswer: "Alpha Widget is the better pick for most people.",
    verdict: "Alpha Widget",
    keyDifferences: [],
    category: "products",
    entities: [entity("alpha-widget", "Alpha Widget"), { ...entity("beta-widget", "Beta Widget"), position: 1 }],
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "Alpha Widget vs Beta Widget",
      metaDescription: "Compare the two widgets.",
      publishedAt: "2026-09-21T00:00:00.000Z",
      updatedAt: "2026-09-21T00:00:00.000Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 0,
      status: "published",
    },
  };
}

function walk(node: unknown, visit: (obj: Record<string, unknown>) => void) {
  if (Array.isArray(node)) {
    for (const item of node) walk(item, visit);
    return;
  }
  if (!node || typeof node !== "object") return;
  const record = node as Record<string, unknown>;
  visit(record);
  for (const child of Object.values(record)) walk(child, visit);
}

/** An object whose only key is `@id` is a reference, not a node. */
function idOnlyRefs(documents: unknown[]): string[] {
  const refs: string[] = [];
  for (const doc of documents) {
    walk(doc, (obj) => {
      const keys = Object.keys(obj);
      if (keys.length === 1 && keys[0] === "@id" && typeof obj["@id"] === "string") {
        refs.push(obj["@id"]);
      }
    });
  }
  return refs;
}

/** A node defines an `@id` when that id sits next to at least one other property. */
function definedIds(documents: unknown[]): Set<string> {
  const ids = new Set<string>();
  for (const doc of documents) {
    walk(doc, (obj) => {
      if (typeof obj["@id"] === "string" && Object.keys(obj).length > 1) ids.add(obj["@id"]);
    });
  }
  return ids;
}

function assertIdsResolve(documents: unknown[]) {
  const ids = definedIds(documents);
  const dangling = idOnlyRefs(documents).filter((ref) => !ids.has(ref));
  expect(dangling).toEqual([]);
}

function collectTypes(documents: unknown[]): string[] {
  const types: string[] = [];
  for (const doc of documents) {
    walk(doc, (obj) => {
      const type = obj["@type"];
      if (typeof type === "string") types.push(type);
      else if (Array.isArray(type)) {
        for (const item of type) if (typeof item === "string") types.push(item);
      }
    });
  }
  return types;
}

function collectIds(documents: unknown[]): string[] {
  const ids: string[] = [];
  for (const doc of documents) {
    walk(doc, (obj) => {
      if (typeof obj["@id"] === "string") ids.push(obj["@id"]);
    });
  }
  return ids;
}

function assertNoFaq(documents: unknown[]) {
  expect(collectTypes(documents).filter((type) => type === "FAQPage")).toEqual([]);
  expect(collectIds(documents).filter((id) => id.endsWith("#faq"))).toEqual([]);
}

function jsonLdFrom(container: HTMLElement): unknown[] {
  return [...container.querySelectorAll('script[type="application/ld+json"]')].map((script) =>
    JSON.parse(script.textContent || "null"),
  );
}

function assembled(page: ComparisonPageData) {
  return assembleCompareJsonLd({
    comparison: page,
    voteData: null,
    videoNode: null,
    fallbackDescription: page.shortAnswer || page.title,
  }).document;
}

describe("compare pages with no FAQs", () => {
  it("emits no FAQPage and no #faq link", () => {
    const page = zeroFaqCompare();
    const document = assembled(page);
    assertNoFaq([document]);
    assertIdsResolve([document]);
  });

  it("drops a stored FAQPage and a dangling #faq link", () => {
    const page = zeroFaqCompare();
    const url = `${SITE_URL}/compare/${page.slug}`;
    page.schemaMarkup = {
      "@context": "https://schema.org",
      "@type": "Article",
      "@id": `${url}#article`,
      headline: page.title,
      hasPart: { "@id": `${url}#faq` },
      mainEntity: {
        "@type": "FAQPage",
        "@id": `${url}#faq`,
        mainEntity: [
          {
            "@type": "Question",
            name: "Which widget?",
            acceptedAnswer: { "@type": "Answer", text: "Alpha." },
          },
        ],
      },
    };
    const document = assembled(page);
    assertNoFaq([document]);
    expect(JSON.stringify(document)).not.toContain("Which widget?");
  });
});

describe("@id-only references resolve inside the page graph", () => {
  it("resolves them on a compare page", () => {
    expect(BRAVE_VS_CHROME.faqs.length).toBeGreaterThan(0);
    const document = assembled(BRAVE_VS_CHROME);
    const ids = collectIds([document]);
    expect(ids.some((id) => id.endsWith("#faq"))).toBe(true);
    expect(collectTypes([document]).filter((type) => type === "FAQPage")).toHaveLength(1);
    assertIdsResolve([document]);
  });

  it("resolves them on a blog post", async () => {
    const ui = await BlogPostPage({
      params: Promise.resolve({ slug: "best-smartphones-2026-ultimate-comparison" }),
    });
    const view = render(ui);
    const documents = jsonLdFrom(view.container);
    expect(documents.length).toBeGreaterThan(0);
    assertIdsResolve(documents);
  });

  it("resolves them on a hub, and the FAQPage owns #faq", () => {
    const hub = HUB_CONFIG.vpn;
    expect(hub.faqs.length).toBeGreaterThan(0);
    const documents = hubSchemas(hub, []);
    const faqId = `${SITE_URL}/hub/${hub.slug}#faq`;
    expect(collectIds(documents).filter((id) => id === faqId).length).toBeGreaterThan(0);
    expect(collectTypes(documents).filter((type) => type === "FAQPage")).toHaveLength(1);
    assertIdsResolve(documents);

    const empty = hubSchemas({ ...hub, faqs: [] }, []);
    assertNoFaq(empty);
    assertIdsResolve(empty);
  });

  it("resolves them on a subcategory with no FAQs, and does not link #faq", async () => {
    const ui = await SubcategoryPage({
      params: Promise.resolve({ slug: "products", subcategory: "ereaders" }),
      searchParams: Promise.resolve({}),
    });
    const view = render(ui);
    const documents = jsonLdFrom(view.container);
    expect(documents.length).toBeGreaterThan(0);
    assertNoFaq(documents);
    assertIdsResolve(documents);
  });
});
