/**
 * Tests for src/lib/seo/schema.ts — JSON-LD emission, with focus on the
 * schema-3way v1 contract (DAN-841 rev 1a540eda, sign-off DAN-844) for N>=3
 * entity comparisons (DAN-854 Phase 1.1).
 */
import { describe, it, expect } from "vitest";
import { comparisonPageSchema, type ComparisonVoteData } from "../schema";
import { SITE_URL, SITE_NAME } from "@/lib/utils/constants";
import type { ComparisonPageData, ComparisonEntityData } from "@/types";

function entity(
  i: number,
  name: string,
  slug: string,
  overrides: Partial<ComparisonEntityData> = {},
): ComparisonEntityData {
  return {
    id: `e${i}`,
    slug,
    name,
    shortDesc: `${name} short desc`,
    imageUrl: `https://img.example/${slug}.png`,
    entityType: "software",
    position: i,
    pros: [],
    cons: [],
    bestFor: null,
    ...overrides,
  };
}

function baseComparison(
  slug: string,
  title: string,
  entities: ComparisonEntityData[],
): ComparisonPageData {
  return {
    id: "cmp1",
    slug,
    title,
    shortAnswer: `${title} — short answer`,
    keyDifferences: [],
    verdict: null,
    category: "technology",
    entities,
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: title,
      metaDescription: `Compare ${title}`,
      publishedAt: "2026-06-08T00:00:00.000Z",
      updatedAt: "2026-06-08T00:00:00.000Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 0,
    },
  };
}

describe("comparisonPageSchema — 3-way v1 contract (DAN-854)", () => {
  const slug = "chatgpt-vs-claude-vs-gemini";
  const pageUrl = `${SITE_URL}/compare/${slug}`;

  const cmp = baseComparison(
    slug,
    "ChatGPT vs Claude vs Gemini",
    [
      entity(0, "ChatGPT", "chatgpt"),
      entity(1, "Claude", "claude"),
      entity(2, "Gemini", "gemini"),
    ],
  );

  it("returns a single @graph document for N>=3 entities", () => {
    const schemas = comparisonPageSchema(cmp);
    expect(schemas).toHaveLength(1);
    const doc = schemas[0] as Record<string, unknown>;
    expect(doc["@context"]).toBe("https://schema.org");
    expect(Array.isArray(doc["@graph"])).toBe(true);
  });

  it("emits a 5-node @graph (Article + ItemList + 3 items + BreadcrumbList) when no FAQs", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<{ "@type": string }> };
    const types = doc["@graph"].map((n) => n["@type"]);
    expect(types).toEqual([
      "Article",
      "ItemList",
      "SoftwareApplication",
      "SoftwareApplication",
      "SoftwareApplication",
      "BreadcrumbList",
    ]);
  });

  it("emits a 6-node @graph including FAQPage when faqs are present", () => {
    const withFaqs: ComparisonPageData = {
      ...cmp,
      faqs: [{ question: "Q?", answer: "A." }],
    };
    const doc = comparisonPageSchema(withFaqs)[0] as { "@graph": Array<{ "@type": string }> };
    const types = doc["@graph"].map((n) => n["@type"]);
    expect(types).toContain("FAQPage");
    expect(types).toHaveLength(7);
  });

  it("Article.mainEntity references the ItemList @id (#comparison)", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const article = doc["@graph"].find((n) => n["@type"] === "Article")!;
    expect(article.mainEntity).toEqual({ "@id": `${pageUrl}#comparison` });
  });

  it("ItemList carries numberOfItems and itemListOrder=Unordered and @id-references the item nodes", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const list = doc["@graph"].find((n) => n["@type"] === "ItemList")! as {
      "@id": string;
      numberOfItems: number;
      itemListOrder: string;
      itemListElement: Array<{ "@type": string; position: number; item: { "@id": string } }>;
    };
    expect(list["@id"]).toBe(`${pageUrl}#comparison`);
    expect(list.numberOfItems).toBe(3);
    expect(list.itemListOrder).toBe("https://schema.org/ItemListUnordered");
    expect(list.itemListElement.map((e) => e.position)).toEqual([1, 2, 3]);
    expect(list.itemListElement.map((e) => e.item["@id"])).toEqual([
      `${pageUrl}#item-a`,
      `${pageUrl}#item-b`,
      `${pageUrl}#item-c`,
    ]);
  });

  it("each SoftwareApplication item node carries the AI-chatbots cluster baseline", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const items = doc["@graph"].filter((n) => n["@type"] === "SoftwareApplication");
    expect(items).toHaveLength(3);
    for (const [i, item] of items.entries()) {
      expect(item["@id"]).toBe(`${pageUrl}#item-${String.fromCharCode(97 + i)}`);
      expect(item.applicationCategory).toBe("BusinessApplication");
      expect(item.operatingSystem).toBe("Web, iOS, Android");
      expect(item.publisher).toMatchObject({ "@type": "Organization" });
      expect(item.url).toMatch(new RegExp(`^${SITE_URL}/entity/`));
      expect(item.image).toMatch(/^https:\/\//);
    }
  });

  it("top-level item nodes emit regardless of vote count (§6 vote-gate fix)", () => {
    const noVotes = comparisonPageSchema(cmp, null);
    const withZeroVotes = comparisonPageSchema(cmp, { votes: {}, total: 0 });
    for (const result of [noVotes, withZeroVotes]) {
      const items = (result[0] as { "@graph": Array<Record<string, unknown>> })["@graph"].filter(
        (n) => n["@type"] === "SoftwareApplication",
      );
      expect(items).toHaveLength(3);
      // aggregateRating field must NOT be populated when there are no real votes
      for (const item of items) {
        expect(item.aggregateRating).toBeUndefined();
      }
    }
  });

  it("aggregateRating field populates only when votes >= 10 and entity has votes (real-data-only)", () => {
    const votes: ComparisonVoteData = {
      votes: { ChatGPT: 7, Claude: 5, Gemini: 0 },
      total: 12,
    };
    const doc = comparisonPageSchema(cmp, votes)[0] as { "@graph": Array<Record<string, unknown>> };
    const items = doc["@graph"].filter((n) => n["@type"] === "SoftwareApplication");
    const byName: Record<string, Record<string, unknown>> = Object.fromEntries(
      items.map((i) => [i.name as string, i]),
    );
    expect(byName.ChatGPT.aggregateRating).toBeDefined();
    expect(byName.Claude.aggregateRating).toBeDefined();
    // Gemini has 0 votes — no fabricated rating field
    expect(byName.Gemini.aggregateRating).toBeUndefined();
  });

  it("does NOT emit Offer for the AI-chatbots cluster", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    for (const node of doc["@graph"]) {
      expect(node.offers).toBeUndefined();
      expect(node["@type"]).not.toBe("Offer");
    }
  });

  it("Article.publisher is the site Organization (separate from item publisher)", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const article = doc["@graph"].find((n) => n["@type"] === "Article")! as {
      publisher: { name: string; url: string };
    };
    expect(article.publisher.name).toBe(SITE_NAME);
    expect(article.publisher.url).toBe(SITE_URL);
  });
});

describe("comparisonPageSchema — 2-way regression (unchanged shape)", () => {
  const cmp = baseComparison("iphone-vs-galaxy", "iPhone vs Galaxy", [
    entity(0, "iPhone 15", "iphone-15", { entityType: "product" }),
    entity(1, "Galaxy S24", "galaxy-s24", { entityType: "product" }),
  ]);

  it("returns an array of separate schemas (not a single @graph document) for N=2", () => {
    const schemas = comparisonPageSchema(cmp);
    expect(schemas.length).toBeGreaterThan(1);
    // No schema in the 2-way array should be a @graph container — each carries its own @context + @type
    for (const s of schemas as Record<string, unknown>[]) {
      expect(s["@graph"]).toBeUndefined();
      expect(s["@context"]).toBe("https://schema.org");
    }
  });

  it("Article.about[] still nests the entities (legacy shape preserved)", () => {
    const schemas = comparisonPageSchema(cmp);
    const article = (schemas as Array<Record<string, unknown>>).find(
      (s) => s["@type"] === "Article",
    )! as { about: Array<{ name: string }>; mainEntity?: unknown };
    expect(article.about).toHaveLength(2);
    expect(article.about.map((a) => a.name)).toEqual(["iPhone 15", "Galaxy S24"]);
    // Legacy 2-way shape does not carry mainEntity → #comparison (that's a 3-way addition)
    expect(article.mainEntity).toBeUndefined();
  });
});
