/**
 * Tests for src/lib/seo/schema.ts — JSON-LD emission, with focus on the
 * schema-3way v1 contract (DAN-841 rev 1a540eda, sign-off DAN-844) for N>=3
 * entity comparisons (DAN-854 Phase 1.1).
 *
 * Contract evolution since sign-off (DAN-1654 test reconciliation):
 *  - DAN-1479 (HB118-120): item node @id switched from `{url}#item-x` to the
 *    canonical `/entity/{slug}` URL so item nodes merge with the entity
 *    ProfilePage node across the knowledge graph.
 *  - HB178: a standalone ClaimReview node now emits in the @graph for
 *    schema.org fact-check parity with the 2-entity schema.
 */
import { describe, it, expect } from "vitest";
import { comparisonPageSchema, type ComparisonVoteData } from "../schema";
import { SITE_URL, SITE_NAME } from "@/lib/utils/constants";
import type { ComparisonPageData, ComparisonEntityData } from "@/types";

function entity(
  i: number,
  name: string,
  slug: string,
  overrides: Partial<ComparisonEntityData> = {},
): ComparisonEntityData {
  return {
    id: `e${i}`,
    slug,
    name,
    shortDesc: `${name} short desc`,
    imageUrl: `https://img.example/${slug}.png`,
    entityType: "software",
    position: i,
    pros: [],
    cons: [],
    bestFor: null,
    ...overrides,
  };
}

function baseComparison(
  slug: string,
  title: string,
  entities: ComparisonEntityData[],
): ComparisonPageData {
  return {
    id: "cmp1",
    slug,
    title,
    shortAnswer: `${title} — short answer`,
    keyDifferences: [],
    verdict: null,
    category: "technology",
    entities,
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: title,
      metaDescription: `Compare ${title}`,
      publishedAt: "2026-06-08T00:00:00.000Z",
      updatedAt: "2026-06-08T00:00:00.000Z",
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 0,
    },
  };
}

describe("comparisonPageSchema — 3-way v1 contract (DAN-854)", () => {
  const slug = "chatgpt-vs-claude-vs-gemini";
  const pageUrl = `${SITE_URL}/compare/${slug}`;

  const cmp = baseComparison(
    slug,
    "ChatGPT vs Claude vs Gemini",
    [
      entity(0, "ChatGPT", "chatgpt"),
      entity(1, "Claude", "claude"),
      entity(2, "Gemini", "gemini"),
    ],
  );

  it("returns a single @graph document for N>=3 entities", () => {
    const schemas = comparisonPageSchema(cmp);
    expect(schemas).toHaveLength(1);
    const doc = schemas[0] as Record<string, unknown>;
    expect(doc["@context"]).toBe("https://schema.org");
    expect(Array.isArray(doc["@graph"])).toBe(true);
  });

  it("emits an 8-node @graph (Article + ItemList + 3 items + BreadcrumbList + ClaimReview + WebPage) when no FAQs", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<{ "@type": string }> };
    const types = doc["@graph"].map((n) => n["@type"]);
    // ClaimReview added for schema.org fact-check parity with the 2-entity schema (HB178).
    // WebPage node added for bidirectional Article↔WebPage graph edge (HB325+).
    expect(types).toEqual([
      "Article",
      "ItemList",
      "SoftwareApplication",
      "SoftwareApplication",
      "SoftwareApplication",
      "BreadcrumbList",
      "ClaimReview",
      "WebPage",
    ]);
  });

  it("emits a 9-node @graph including FAQPage, ClaimReview and WebPage when faqs are present", () => {
    const withFaqs: ComparisonPageData = {
      ...cmp,
      faqs: [{ question: "Q?", answer: "A." }],
    };
    const doc = comparisonPageSchema(withFaqs)[0] as { "@graph": Array<{ "@type": string }> };
    const types = doc["@graph"].map((n) => n["@type"]);
    expect(types).toContain("FAQPage");
    expect(types).toContain("ClaimReview");
    expect(types).toContain("WebPage");
    expect(types).toHaveLength(9);
  });

  it("Article.mainEntity references the ItemList @id (#comparison)", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const article = doc["@graph"].find((n) => n["@type"] === "Article")!;
    expect(article.mainEntity).toEqual({ "@id": `${pageUrl}#comparison` });
  });

  it("ItemList carries numberOfItems and itemListOrder=Unordered and @id-references the item nodes", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const list = doc["@graph"].find((n) => n["@type"] === "ItemList")! as {
      "@id": string;
      numberOfItems: number;
      itemListOrder: string;
      itemListElement: Array<{ "@type": string; position: number; item: { "@id": string } }>;
    };
    expect(list["@id"]).toBe(`${pageUrl}#comparison`);
    expect(list.numberOfItems).toBe(3);
    expect(list.itemListOrder).toBe("https://schema.org/ItemListUnordered");
    expect(list.itemListElement.map((e) => e.position)).toEqual([1, 2, 3]);
    // DAN-1479: item nodes are @id'd by their canonical /entity/{slug} URL so they
    // merge with the entity ProfilePage node across the knowledge graph.
    expect(list.itemListElement.map((e) => e.item["@id"])).toEqual([
      `${SITE_URL}/entity/chatgpt`,
      `${SITE_URL}/entity/claude`,
      `${SITE_URL}/entity/gemini`,
    ]);
  });

  it("each SoftwareApplication item node carries the AI-chatbots cluster baseline", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const items = doc["@graph"].filter((n) => n["@type"] === "SoftwareApplication");
    expect(items).toHaveLength(3);
    for (const [i, item] of items.entries()) {
      // DAN-1479: @id is the canonical /entity/{slug} URL (entity-graph merge); the
      // node's own url mirrors it as the entity's profile page.
      expect(item["@id"]).toBe(`${SITE_URL}/entity/${cmp.entities[i].slug}`);
      expect(item.applicationCategory).toBe("BusinessApplication");
      expect(item.operatingSystem).toBe("Web, iOS, Android");
      expect(item.publisher).toMatchObject({ "@type": "Organization" });
      expect(item.url).toMatch(new RegExp(`^${SITE_URL}/entity/`));
      // image is emitted as an ImageObject (licensing/credit metadata) — assert its url.
      expect((item.image as { url: string }).url).toMatch(/^https:\/\//);
    }
  });

  it("top-level item nodes emit regardless of vote count (§6 vote-gate fix)", () => {
    const noVotes = comparisonPageSchema(cmp, null);
    const withZeroVotes = comparisonPageSchema(cmp, { votes: {}, total: 0 });
    for (const result of [noVotes, withZeroVotes]) {
      const items = (result[0] as { "@graph": Array<Record<string, unknown>> })["@graph"].filter(
        (n) => n["@type"] === "SoftwareApplication",
      );
      expect(items).toHaveLength(3);
      // aggregateRating field must NOT be populated when there are no real votes
      for (const item of items) {
        expect(item.aggregateRating).toBeUndefined();
      }
    }
  });

  it("aggregateRating field populates only when votes >= 10 and entity has votes (real-data-only)", () => {
    const votes: ComparisonVoteData = {
      votes: { ChatGPT: 7, Claude: 5, Gemini: 0 },
      total: 12,
    };
    const doc = comparisonPageSchema(cmp, votes)[0] as { "@graph": Array<Record<string, unknown>> };
    const items = doc["@graph"].filter((n) => n["@type"] === "SoftwareApplication");
    const byName: Record<string, Record<string, unknown>> = Object.fromEntries(
      items.map((i) => [i.name as string, i]),
    );
    expect(byName.ChatGPT.aggregateRating).toBeDefined();
    expect(byName.Claude.aggregateRating).toBeDefined();
    // Gemini has 0 votes — no fabricated rating field
    expect(byName.Gemini.aggregateRating).toBeUndefined();
  });

  it("does NOT emit Offer for the AI-chatbots cluster", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    for (const node of doc["@graph"]) {
      expect(node.offers).toBeUndefined();
      expect(node["@type"]).not.toBe("Offer");
    }
  });

  it("Article.publisher is the site Organization (separate from item publisher)", () => {
    const doc = comparisonPageSchema(cmp)[0] as { "@graph": Array<Record<string, unknown>> };
    const article = doc["@graph"].find((n) => n["@type"] === "Article")! as {
      publisher: { name: string; url: string };
    };
    expect(article.publisher.name).toBe(SITE_NAME);
    expect(article.publisher.url).toBe(SITE_URL);
  });

  it("every @graph node carries a stable canonical-host @id (entity-graph linkage)", () => {
    const withFaqs: ComparisonPageData = { ...cmp, faqs: [{ question: "Q?", answer: "A." }] };
    const doc = comparisonPageSchema(withFaqs)[0] as { "@graph": Array<Record<string, string>> };
    const byType: Record<string, string> = Object.fromEntries(
      doc["@graph"].map((n) => [n["@type"], n["@id"]]),
    );
    expect(byType.Article).toBe(`${pageUrl}#article`);
    expect(byType.BreadcrumbList).toBe(`${pageUrl}#breadcrumbs`);
    expect(byType.FAQPage).toBe(`${pageUrl}#faq`);
    expect(byType.ItemList).toBe(`${pageUrl}#comparison`);
    expect(byType.ClaimReview).toBe(`${pageUrl}#claimreview`);
    // No node may be missing its @id, and all must share the canonical host.
    // Item (SoftwareApplication) nodes intentionally use their /entity/{slug} @id
    // (DAN-1479 entity-graph merge); every other node anchors to the /compare/ page.
    for (const node of doc["@graph"]) {
      expect(node["@id"], `${node["@type"]} missing @id`).toBeTruthy();
      expect(node["@id"]).toMatch(new RegExp(`^${SITE_URL}/(compare|entity)/`));
    }
  });
});

describe("comparisonPageSchema — 2-way regression (unchanged shape)", () => {
  const cmp = baseComparison("iphone-vs-galaxy", "iPhone vs Galaxy", [
    entity(0, "iPhone 15", "iphone-15", { entityType: "product" }),
    entity(1, "Galaxy S24", "galaxy-s24", { entityType: "product" }),
  ]);

  it("returns an array of separate schemas (not a single @graph document) for N=2", () => {
    const schemas = comparisonPageSchema(cmp);
    expect(schemas.length).toBeGreaterThan(1);
    // No schema in the 2-way array should be a @graph container — each carries its own @context + @type
    for (const s of schemas as Record<string, unknown>[]) {
      expect(s["@graph"]).toBeUndefined();
      expect(s["@context"]).toBe("https://schema.org");
    }
  });

  it("Article.about[] still nests the entities (legacy shape preserved)", () => {
    const schemas = comparisonPageSchema(cmp);
    const article = (schemas as Array<Record<string, unknown>>).find(
      (s) => s["@type"] === "Article",
    )! as { about: Array<{ name: string }>; mainEntity?: unknown };
    expect(article.about).toHaveLength(2);
    expect(article.about.map((a) => a.name)).toEqual(["iPhone 15", "Galaxy S24"]);
    // Legacy 2-way shape does not carry mainEntity → #comparison (that's a 3-way addition)
    expect(article.mainEntity).toBeUndefined();
  });

  it("every 2-way node carries a stable canonical-host @id once consolidated into a @graph", () => {
    const withExtras: ComparisonPageData = {
      ...cmp,
      faqs: [{ question: "Q?", answer: "A." }],
      attributes: [{ name: "Battery", values: {} } as never],
    };
    const url = `${SITE_URL}/compare/${withExtras.slug}`;
    const byType: Record<string, string> = Object.fromEntries(
      (comparisonPageSchema(withExtras) as Array<Record<string, string>>).map((s) => [
        s["@type"],
        s["@id"],
      ]),
    );
    expect(byType.Article).toBe(`${url}#article`);
    expect(byType.ItemList).toBe(`${url}#list`);
    expect(byType.FAQPage).toBe(`${url}#faq`);
    expect(byType.BreadcrumbList).toBe(`${url}#breadcrumbs`);
    expect(byType.Dataset).toBe(`${url}#dataset`);
  });
});
