/**
 * Synthetic compare pages shaped like the ROO-154 live examples.
 * They are not database dumps. Tests and the dry-run script both use them.
 */

import type {
  ComparisonAttribute,
  ComparisonEntityData,
  ComparisonPageData,
  KeyDifference,
} from "@/types";

const METADATA: ComparisonPageData["metadata"] = {
  metaTitle: "Fixture",
  metaDescription: "Fixture",
  publishedAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
  isAutoGenerated: true,
  isHumanReviewed: false,
  viewCount: 0,
  status: "published",
};

function entity(id: string, name: string, position: number): ComparisonEntityData {
  return {
    id,
    slug: id,
    name,
    shortDesc: null,
    imageUrl: null,
    entityType: "country",
    position,
    pros: [],
    cons: [],
    bestFor: null,
  };
}

function row(
  id: string,
  name: string,
  entityA: string,
  entityB: string,
  a: string,
  b: string,
  extra?: {
    winner?: "a" | "b";
    source?: string;
    updatedAt?: string;
    unit?: string;
  },
): ComparisonAttribute {
  const winnerA = extra?.winner === "a";
  const winnerB = extra?.winner === "b";
  return {
    id,
    slug: id,
    name,
    unit: extra?.unit ?? null,
    category: "Economy",
    dataType: "number",
    higherIsBetter: null,
    values: [
      {
        entityId: entityA,
        valueText: a,
        valueNumber: null,
        valueBoolean: null,
        ...(winnerA ? { winner: true } : {}),
        ...(extra?.source ? { source: extra.source } : {}),
        ...(extra?.updatedAt ? { updatedAt: extra.updatedAt } : {}),
      },
      {
        entityId: entityB,
        valueText: b,
        valueNumber: null,
        valueBoolean: null,
        ...(winnerB ? { winner: true } : {}),
        ...(extra?.source ? { source: extra.source } : {}),
        ...(extra?.updatedAt ? { updatedAt: extra.updatedAt } : {}),
      },
    ],
  };
}

function page(
  slug: string,
  title: string,
  entities: ComparisonEntityData[],
  keyDifferences: KeyDifference[],
  attributes: ComparisonAttribute[],
  quick: string,
): ComparisonPageData {
  return {
    id: slug,
    slug,
    title,
    shortAnswer: quick,
    keyDifferences,
    verdict: null,
    category: "economy",
    entities,
    attributes,
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    quickAnswer: {
      tldr: quick,
      winnerName: null,
      winnerReason: null,
      keyFact: quick,
    },
    metadata: METADATA,
  };
}

/**
 * About 350 stored rows for a 7-row scorecard: six nominal-GDP vintages,
 * a Total GDP row that pastes China's $17.9T into the US column, debt-to-GDP
 * at both 77% and 282%, and a block of identical copied rows.
 */
export function usVsChinaGdpFixture(): ComparisonPageData {
  const us = "us";
  const cn = "cn";
  const entities = [
    entity(us, "United States", 0),
    entity(cn, "China", 1),
  ];
  const keyDifferences: KeyDifference[] = [
    { label: "Nominal GDP", entityAValue: "$30+ trillion", entityBValue: "about $19 trillion", winner: "a" },
    { label: "GDP (PPP)", entityAValue: "Second", entityBValue: "First", winner: "b" },
    { label: "GDP per capita", entityAValue: "about $89,000+", entityBValue: "about $13,500", winner: "a" },
    { label: "GDP growth", entityAValue: "about 2–2.5%", entityBValue: "about 4.5–5%", winner: "b" },
    { label: "Population", entityAValue: "333 million", entityBValue: "1.4 billion", winner: "b" },
    { label: "Debt-to-GDP", entityAValue: "122%", entityBValue: "77%", winner: "b" },
    { label: "Defense spending", entityAValue: "$886 billion", entityBValue: "$292 billion", winner: "a" },
  ];

  const attributes: ComparisonAttribute[] = [
    row("nom-1", "Nominal GDP", us, cn, "$27.4T", "$17.9T", { winner: "a", source: "Old blog", updatedAt: "2026-09-01T00:00:00.000Z" }),
    row("nom-2", "GDP (nominal)", us, cn, "$28.0T", "$17.8T"),
    row("nom-3", "GDP Nominal (USD)", us, cn, "$28.2 trillion", "$18.5 trillion", { unit: "USD" }),
    row("nom-4", "Nominal GDP 2024", us, cn, "$28.7T", "$18.2T"),
    row("nom-5", "US Nominal GDP", us, cn, "$28.8T", "$18.5T"),
    row("nom-6", "GDP (nominal, 2025)", us, cn, "$30.0–30.5T", "about $19 trillion"),
    row("nom-7", "Total GDP", us, cn, "$17.9T", "$17.9T"),
    row("debt-1", "Debt-to-GDP", us, cn, "122%", "77%", { winner: "b" }),
    row("debt-2", "Debt to GDP ratio", us, cn, "122%", "282%", { winner: "a" }),
    row("ppp-1", "GDP (PPP)", us, cn, "Second", "First", { winner: "b" }),
    row("ppp-2", "PPP GDP", us, cn, "$28.3T", "$35.4T"),
    row("ppp-3", "GDP PPP", us, cn, "$31.6T", "$45.78T"),
    row("ppp-4", "GDP (PPP, USD)", us, cn, "$35.4T", "$45.78T", { unit: "USD" }),
    row("def-1", "Defence spending (EUR)", us, cn, "€820 billion", "€270 billion", { unit: "EUR" }),
    row("def-2", "Defense spending (USD)", us, cn, "$886 billion", "$292 billion", { unit: "USD" }),
    row("pc-1", "GDP per capita", us, cn, "$80,300", "$12,500"),
    row("pc-2", "GDP per Capita", us, cn, "about $89,000+", "about $13,500"),
    row("gr-1", "GDP growth", us, cn, "2.5%", "5.2%"),
    row("gr-2", "2026 GDP growth", us, cn, "about 2–2.5%", "about 4.5–5%"),
    row("pop-1", "Population", us, cn, "333 million", "1.4 billion"),
  ];

  for (let i = 1; i <= 300; i += 1) {
    const value = i % 2 === 0 ? "$17.9T" : "282%";
    attributes.push(row(`copy-${i}`, `Copied metric ${i}`, us, cn, value, value));
  }
  for (let i = 1; i <= 30; i += 1) {
    const label = `Open metric ${String(i).padStart(2, "0")}`;
    attributes.push(row(`open-${i}`, label, us, cn, `${100 + i}`, `${400 + i}`));
  }

  return page(
    "us-vs-china-gdp",
    "US vs China GDP",
    entities,
    keyDifferences,
    attributes,
    "By nominal GDP the United States is larger (about $30+ trillion vs about $19 trillion). By PPP, China leads. GDP per capita is about $89,000+ vs about $13,500.",
  );
}

/**
 * Lyft's driver commission is stored as 75–80% and marked the winner, while
 * the scorecard says about 25%. Uber's 2024 revenue is stored four ways.
 */
export function lyftVsUberFixture(): ComparisonPageData {
  const uber = "uber";
  const lyft = "lyft";
  const entities = [
    entity(uber, "Uber", 0),
    entity(lyft, "Lyft", 1),
  ];
  const keyDifferences: KeyDifference[] = [
    { label: "Global Market Presence", entityAValue: "72 countries across 6 continents", entityBValue: "US and Canada", winner: "a" },
    { label: "US Rideshare Market Share", entityAValue: "71%", entityBValue: "29%", winner: "a" },
    { label: "Revenue Diversification", entityAValue: "Rideshare, Uber Eats, Uber Freight", entityBValue: "Rideshare only", winner: "a" },
    { label: "Driver Commission Rate", entityAValue: "25-30% platform fee", entityBValue: "approximately 25% platform fee", winner: "b" },
    { label: "2024 Annual Revenue", entityAValue: "$38.7 billion", entityBValue: "$4.3 billion", winner: "a" },
    { label: "Active Driver Base (Estimated)", entityAValue: "6+ million globally", entityBValue: "600,000-700,000 in North America", winner: "a" },
    { label: "Average Driver Rating Requirements", entityAValue: "4.6+ stars", entityBValue: "4.6+ stars", winner: "tie" },
  ];
  const attributes: ComparisonAttribute[] = [
    row("comm-bad", "Driver commission", uber, lyft, "25-30% platform fee", "75–80%", { winner: "b" }),
    row("comm-good", "Driver Commission Rate", uber, lyft, "25-30% platform fee", "approximately 25% platform fee", { winner: "b" }),
    row("rev-1", "2024 Annual Revenue", uber, lyft, "$37.2 billion", "$4.3 billion"),
    row("rev-2", "Annual Revenue (2024)", uber, lyft, "$38.1B", "$4.3B"),
    row("rev-3", "2024 Revenue", uber, lyft, "$38.7 billion", "$4.3 billion"),
    row("rev-4", "Uber 2024 revenue", uber, lyft, "$39.7 billion", "$4.3 billion", { source: "Press wire", updatedAt: "2026-08-01T00:00:00.000Z" }),
    row("geo-bad", "Geographic Coverage", uber, lyft, "70+ countries", "1 (US only)", { winner: "a" }),
    row("geo-good", "Global Market Presence", uber, lyft, "72 countries across 6 continents", "US and Canada", { winner: "a" }),
    row("share", "US Rideshare Market Share", uber, lyft, "71%", "29%", { winner: "a" }),
    row("mix", "Revenue Diversification", uber, lyft, "Rideshare, Uber Eats, Uber Freight", "Rideshare only", { winner: "a" }),
    row("drivers", "Active Driver Base (Estimated)", uber, lyft, "6+ million globally", "600,000-700,000 in North America", { winner: "a" }),
    row("rating", "Average Driver Rating Requirements", uber, lyft, "4.6+ stars", "4.6+ stars", { winner: "a" }),
    row("copy", "Copied coverage", uber, lyft, "US and Canada", "US and Canada"),
  ];

  return page(
    "lyft-vs-uber",
    "Lyft vs Uber",
    entities,
    keyDifferences,
    attributes,
    "Uber's 2024 annual revenue is $38.7 billion vs Lyft's $4.3 billion. Lyft's driver commission is approximately 25% platform fee. Lyft operates in the US and Canada.",
  );
}
