"use client";

import { useState, useEffect, useCallback } from "react";

interface ChangeLogEntry {
  id: string;
  version: number;
  action: string;
  changes: {
    field: string;
    summary: string;
  }[];
  performedBy: string;
  createdAt: string;
}

interface VersionHistoryProps {
  comparisonSlug: string;
  currentVersion: {
    updatedAt: string;
    isAutoGenerated: boolean;
    isHumanReviewed: boolean;
  };
}

const ACTION_CONFIG: Record<
  string,
  { label: string; icon: string; color: string; bgColor: string }
> = {
  created: {
    label: "Created",
    icon: "✦",
    color: "text-indigo-600",
    bgColor: "bg-indigo-100",
  },
  updated: {
    label: "Updated",
    icon: "↻",
    color: "text-purple-600",
    bgColor: "bg-purple-100",
  },
  refreshed: {
    label: "Data Refreshed",
    icon: "⟳",
    color: "text-blue-600",
    bgColor: "bg-blue-100",
  },
  reviewed: {
    label: "Human Reviewed",
    icon: "✓",
    color: "text-green-600",
    bgColor: "bg-green-100",
  },
};

const PERFORMER_LABELS: Record<string, string> = {
  system: "System",
  ai: "AI Engine",
  human: "Editor",
};

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function VersionHistory({
  comparisonSlug,
  currentVersion,
}: VersionHistoryProps) {
  const [entries, setEntries] = useState<ChangeLogEntry[]>([]);
  const [expandedEntries, setExpandedEntries] = useState<Set<string>>(
    new Set()
  );
  const [isExpanded, setIsExpanded] = useState(false);
  const [loading, setLoading] = useState(false);
  const [fetched, setFetched] = useState(false);

  const fetchHistory = useCallback(async () => {
    if (fetched) return;
    setLoading(true);
    try {
      const res = await fetch(
        `/api/comparisons/${comparisonSlug}/history`
      );
      if (res.ok) {
        const data = await res.json();
        setEntries(data.versions || []);
      }
    } catch {
      // Silently fail — fallback info is shown from props
    } finally {
      setLoading(false);
      setFetched(true);
    }
  }, [comparisonSlug, fetched]);

  useEffect(() => {
    if (isExpanded && !fetched) {
      fetchHistory();
    }
  }, [isExpanded, fetched, fetchHistory]);

  const toggleEntry = (id: string) => {
    setExpandedEntries((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const getConfig = (action: string) =>
    ACTION_CONFIG[action] || ACTION_CONFIG.updated;

  return (
    <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header bar */}
      <div className="bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-950/30 dark:to-purple-950/30 rounded-xl border border-indigo-100 dark:border-indigo-800/40 overflow-hidden">
        {/* Summary row — always visible */}
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="w-full px-6 py-4 flex items-center justify-between hover:bg-indigo-50/50 dark:hover:bg-indigo-950/20 transition-colors"
        >
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400">
              <svg
                className="w-5 h-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <span className="font-semibold text-sm">Version History</span>
            </div>
            <span className="text-xs text-text-secondary hidden sm:inline">
              Last updated {formatDate(currentVersion.updatedAt)}
            </span>
          </div>
          <div className="flex items-center gap-3">
            {currentVersion.isHumanReviewed && (
              <span className="hidden sm:inline-flex items-center gap-1 text-xs text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-950/30 px-2 py-0.5 rounded-full">
                <svg
                  className="w-3 h-3"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                    clipRule="evenodd"
                  />
                </svg>
                Verified
              </span>
            )}
            {currentVersion.isAutoGenerated && (
              <span className="hidden sm:inline-flex items-center gap-1 text-xs text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/30 px-2 py-0.5 rounded-full">
                AI
              </span>
            )}
            <svg
              className={`w-4 h-4 text-text-secondary transition-transform duration-200 ${
                isExpanded ? "rotate-180" : ""
              }`}
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 9l-7 7-7-7"
              />
            </svg>
          </div>
        </button>

        {/* Expanded timeline */}
        {isExpanded && (
          <div className="px-6 pb-6 pt-2 border-t border-indigo-100 dark:border-indigo-800/40">
            {loading ? (
              <div className="flex items-center justify-center py-8">
                <div className="animate-spin rounded-full h-6 w-6 border-2 border-indigo-300 border-t-indigo-600" />
                <span className="ml-3 text-sm text-text-secondary">
                  Loading history...
                </span>
              </div>
            ) : entries.length > 0 ? (
              <div className="relative ml-4 mt-2">
                {/* Connecting line */}
                <div className="absolute left-[7px] top-2 bottom-2 w-0.5 bg-gradient-to-b from-indigo-300 via-purple-300 to-indigo-200 dark:from-indigo-700 dark:via-purple-700 dark:to-indigo-800" />

                <div className="space-y-4">
                  {entries.map((entry, index) => {
                    const config = getConfig(entry.action);
                    const isEntryExpanded = expandedEntries.has(entry.id);
                    const isLatest = index === entries.length - 1;

                    return (
                      <div key={entry.id} className="relative pl-8">
                        {/* Timeline dot */}
                        <div
                          className={`absolute left-0 top-1 w-4 h-4 rounded-full border-2 border-white dark:border-gray-900 ${
                            isLatest
                              ? "bg-indigo-500 ring-2 ring-indigo-200 dark:ring-indigo-800"
                              : "bg-gray-300 dark:bg-gray-600"
                          }`}
                        />

                        {/* Entry card */}
                        <div
                          className={`rounded-lg border transition-all ${
                            isLatest
                              ? "border-indigo-200 dark:border-indigo-700 bg-white dark:bg-gray-900"
                              : "border-gray-100 dark:border-gray-800 bg-white/60 dark:bg-gray-900/60"
                          }`}
                        >
                          <button
                            onClick={() => toggleEntry(entry.id)}
                            className="w-full px-4 py-3 flex items-center justify-between text-left hover:bg-gray-50 dark:hover:bg-gray-800/50 rounded-lg transition-colors"
                          >
                            <div className="flex items-center gap-3">
                              <span
                                className={`inline-flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold ${config.bgColor} ${config.color}`}
                              >
                                {config.icon}
                              </span>
                              <div>
                                <div className="flex items-center gap-2">
                                  <span className="text-sm font-medium text-text">
                                    Version {entry.version}
                                  </span>
                                  <span
                                    className={`text-xs font-medium ${config.color}`}
                                  >
                                    {config.label}
                                  </span>
                                </div>
                                <div className="text-xs text-text-secondary mt-0.5">
                                  {formatDateTime(entry.createdAt)} &middot;{" "}
                                  {PERFORMER_LABELS[entry.performedBy] ||
                                    entry.performedBy}
                                </div>
                              </div>
                            </div>
                            <svg
                              className={`w-4 h-4 text-text-secondary transition-transform duration-200 ${
                                isEntryExpanded ? "rotate-180" : ""
                              }`}
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M19 9l-7 7-7-7"
                              />
                            </svg>
                          </button>

                          {/* Expanded changes */}
                          {isEntryExpanded && entry.changes.length > 0 && (
                            <div className="px-4 pb-3 pt-1 border-t border-gray-50 dark:border-gray-800">
                              <ul className="space-y-1.5">
                                {entry.changes.map((change, ci) => (
                                  <li
                                    key={ci}
                                    className="flex items-start gap-2 text-xs text-text-secondary"
                                  >
                                    <span className="text-indigo-400 mt-0.5">
                                      &bull;
                                    </span>
                                    <span>
                                      <span className="font-medium text-text capitalize">
                                        {change.field}
                                      </span>
                                      : {change.summary}
                                    </span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            ) : (
              /* Fallback: show minimal info from props */
              <div className="relative ml-4 mt-2">
                <div className="absolute left-[7px] top-2 bottom-2 w-0.5 bg-gradient-to-b from-indigo-300 to-indigo-200 dark:from-indigo-700 dark:to-indigo-800" />

                <div className="space-y-4">
                  <div className="relative pl-8">
                    <div className="absolute left-0 top-1 w-4 h-4 rounded-full border-2 border-white dark:border-gray-900 bg-gray-300 dark:bg-gray-600" />
                    <div className="rounded-lg border border-gray-100 dark:border-gray-800 bg-white/60 dark:bg-gray-900/60 px-4 py-3">
                      <div className="flex items-center gap-3">
                        <span className="inline-flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold bg-indigo-100 text-indigo-600">
                          ✦
                        </span>
                        <div>
                          <span className="text-sm font-medium text-text">
                            First Published
                          </span>
                          <div className="text-xs text-text-secondary mt-0.5">
                            {currentVersion.isAutoGenerated
                              ? "AI generated comparison"
                              : "Comparison created"}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="relative pl-8">
                    <div className="absolute left-0 top-1 w-4 h-4 rounded-full border-2 border-white dark:border-gray-900 bg-indigo-500 ring-2 ring-indigo-200 dark:ring-indigo-800" />
                    <div className="rounded-lg border border-indigo-200 dark:border-indigo-700 bg-white dark:bg-gray-900 px-4 py-3">
                      <div className="flex items-center gap-3">
                        <span className="inline-flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold bg-purple-100 text-purple-600">
                          ↻
                        </span>
                        <div>
                          <span className="text-sm font-medium text-text">
                            Last Updated
                          </span>
                          <div className="text-xs text-text-secondary mt-0.5">
                            {formatDate(currentVersion.updatedAt)}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  );
}
