/**
 * DAN-1800 — thin/scaled /compare/* footprint audit (spam-update recovery, lever #1).
 *
 * The Google June 2026 Spam Update downranked /compare/* for "scaled content
 * abuse". This audit classifies every published comparison by content depth and
 * historical demand so growth/product can sign off on a consolidate-vs-noindex
 * scope. It does NOT change any page — output only.
 *
 * Signals per page:
 *   - substantiveKeyDifferences: key-difference rows with real, contrasting
 *     values (reuses the same isSubstantiveValue helper the live quality gate
 *     uses, so the audit and the generator agree on what "thin" means).
 *   - searchImpressions: historical GSC impressions stored on the row (demand).
 *   - viewCount: lifetime page views (demand).
 *   - pairKey: sorted entity-slug pair — clusters A-vs-B with B-vs-A duplicates
 *     (extends DAN-1265 dedup).
 *
 * Classification:
 *   STRONG            — substantiveKD >= 3            → keep + deepen (lever #2)
 *   THIN_NO_DEMAND    — substantiveKD < 3 AND impressions < DEMAND_FLOOR
 *                       AND views < VIEW_FLOOR        → noindex candidate
 *   THIN_HAS_DEMAND   — substantiveKD < 3 but has demand → deepen, do NOT noindex
 *   DUP_CLUSTER       — member of an A/B ordering cluster → consolidate (DAN-1265)
 *
 * Usage: npx tsx scripts/dan1800-thin-page-audit.ts [--limit N] [--out FILE]
 */

import * as dotenv from "dotenv";
import * as path from "path";
import * as fs from "fs";
dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import { PrismaClient } from "@prisma/client";
import { isSubstantiveValue } from "../src/lib/services/comparison-quality";

const DEMAND_FLOOR = 5; // GSC impressions over the tracked window
const VIEW_FLOOR = 10; // lifetime page views
const MIN_SUBSTANTIVE_KD = 3;

// Key differences are persisted in THREE historical shapes across the corpus:
//   (1) 2-way object:  { label, entityAValue, entityBValue }
//   (2) N-way object:  { label, values: { entityName: value, ... } }  ← object, not array
//   (3) plain string:  "Monetization: Google uses ads; Perplexity is ad-free"
// An audit that only understands (1) mis-reports (2)/(3) as thin. Handle all.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function kdValues(kd: any): { label: string; vals: unknown[] } {
  if (typeof kd === "string") return { label: kd, vals: [kd] };
  const label = String(kd?.label ?? "").trim();
  let vals: unknown[];
  if (Array.isArray(kd?.values)) vals = kd.values;
  else if (kd?.values && typeof kd.values === "object") vals = Object.values(kd.values);
  else vals = [kd?.entityAValue, kd?.entityBValue];
  return { label, vals };
}

function substantiveKDCount(raw: unknown): number {
  if (!Array.isArray(raw)) return 0;
  let n = 0;
  for (const kd of raw) {
    const { label, vals } = kdValues(kd);
    const substantive = vals.filter((v) => isSubstantiveValue(v));
    const distinct = new Set(vals.filter(Boolean).map((v) => String(v).trim().toLowerCase()));
    // String rows carry a single self-describing value: substance is enough
    // (no two-sided contrast to check). Object rows need >=2 distinct sides.
    const isStringRow = typeof kd === "string";
    const contrastOK = isStringRow ? substantive.length >= 1 : distinct.size >= 2 && substantive.length >= 1;
    if (label.length >= 2 && contrastOK) n++;
  }
  return n;
}

function pairKeyFromSlug(slug: string): string {
  return slug.split("-vs-").map((s) => s.trim()).sort().join("|");
}

async function main() {
  const args = process.argv.slice(2);
  const limitArg = args.indexOf("--limit");
  const limit = limitArg !== -1 ? parseInt(args[limitArg + 1], 10) : undefined;
  const outArg = args.indexOf("--out");
  const outFile = outArg !== -1 ? args[outArg + 1] : "scripts/data/dan1800-thin-audit.json";

  const prisma = new PrismaClient();
  try {
    const rows = await prisma.comparison.findMany({
      where: { status: "published" },
      select: {
        slug: true,
        title: true,
        keyDifferences: true,
        searchImpressions: true,
        viewCount: true,
        isAutoGenerated: true,
        isHumanReviewed: true,
        createdAt: true,
      },
      ...(limit ? { take: limit } : {}),
    });

    const pairCounts = new Map<string, number>();
    for (const r of rows) pairCounts.set(pairKeyFromSlug(r.slug), (pairCounts.get(pairKeyFromSlug(r.slug)) || 0) + 1);

    const scored = rows.map((r) => {
      const kd = substantiveKDCount(r.keyDifferences);
      const impressions = r.searchImpressions ?? 0;
      const views = r.viewCount ?? 0;
      const inCluster = (pairCounts.get(pairKeyFromSlug(r.slug)) || 0) > 1;
      const entityCount = r.slug.split("-vs-").length;
      let bucket: string;
      if (inCluster) bucket = "DUP_CLUSTER";
      else if (kd >= MIN_SUBSTANTIVE_KD) bucket = "STRONG";
      // The substantiveKD metric is unreliable for 3+ entity pages (their
      // key-differences use exotic object/keyed shapes), so never auto-flag them
      // for noindex — route to manual review instead.
      else if (entityCount > 2) bucket = "REVIEW_NWAY_SHAPE";
      else if (impressions < DEMAND_FLOOR && views < VIEW_FLOOR) bucket = "THIN_NO_DEMAND";
      else bucket = "THIN_HAS_DEMAND";
      return { slug: r.slug, title: r.title, substantiveKD: kd, impressions, views, isAutoGenerated: r.isAutoGenerated, isHumanReviewed: r.isHumanReviewed, bucket };
    });

    const byBucket: Record<string, typeof scored> = {};
    for (const s of scored) (byBucket[s.bucket] ||= []).push(s);

    const summary = {
      generatedAt: new Date().toISOString(),
      totalPublished: rows.length,
      thresholds: { DEMAND_FLOOR, VIEW_FLOOR, MIN_SUBSTANTIVE_KD },
      buckets: Object.fromEntries(Object.entries(byBucket).map(([k, v]) => [k, v.length])),
      noindexCandidates: (byBucket["THIN_NO_DEMAND"] || []).sort((a, b) => a.substantiveKD - b.substantiveKD),
      deepenCandidates: (byBucket["THIN_HAS_DEMAND"] || []).sort((a, b) => b.impressions - a.impressions),
      dupClusterPages: (byBucket["DUP_CLUSTER"] || []).length,
    };

    fs.mkdirSync(path.dirname(path.resolve(__dirname, "..", outFile)), { recursive: true });
    fs.writeFileSync(path.resolve(__dirname, "..", outFile), JSON.stringify({ summary, scored }, null, 2));

    console.log("=== DAN-1800 thin-page audit ===");
    console.log(`Total published /compare/* pages: ${rows.length}`);
    for (const [k, v] of Object.entries(summary.buckets)) console.log(`  ${k}: ${v}`);
    console.log(`\nnoindex candidates (thin + no demand): ${summary.noindexCandidates.length}`);
    console.log(`deepen candidates (thin but has demand): ${summary.deepenCandidates.length}`);
    console.log(`pages in A/B duplicate clusters: ${summary.dupClusterPages}`);
    console.log(`\nFull report → ${outFile}`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
