import * as dotenv from "dotenv";
import * as path from "path";
dotenv.config({ override: true, path: path.resolve(__dirname, "../.env.local") });
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
async function main() {
  const row = await prisma.comparison.findUnique({
    where: { slug: "neymar-vs-mbappe" },
    include: {
      entities: { include: { entity: { include: { entityType: true, attributeValues: { include: { attribute: true } } } } } },
      faqs: true,
    },
  });
  if (!row) { console.log("NOT FOUND"); return; }
  console.log("=== COMPARISON ===");
  console.log("id:", row.id, "status:", row.status, "isHumanReviewed:", row.isHumanReviewed, "isAutoGenerated:", row.isAutoGenerated);
  console.log("viewCount:", row.viewCount, "searchImpressions:", row.searchImpressions, "category:", row.category);
  console.log("title:", row.title);
  console.log("metaTitle:", row.metaTitle);
  console.log("metaDescription:", row.metaDescription);
  console.log("publishedAt:", row.publishedAt, "updatedAt:", row.updatedAt);
  console.log("\n=== shortAnswer ===\n", row.shortAnswer);
  console.log("\n=== verdict ===\n", row.verdict);
  console.log("\n=== keyDifferences (raw) ===\n", JSON.stringify(row.keyDifferences, null, 2));
  console.log("\n=== entities ===");
  for (const ce of row.entities.sort((a,b)=>a.position-b.position)) {
    console.log(`  [pos ${ce.position}] ${ce.entity.name} (slug=${ce.entity.slug}, type=${ce.entity.entityType.slug})`);
    console.log("    shortDesc:", ce.entity.shortDesc);
    console.log("    pros:", JSON.stringify(ce.pros));
    console.log("    cons:", JSON.stringify(ce.cons));
    console.log("    bestFor:", JSON.stringify(ce.bestFor));
    console.log("    attributeValues:", ce.entity.attributeValues.map(av=>`${av.attribute.slug}=${av.valueText ?? av.valueNumber ?? av.valueBoolean}`).join(" | "));
  }
  console.log("\n=== FAQs ===");
  row.faqs.forEach((f,i)=>console.log(`  Q${i+1}: ${f.question}\n     A: ${f.answer}`));
}
main().catch(e=>{console.error(e);process.exit(1);}).finally(()=>prisma.$disconnect());
