import * as dotenv from "dotenv"; dotenv.config({ path: ".env.prod.tmp" });
import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();
(async () => {
  const byStatus = await p.comparison.groupBy({ by: ["status"], _count: { _all: true } });
  console.log("=== status distribution ===");
  console.table(byStatus.map(r => ({ status: r.status, count: r._count._all })));

  const probes = ["banana-vs-stapler","chatgpt-vs-google","copilot-vs-stack-overflow","nonexistent-vs-fake-xyz123","zzqq-vs-wwxx","clickup-vs-notion"];
  console.log("=== probe slugs ===");
  for (const s of probes) {
    const r = await p.comparison.findUnique({ where: { slug: s }, select: { slug:true, status:true, isAutoGenerated:true, createdAt:true, viewCount:true } });
    console.log(s.padEnd(30), r ? `status=${r.status} auto=${r.isAutoGenerated} created=${r.createdAt.toISOString().slice(0,10)}` : "NOT IN DB");
  }
  // Rows minted recently (SSR fallback suspects)
  const recent = await p.comparison.findMany({
    where: { createdAt: { gte: new Date("2026-07-01") } },
    select: { slug: true, status: true, createdAt: true, isAutoGenerated: true },
    orderBy: { createdAt: "desc" }, take: 30,
  });
  console.log(`=== rows created since 2026-07-01: ${recent.length} ===`);
  recent.forEach(r => console.log(" ", r.createdAt.toISOString().slice(0,16), r.status.padEnd(10), r.slug));
  await p.$disconnect();
})();
