/**
 * DAN-2078 — generate the rivalry-level consolidation map from LIVE prod data.
 *
 * Emits src/lib/redirects/compare-rivalry-redirects.dan2078.generated.ts.
 * Regenerate (read-only against prod; writes only the local file):
 *   set -a; . ./.env.local; set +a
 *   npx tsx scripts/dan2078-generate-rivalry-redirects.ts
 *
 * WHY A RIVALRY KEY, NOT A SLUG KEY
 * ---------------------------------
 * DAN-1265 / DAN-1800 grouped duplicates by slug shape: sort the `-vs-` tokens and
 * group on collision. That is blind to a duplicate whose two slugs share no tokens.
 * `us-economy-vs-china-economy` and `china-economy-size-vs-us` are the same page
 * twice but sort to different keys, so every slug-shaped sweep walked past them.
 * The key that sees them is the entity pair (the ComparisonEntity join) run through
 * the alias map — the same key the DAN-2047 studies collapse on, so the redirect map
 * and the published study figures now agree by construction, not by coincidence.
 *
 * SURVIVOR RULE: highest `searchImpressions` (real GSC data, synced onto the row by
 * gsc-service). NOT `viewCount` — that column is seed data, not traffic (DAN-2037),
 * and trusting it is exactly what made DAN-1265 keep 18 archived survivors that
 * DAN-2065 then had to unpick. 456 of 468 canonical rows carry non-zero impressions.
 *
 * SAFETY: sources and survivors are both drawn from `canonicalComparisonWhere()`, so
 * a survivor is always `published` AND not already a redirect source. A redirect into
 * an archived slug 404s the whole cluster — DAN-1908 / DAN-2065 hit that three times.
 *
 * MULTI-FACET CLUSTERS ARE EXCLUDED (see HELD_FOR_BOARD): the NFL/NBA and US/China
 * clusters carry facet-shaped slugs. Held pending the DAN-2078 board call.
 */
import { PrismaClient } from "@prisma/client";
import { writeFileSync } from "node:fs";
import { canonicalComparisonWhere } from "../src/lib/db/canonical-comparisons";
import { canonicalSlug } from "../src/lib/services/entity-aliases";

const prisma = new PrismaClient();

/**
 * Rivalries deliberately NOT consolidated here. Their slugs promise a facet
 * ("…-revenue", "…-viewership", "…-gdp", "…-economic-growth"), so collapsing them is
 * a content decision, not a mechanical one — even though the audit shows the bodies
 * do not actually honour those facets (DAN-2078 comment). Board call pending.
 */
const HELD_FOR_BOARD = new Set([
  "national-basketball-association-nba | national-football-league-nfl",
  "china-economy | united-states-economy",
]);

function rivalryKey(entitySlugs: string[]): string {
  return [...entitySlugs].map(canonicalSlug).sort().join(" | ");
}

async function main() {
  const rows = await prisma.comparison.findMany({
    where: canonicalComparisonWhere(),
    select: {
      slug: true,
      title: true,
      searchImpressions: true,
      entities: {
        select: { position: true, entity: { select: { slug: true } } },
        orderBy: { position: "asc" },
      },
    },
  });

  const clusters = new Map<string, typeof rows>();
  for (const row of rows) {
    const entitySlugs = row.entities.map((e) => e.entity.slug);
    if (entitySlugs.length !== 2) continue;
    const key = rivalryKey(entitySlugs);
    clusters.set(key, [...(clusters.get(key) ?? []), row]);
  }

  const dupes = [...clusters.entries()]
    .filter(([, g]) => g.length > 1)
    .sort((a, b) => a[0].localeCompare(b[0]));

  const lines: string[] = [];
  const map: Record<string, string> = {};
  let held = 0;

  for (const [key, group] of dupes) {
    if (HELD_FOR_BOARD.has(key)) {
      held += group.length;
      console.log(`HELD (board call): ${key} — ${group.length} pages`);
      continue;
    }
    // Survivor = most impressions. Deterministic tie-break on slug so a re-run
    // cannot silently flip a survivor and invert a live redirect.
    const ranked = [...group].sort(
      (a, b) =>
        b.searchImpressions - a.searchImpressions || a.slug.localeCompare(b.slug),
    );
    const [survivor, ...retired] = ranked;
    const detail = ranked.map((r) => `${r.slug} (${r.searchImpressions})`).join(" > ");
    lines.push(`  // ${key} — ${detail}`);
    for (const r of retired) {
      map[r.slug] = survivor.slug;
      lines.push(`  ${JSON.stringify(r.slug)}: ${JSON.stringify(survivor.slug)},`);
    }
    lines.push("");
  }

  // Invariant: no survivor may also be a retired source, or the edge 301-chains.
  const survivors = new Set(Object.values(map));
  for (const from of Object.keys(map)) {
    if (survivors.has(from)) throw new Error(`chain: ${from} is both source and survivor`);
  }

  const header = `/**
 * DAN-2078 — rivalry-level duplicate consolidation (retired slug -> survivor).
 *
 * GENERATED by scripts/dan2078-generate-rivalry-redirects.ts. Do not hand-edit:
 * re-run the generator instead, and re-run scripts/dan2065-full-map-audit.ts after.
 *
 * Grouped by ENTITY PAIR (alias-normalised), not slug shape — that is why this map
 * catches duplicates DAN-1265 / DAN-1800 could not see (\`us-economy-vs-china-economy\`
 * and \`china-economy-size-vs-us\` share no slug tokens but are the same rivalry).
 *
 * Survivor = highest \`searchImpressions\` (real GSC data). Never \`viewCount\` — that is
 * seed data, not traffic (DAN-2037). Impressions at decision time are recorded inline
 * so a future reader can see the call rather than re-derive it.
 *
 * The NFL/NBA (4 pages) and US/China-economy (7 pages) clusters are deliberately absent
 * — their slugs promise facets, so they are held for the DAN-2078 board call.
 */
export const RIVALRY_CONSOLIDATIONS_DAN2078: Record<string, string> = {
${lines.join("\n").trimEnd()}
};
`;

  writeFileSync("src/lib/redirects/compare-rivalry-redirects.dan2078.generated.ts", header);

  console.log(
    `\nClusters: ${dupes.length} duplicated | consolidated ${dupes.length - HELD_FOR_BOARD.size} | held ${HELD_FOR_BOARD.size} (${held} pages)`,
  );
  console.log(`Redirects emitted: ${Object.keys(map).length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
