/**
 * DAN-2045 — find every edge redirect that 308s onto a page that no longer exists,
 * and emit the drop-list consumed by src/lib/redirects/compare-redirects.ts.
 *
 * Why these exist: the ordering layers (DAN-1265 / DAN-1800) paired A-vs-B with
 * B-vs-A back when BOTH rows were published. DAN-1890 Phase B then archived pages
 * by viewCount and, for 163 clusters, archived BOTH members. The redirect outlived
 * the pages it was pointing between, so the source 308s to a 404 — Google spends a
 * hop to reach a dead end, which is strictly worse than serving the 404 directly.
 *
 * A redirect may only be dropped when its SOURCE is not a published row. Dropping a
 * published source would resurrect it as a live page and silently grow the corpus.
 * This generator refuses to emit any such slug — see the assertion below.
 *
 * Re-run after any archive sweep or consolidation batch:
 *   npx tsx scripts/dan2045-generate-dead-redirects.ts
 * then re-run scripts/dan2045-verify.ts.
 */
import fs from "fs";
import path from "path";
import { getPrisma } from "@/lib/db/prisma";
import { COMPARE_REDIRECTS } from "@/lib/redirects/compare-redirects";

const OUT = path.join(
  process.cwd(),
  "src/lib/redirects/compare-dead-redirects.dan2045.generated.ts"
);

async function main() {
  const prisma = getPrisma();
  if (!prisma) throw new Error("no DATABASE_URL — pull prod env before running");

  const slugOf = (u: string) => u.split("/compare/")[1];

  // A destination "exists" only if it is a renderable page: published rows render,
  // archived rows 404 (DAN-1886), and a missing row is a 404 too.
  const dests = [...new Set(COMPARE_REDIRECTS.map((r) => slugOf(r.destination)))];
  const liveDests = new Set(
    (
      await prisma.comparison.findMany({
        where: { slug: { in: dests }, status: "published" },
        select: { slug: true },
      })
    ).map((r: { slug: string }) => r.slug)
  );

  const broken = COMPARE_REDIRECTS.filter((r) => !liveDests.has(slugOf(r.destination)));
  const sources = broken.map((r) => slugOf(r.source));

  // Safety gate: never drop a redirect whose source would come back to life.
  const publishedSources = await prisma.comparison.findMany({
    where: { slug: { in: sources }, status: "published" },
    select: { slug: true },
  });
  if (publishedSources.length > 0) {
    throw new Error(
      `refusing to generate: ${publishedSources.length} broken-redirect sources are still published ` +
        `and would resurrect as live pages: ${publishedSources
          .map((r: { slug: string }) => r.slug)
          .join(", ")}. Archive them (or re-point the redirect) first.`
    );
  }

  const statusBySlug = new Map<string, string>(
    (
      await prisma.comparison.findMany({
        where: { slug: { in: [...sources, ...broken.map((r) => slugOf(r.destination))] } },
        select: { slug: true, status: true },
      })
    ).map((r: { slug: string; status: string }) => [r.slug, r.status])
  );
  const describe = (s: string) => statusBySlug.get(s) ?? "no row";

  const lines = broken
    .map((r) => ({ from: slugOf(r.source), to: slugOf(r.destination) }))
    .sort((a, b) => a.from.localeCompare(b.from))
    .map(
      ({ from, to }) =>
        `  // -> ${to} (${describe(to)}); source is ${describe(from)}\n  ${JSON.stringify(from)},`
    )
    .join("\n");

  const body = `/**
 * DAN-2045 — redirect sources whose destination is not a live page.
 *
 * GENERATED by scripts/dan2045-generate-dead-redirects.ts. Do not hand-edit:
 * re-run the generator instead, then re-run scripts/dan2045-verify.ts.
 *
 * Every slug here 308'd onto a 404. Both ends of each pair are archived, so dropping
 * the redirect turns a wasted hop into a direct 404 and changes no page's status.
 * Because every source is archived, removing these from the consolidation map does
 * NOT change the canonical corpus count — archived rows are already excluded by
 * \`canonicalComparisonWhere()\`.
 *
 * Generated ${new Date().toISOString().slice(0, 10)} against prod: ${broken.length} of ${COMPARE_REDIRECTS.length} redirects were broken.
 */
export const DEAD_REDIRECT_SOURCES_DAN2045: string[] = [
${lines}
];
`;
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${OUT}`);
  console.log(`broken: ${broken.length} of ${COMPARE_REDIRECTS.length} redirects`);
}

main().then(() => process.exit(0));
