import { PrismaClient } from '@prisma/client'
import * as dotenv from 'dotenv'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'
const __dirname = dirname(fileURLToPath(import.meta.url))
dotenv.config({ path: resolve('/Users/danielrozin/Comparison', '.env.local'), override: true })

const prisma = new PrismaClient()

async function main() {
  // Get top 100 pages by impressions
  const results = await prisma.comparison.findMany({
    where: { searchImpressions: { gt: 0 } },
    select: {
      slug: true, title: true, searchImpressions: true,
      isHumanReviewed: true, isAutoGenerated: true, content: true, status: true
    },
    orderBy: { searchImpressions: 'desc' },
    take: 100
  })
  
  console.log('All top 100 by impressions:')
  let rank = 0
  for (const r of results) {
    rank++
    const hasAnalysis = r.content && typeof r.content === 'object' && 'expertAnalysis' in r.content
    const isAuto = r.isAutoGenerated
    // Flag programmatic: slugs ending in "-2026", containing comparison keywords in a long form
    const isProgram = r.slug.match(/-2026$/) || r.slug.match(/comparison-\d{4}/) || r.slug.match(/specs-performance/) || r.slug.match(/performance-comparison/)
    console.log(`${rank}. [${hasAnalysis ? 'HAS' : 'NO '}] [${isAuto ? 'AUTO' : 'REAL'}] [${isProgram ? 'PROG' : 'SLUG'}] ${r.slug} — ${r.searchImpressions}`)
  }
  
  await prisma.$disconnect()
}

main().catch(e => { console.error(e); process.exit(1) })
