import * as dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";
import { createRequire } from "module";

dotenv.config({ path: "/Users/danielrozin/Comparison/.env.local" });

const require = createRequire(import.meta.url);
const Anthropic = require("/Users/danielrozin/Comparison/node_modules/@anthropic-ai/sdk");
const { PrismaClient } = require("/Users/danielrozin/Comparison/node_modules/@prisma/client");

const prisma = new PrismaClient();
const anthropic = new Anthropic.default({ apiKey: process.env.ANTHROPIC_API_KEY });

// High-volume pairs from the opportunity queue - categories and brands
const PAIRS = [
  // Finance (high volume)
  ["Robinhood", "Webull", "finance"],
  ["Fidelity", "Schwab", "finance"],
  ["Vanguard", "Fidelity", "finance"],
  ["Coinbase", "Binance", "finance"],
  // Productivity software
  ["Notion", "Monday.com", "software"],
  ["Slack", "Microsoft Teams", "software"],
  ["Zoom", "Google Meet", "software"],
  ["Asana", "Trello", "software"],
  ["Linear", "Jira", "software"],
  // Cloud/Tech
  ["AWS", "Google Cloud", "technology"],
  ["Azure", "AWS", "technology"],
  ["Vercel", "Netlify", "technology"],
  ["Supabase", "Firebase", "technology"],
  ["MongoDB", "PostgreSQL", "technology"],
  // Consumer brands
  ["Apple Watch", "Samsung Galaxy Watch", "products"],
  ["AirPods Pro", "Sony WF-1000XM5", "products"],
  ["Dyson", "Shark", "products"],
  ["Vitamix", "Blendtec", "products"],
  ["Peloton", "NordicTrack", "products"],
  ["Kindle", "Kobo", "products"],
];

function makeSlug(a, b) {
  const sa = a.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/g, "");
  const sb = b.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/g, "");
  return sa + "-vs-" + sb;
}

async function tavilySearch(query) {
  try {
    const res = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ api_key: process.env.TAVILY_API_KEY, query, max_results: 3 }),
    });
    if (!res.ok) return "";
    const data = await res.json();
    return (data.results || []).map(r => "- " + (r.content?.slice(0, 250))).join("\n");
  } catch { return ""; }
}

async function generateOne(entityA, entityB, category) {
  const slug = makeSlug(entityA, entityB);
  const existing = await prisma.comparison.findUnique({ where: { slug } });
  if (existing) {
    console.log("skip " + slug);
    return true;
  }

  console.log("gen: " + entityA + " vs " + entityB);
  const context = await tavilySearch(entityA + " vs " + entityB + " 2026");

  const prompt = "Generate SEO comparison between " + entityA + " and " + entityB + ".\n\nContext:\n" + (context || "No context.") + "\n\nReturn ONLY JSON: {title, metaTitle (<=60 chars), metaDescription (120-155 chars), shortAnswer (2-3 sentences), keyDifferences (4 strings array), verdict (paragraph)}";

  const response = await anthropic.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 800,
    messages: [{ role: "user", content: prompt }],
  });

  let data;
  try {
    data = JSON.parse(response.content[0].text.match(/\{[\s\S]*\}/)[0]);
  } catch (e) {
    console.error("parse err: " + slug);
    return false;
  }

  await prisma.comparison.create({
    data: {
      slug,
      title: data.title || (entityA + " vs " + entityB),
      metaTitle: data.metaTitle || (entityA + " vs " + entityB),
      metaDescription: data.metaDescription || ("Compare " + entityA + " and " + entityB),
      shortAnswer: data.shortAnswer || "",
      keyDifferences: data.keyDifferences || [],
      verdict: data.verdict || "",
      category,
      isAutoGenerated: true,
      status: "published",
      publishedAt: new Date(),
    }
  });
  console.log("saved: " + slug);
  return true;
}

async function main() {
  let ok = 0;
  for (const [a, b, cat] of PAIRS) {
    try { if (await generateOne(a, b, cat)) ok++; }
    catch (e) { console.error("err " + a + " vs " + b + ": " + e.message); }
    await new Promise(r => setTimeout(r, 800));
  }
  console.log("Done: " + ok + "/" + PAIRS.length);
  await prisma.$disconnect();
}
main().catch(console.error);
