/**
 * Generate blog articles for software and company verticals.
 * Run: npx tsx scripts/gen-blogs.ts
 */
import * as dotenv from "dotenv";
import * as path from "path";
dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import Anthropic from "@anthropic-ai/sdk";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

const BLOG_TOPICS = [
  // Software
  "Best VPN Services 2026: Complete Comparison Guide",
  "Best Antivirus Software 2026: Norton vs McAfee vs Bitdefender",
  "Best Web Hosting Providers 2026: Speed, Price & Support Compared",
  "Best Website Builders 2026: Wix vs Squarespace vs WordPress",
  "Best AI Chatbots 2026: ChatGPT vs Claude vs Gemini vs Perplexity",
  "Best Project Management Software 2026: Asana vs Monday vs ClickUp",
  "Best CRM Software 2026: HubSpot vs Salesforce vs Pipedrive",
  "Best Password Managers 2026: 1Password vs Bitwarden vs LastPass",
  "Best Email Marketing Platforms 2026: Mailchimp vs Klaviyo vs ConvertKit",
  "Best Accounting Software for Small Business 2026: QuickBooks vs Xero vs Wave",
  // Companies
  "OpenAI vs Anthropic 2026: Which AI Company is Leading?",
  "Best Food Delivery Apps 2026: A Complete Comparison",
  "Visa vs Mastercard 2026: Which Card Network is Better?",
  "Best Streaming Services 2026: Netflix vs Disney Plus vs HBO Max",
  "Best Fast Food Chains 2026: McDonald's vs Burger King vs Chick-fil-A",
];

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "").slice(0, 80);
}

async function tavilySearch(query: string): Promise<string> {
  const apiKey = process.env.TAVILY_API_KEY;
  if (!apiKey) return "";
  try {
    const res = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ api_key: apiKey, query, max_results: 5 }),
    });
    if (!res.ok) return "";
    const data: any = await res.json();
    return (data.results || []).map((r: any) => `- ${r.title}: ${r.content?.slice(0, 300)}`).join("\n");
  } catch { return ""; }
}

async function generateBlog(topic: string): Promise<boolean> {
  const slug = slugify(topic);

  const existing = await prisma.blogArticle.findUnique({ where: { slug } });
  if (existing) {
    console.log(`  ⏭ Already exists: ${slug}`);
    return true;
  }

  const enrichment = await tavilySearch(topic);

  const prompt = `You are a professional content writer for "A Versus B" (aversusb.net), a comparison platform.
Write an SEO-optimized blog article about: "${topic}"

Your article should be:
- Well-researched and factually accurate
- SEO-optimized with natural keyword usage
- Engaging and easy to read
- 1000-1500 words
- Include internal links to comparison pages using format [text](/compare/slug-a-vs-slug-b)
- Use markdown: ## for sections, ### for subsections, tables where appropriate

IMPORTANT: Use 'software' as the category for any software/SaaS/tool articles. Use 'companies' for company articles. Use 'entertainment' for streaming/media. Use 'food' for restaurant articles.

Valid categories: technology, sports, entertainment, lifestyle, science, business, education, health, travel, food, automotive

Return ONLY valid JSON:
{
  "title": "Article Title",
  "excerpt": "2-3 sentence compelling summary",
  "content": "Full markdown article content",
  "category": "one of the valid categories above",
  "tags": ["tag1", "tag2"],
  "metaTitle": "SEO title 50-60 chars",
  "metaDescription": "SEO description 150-160 chars",
  "relatedComparisonSlugs": ["slug-a-vs-slug-b"]
}

${enrichment ? `\nRecent web research:\n${enrichment}` : ""}`;

  const message = await anthropic.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 4000,
    messages: [{ role: "user", content: prompt }],
  });

  const text = (message.content[0] as any).text || "";
  let jsonText = text.trim();
  const jsonMatch = jsonText.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (jsonMatch) jsonText = jsonMatch[1].trim();

  let data: any;
  try { data = JSON.parse(jsonText); } catch { console.error(`  ✗ JSON parse failed`); return false; }

  await prisma.blogArticle.upsert({
    where: { slug },
    create: {
      slug,
      title: data.title || topic,
      excerpt: data.excerpt || null,
      content: data.content || "",
      category: data.category || "technology",
      tags: data.tags || [],
      metaTitle: data.metaTitle || topic,
      metaDescription: data.metaDescription || "",
      relatedComparisonSlugs: data.relatedComparisonSlugs || [],
      status: "published",
      isAutoGenerated: true,
      publishedAt: new Date(),
    },
    update: {
      title: data.title, excerpt: data.excerpt, content: data.content,
      category: data.category, tags: data.tags, metaTitle: data.metaTitle,
      metaDescription: data.metaDescription, relatedComparisonSlugs: data.relatedComparisonSlugs,
      status: "published", publishedAt: new Date(),
    },
  });

  return true;
}

async function main() {
  console.log(`Generating ${BLOG_TOPICS.length} blog articles...\n`);
  let success = 0, failed = 0;

  for (let i = 0; i < BLOG_TOPICS.length; i++) {
    const topic = BLOG_TOPICS[i];
    console.log(`[${i + 1}/${BLOG_TOPICS.length}] ${topic}`);
    const start = Date.now();
    try {
      const ok = await generateBlog(topic);
      const s = ((Date.now() - start) / 1000).toFixed(1);
      if (ok) { console.log(`  ✓ ${s}s`); success++; }
      else { console.log(`  ✗ Failed ${s}s`); failed++; }
    } catch (err: any) {
      console.log(`  ✗ Error: ${err.message?.slice(0, 100)}`);
      failed++;
    }
    if (i < BLOG_TOPICS.length - 1) await new Promise(r => setTimeout(r, 500));
  }

  console.log(`\nDone: ${success} success, ${failed} failed`);

  const total = await prisma.blogArticle.count({ where: { status: "published" } });
  console.log(`Total published blog articles: ${total}`);

  await prisma.$disconnect();
}

main().catch(e => { console.error(e); prisma.$disconnect(); process.exit(1); });
