/**
 * DAN-827: Publish "Best Cloud Platforms 2026" at /blog/best-cloud-platforms-2026.
 *
 * Upserts a BlogArticle row using the cleaned rev-3 body from DAN-426's
 * `draft-v1` document (schema bundle + internal-link manifest stripped before
 * insert). Idempotent — safe to re-run.
 *
 * Run: npx tsx scripts/publish-dan827-best-cloud-platforms-2026.ts
 */
import * as dotenv from "dotenv";
import * as path from "path";
import * as fs from "fs";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SLUG = "best-cloud-platforms-2026";
const TITLE = "Best Cloud Platforms 2026: 8 Top Providers Compared";
const META_TITLE =
  "Best Cloud Platforms 2026: AWS vs Azure vs GCP & 5 More Compared";
const META_DESCRIPTION =
  "Compare the 8 best cloud platforms of 2026 — pricing, free tiers, services, and use cases. AWS, Azure, GCP, Oracle, IBM, DigitalOcean, Linode, Vultr ranked.";
const EXCERPT =
  "We compare AWS, Azure, GCP, Oracle, IBM, DigitalOcean, Linode and Vultr on pricing, free tiers, services and use cases — and map six common use cases to a specific pick.";
const CATEGORY = "technology";
const TAGS = ["cloud", "aws", "azure", "gcp", "comparison", "2026"];
const PUBLISH_DATE = new Date("2026-05-29T00:00:00Z");

// Only slugs that exist in DB today. Body has inline links to 6 more that are
// queued as gaps (see comment back to DAN-827). When those land, add them here.
const RELATED_COMPARISON_SLUGS = ["aws-vs-azure", "aws-vs-google-cloud"];

async function main() {
  const bodyPath = path.resolve(
    __dirname,
    "data",
    "best-cloud-platforms-2026.md"
  );
  const content = fs.readFileSync(bodyPath, "utf-8");
  if (content.includes("## Schema bundle")) {
    throw new Error(
      "Body still contains '## Schema bundle' — appendix was not stripped"
    );
  }
  if (content.length < 25000 || content.length > 30000) {
    throw new Error(
      `Body length out of expected range (got ${content.length}, expected ~28000)`
    );
  }

  const result = await prisma.blogArticle.upsert({
    where: { slug: SLUG },
    create: {
      slug: SLUG,
      title: TITLE,
      excerpt: EXCERPT,
      content,
      category: CATEGORY,
      tags: TAGS,
      metaTitle: META_TITLE,
      metaDescription: META_DESCRIPTION,
      relatedComparisonSlugs: RELATED_COMPARISON_SLUGS,
      status: "published",
      isAutoGenerated: false,
      publishedAt: PUBLISH_DATE,
    },
    update: {
      title: TITLE,
      excerpt: EXCERPT,
      content,
      category: CATEGORY,
      tags: TAGS,
      metaTitle: META_TITLE,
      metaDescription: META_DESCRIPTION,
      relatedComparisonSlugs: RELATED_COMPARISON_SLUGS,
      status: "published",
      publishedAt: PUBLISH_DATE,
    },
  });
  console.log(`✔ upserted BlogArticle id=${result.id} slug=${result.slug}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
