/**
 * DAN-1424: Upsert 22 original blog articles from the import-bundle document.
 * Run: npx tsx scripts/publish-dan1424-blog-originals.ts
 */
import * as dotenv from "dotenv";
import * as path from "path";
dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import { PrismaClient } from "@prisma/client";
import * as fs from "fs";

const prisma = new PrismaClient();

interface Article {
  slug: string;
  title: string;
  description: string;
  tags: string[];
  canonical_url: string;
  body_markdown: string;
}

async function main() {
  const articlesPath = "/tmp/articles.json";
  const rawArticles: Article[] = JSON.parse(fs.readFileSync(articlesPath, "utf-8"));

  console.log(`Upserting ${rawArticles.length} articles...\n`);

  let success = 0;
  let failed = 0;

  for (const article of rawArticles) {
    try {
      await prisma.blogArticle.upsert({
        where: { slug: article.slug },
        create: {
          slug: article.slug,
          title: article.title || article.slug,
          excerpt: article.description || null,
          content: article.body_markdown || "",
          category: "business",
          tags: article.tags || [],
          metaTitle: article.title || null,
          metaDescription: article.description || null,
          relatedComparisonSlugs: [],
          status: "published",
          isAutoGenerated: false,
          publishedAt: new Date(),
        },
        update: {
          title: article.title,
          excerpt: article.description || null,
          content: article.body_markdown || "",
          category: "business",
          tags: article.tags || [],
          metaTitle: article.title || null,
          metaDescription: article.description || null,
          status: "published",
          isAutoGenerated: false,
          publishedAt: new Date(),
        },
      });
      console.log(`  ✓ ${article.slug}`);
      success++;
    } catch (err: any) {
      console.error(`  ✗ ${article.slug}: ${err.message}`);
      failed++;
    }
  }

  console.log(`\nDone: ${success} published, ${failed} failed`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
