/**
 * Publish ROO-27 / ROO-28 messaging compares into the catalog DB.
 *
 * Idempotent. After merge, owner can run (do not run from this PR):
 *   gh workflow run publish-editorial.yml -f script=scripts/publish-messaging-compares-roo27.ts
 *
 * The pages also render from the in-repo editorial pack so preview / post-merge
 * ISR can 200 before this workflow runs.
 */

import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import { saveComparison } from "../src/lib/services/comparison-service";
import { getPrisma } from "../src/lib/db/prisma";
import { listEditorialComparisons } from "../src/lib/data/editorial-compares";

async function main() {
  const pages = listEditorialComparisons();
  const prisma = getPrisma();
  if (!prisma) {
    console.error("FAIL: no DATABASE_URL / Prisma client.");
    process.exit(1);
  }

  for (const comparison of pages) {
    console.log(`Publishing ${comparison.slug}...`);
    const result = await saveComparison(comparison);
    if (!result) {
      console.error(`FAIL: saveComparison returned null for ${comparison.slug}`);
      process.exit(1);
    }

    const existing = await prisma.comparison.findUnique({
      where: { slug: comparison.slug },
      select: { publishedAt: true },
    });

    await prisma.comparison.update({
      where: { slug: comparison.slug },
      data: {
        status: "published",
        isHumanReviewed: true,
        isAutoGenerated: false,
        publishedAt: existing?.publishedAt ?? new Date(comparison.metadata.publishedAt ?? Date.now()),
        content: {
          expertAnalysis: comparison.expertAnalysis ?? null,
          quickAnswer: comparison.quickAnswer ?? null,
          citationStats: comparison.citationStats ?? null,
        } as object,
      },
    });

    console.log(`  saved id=${result.id} status=published`);
  }

  console.log("Done. Verify after ISR:");
  for (const page of pages) {
    console.log(`  curl -sI https://www.aversusb.net/compare/${page.slug} | head -n 1`);
  }
}

main().catch((err) => {
  console.error("Publish error:", err);
  process.exit(1);
});
