/**
 * Publish Track #3 Wave 1 — 5 manually-authored, human-reviewed comparison articles
 * for high-volume /compare/<slug> pages that were stuck in the "generating" state
 * (no Comparison DB record -> page fell back to the stalling DynamicComparison view).
 *
 * Source briefs: track3-content-briefs-wave1.md (Sales Lead -> Content Marketing Lead).
 * Content data: scripts/track3-data/<slug>.json (one per article).
 *
 * Creating a published Comparison record IS the publish action — getComparisonBySlug
 * does an exact findUnique with no status filter, so the page renders real content the
 * instant a record exists. (NOTE: the public site is separately gated on the Vercel
 * deployment hold, tracked as DAN-687; this script makes the content ready to serve.)
 *
 * Run: npx tsx scripts/publish-track3-wave1.ts
 * Dry run (no writes): DRY_RUN=1 npx tsx scripts/publish-track3-wave1.ts
 */
import * as dotenv from "dotenv";
import * as path from "path";
import * as fs from "fs";
dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const DRY_RUN = process.env.DRY_RUN === "1";
const REVIEWER = "Content Marketing Lead (Track #3 Wave 1)";

interface KeyDifference { label: string; entityAValue: string; entityBValue: string; winner: "a" | "b" | "tie"; }
interface ArticleEntity { name: string; slug: string; shortDesc: string; entityType: string; pros: string[]; cons: string[]; bestFor: string; }
interface ArticleAttribute { name: string; unit: string | null; category: string; dataType: string; higherIsBetter: boolean | null; entityAValue: string; entityANumber: number | null; entityBValue: string; entityBNumber: number | null; }
interface ArticleFAQ { question: string; answer: string; }
interface Article {
  slug: string; title: string; category: string;
  shortAnswer: string; verdict: string; metaTitle: string; metaDescription: string;
  keyDifferences: KeyDifference[];
  entities: [ArticleEntity, ArticleEntity];
  attributes: ArticleAttribute[];
  faqs: ArticleFAQ[];
  relatedSlugs: string[];
}

// Production order (commercial-intent ranked) per the brief.
const ORDER = [
  "cursor-vs-copilot",
  "m4-pro-vs-m4-max",
  "apple-vision-pro-vs-meta-quest-3",
  "cursor-vs-claude-code",
  "windsurf-vs-cursor",
];

function loadArticles(): Article[] {
  const dir = path.resolve(__dirname, "track3-data");
  return ORDER.map((slug) => {
    const file = path.join(dir, `${slug}.json`);
    const a = JSON.parse(fs.readFileSync(file, "utf8")) as Article;
    if (a.slug !== slug) throw new Error(`slug mismatch in ${file}: ${a.slug}`);
    return a;
  });
}

function attrSlug(name: string): string {
  return (name || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || `attr-${Date.now()}`;
}

async function publishOne(a: Article): Promise<void> {
  console.log(`\n→ ${a.slug}  (${a.title})`);
  console.log(`   KD=${a.keyDifferences.length} ATTR=${a.attributes.length} FAQ=${a.faqs.length} rel=${a.relatedSlugs.length}`);
  if (DRY_RUN) { console.log("   [dry run] skipping writes"); return; }

  const entityType = await prisma.entityType.upsert({
    where: { slug: a.category },
    create: { slug: a.category, name: a.category.charAt(0).toUpperCase() + a.category.slice(1) },
    update: {},
  });

  // Entities (shared canonical records keyed by slug — matches platform convention)
  const dbEntities = [] as { id: string }[];
  for (const e of a.entities) {
    const ent = await prisma.entity.upsert({
      where: { slug: e.slug },
      create: { slug: e.slug, name: e.name, shortDesc: e.shortDesc, entityTypeId: entityType.id, status: "published", publishedAt: new Date() },
      update: { name: e.name, shortDesc: e.shortDesc, status: "published" },
    });
    dbEntities.push(ent);
  }

  const comparison = await prisma.comparison.upsert({
    where: { slug: a.slug },
    create: {
      slug: a.slug, title: a.title,
      shortAnswer: a.shortAnswer, keyDifferences: a.keyDifferences as object,
      verdict: a.verdict, category: a.category,
      metaTitle: a.metaTitle, metaDescription: a.metaDescription,
      status: "published", isAutoGenerated: false, isHumanReviewed: true,
      reviewedBy: REVIEWER, reviewedAt: new Date(), publishedAt: new Date(),
    },
    update: {
      title: a.title, shortAnswer: a.shortAnswer, keyDifferences: a.keyDifferences as object,
      verdict: a.verdict, category: a.category,
      metaTitle: a.metaTitle, metaDescription: a.metaDescription,
      status: "published", isAutoGenerated: false, isHumanReviewed: true,
      reviewedBy: REVIEWER, reviewedAt: new Date(), publishedAt: new Date(),
    },
  });

  // Pros/cons/bestFor join rows (rebuild)
  await prisma.comparisonEntity.deleteMany({ where: { comparisonId: comparison.id } });
  await prisma.comparisonEntity.createMany({
    data: a.entities.map((e, i) => ({
      comparisonId: comparison.id, entityId: dbEntities[i].id, position: i,
      pros: e.pros, cons: e.cons, bestFor: e.bestFor,
    })),
  });

  // FAQs (rebuild)
  await prisma.fAQ.deleteMany({ where: { comparisonId: comparison.id } });
  for (const f of a.faqs) {
    await prisma.fAQ.create({ data: { question: f.question, answer: f.answer, comparisonId: comparison.id } });
  }

  // Attributes + per-entity values
  for (const at of a.attributes) {
    try {
      const slug = attrSlug(at.name);
      let dbAttr = await prisma.attribute.findFirst({ where: { slug, entityTypeId: entityType.id } });
      if (!dbAttr) {
        dbAttr = await prisma.attribute.create({
          data: { slug, name: at.name, unit: at.unit, dataType: at.dataType || "text", category: at.category || null, higherIsBetter: typeof at.higherIsBetter === "boolean" ? at.higherIsBetter : null, entityTypeId: entityType.id },
        });
      }
      await prisma.attributeValue.deleteMany({ where: { entityId: dbEntities[0].id, attributeId: dbAttr.id } });
      await prisma.attributeValue.create({ data: { entityId: dbEntities[0].id, attributeId: dbAttr.id, valueText: at.entityAValue ?? null, valueNumber: typeof at.entityANumber === "number" ? at.entityANumber : null, source: "track3-wave1" } });
      await prisma.attributeValue.deleteMany({ where: { entityId: dbEntities[1].id, attributeId: dbAttr.id } });
      await prisma.attributeValue.create({ data: { entityId: dbEntities[1].id, attributeId: dbAttr.id, valueText: at.entityBValue ?? null, valueNumber: typeof at.entityBNumber === "number" ? at.entityBNumber : null, source: "track3-wave1" } });
    } catch (e: unknown) {
      console.log(`   ! attribute "${at.name}" skipped: ${(e as Error).message?.slice(0, 80)}`);
    }
  }
  console.log(`   ✓ published (id=${comparison.id})`);
}

async function wireInternalLinks(articles: Article[]): Promise<void> {
  console.log("\n=== Wiring internal links (relatedComparisonIds) ===");
  for (const a of articles) {
    const wanted = a.relatedSlugs;
    const rows = await prisma.comparison.findMany({ where: { slug: { in: wanted } }, select: { id: true, slug: true } });
    const found = rows.map((r) => r.slug);
    const missing = wanted.filter((s) => !found.includes(s));
    if (DRY_RUN) {
      console.log(`   ${a.slug}: would link ${rows.length}/${wanted.length}${missing.length ? ` (missing: ${missing.join(", ")})` : ""}`);
      continue;
    }
    await prisma.comparison.update({ where: { slug: a.slug }, data: { relatedComparisonIds: rows.map((r) => r.id) } });
    console.log(`   ${a.slug}: linked ${rows.length}/${wanted.length}${missing.length ? ` (skipped non-existent: ${missing.join(", ")})` : ""}`);
  }
}

async function main(): Promise<void> {
  const articles = loadArticles();
  console.log(`Publishing ${articles.length} Track #3 Wave 1 articles${DRY_RUN ? " [DRY RUN]" : ""}...`);
  for (const a of articles) await publishOne(a);
  await wireInternalLinks(articles);

  // Verify
  const slugs = articles.map((a) => a.slug);
  const verify = await prisma.comparison.findMany({
    where: { slug: { in: slugs } },
    select: { slug: true, status: true, isHumanReviewed: true, isAutoGenerated: true, relatedComparisonIds: true, _count: { select: { entities: true, faqs: true } } },
  });
  console.log("\n=== Verification ===");
  for (const v of verify) {
    console.log(`   ${v.slug}: status=${v.status} humanReviewed=${v.isHumanReviewed} entities=${v._count.entities} faqs=${v._count.faqs} related=${v.relatedComparisonIds.length}`);
  }
  console.log(`\nDone: ${verify.length}/${slugs.length} present in DB.`);
  await prisma.$disconnect();
}

main().catch((e) => { console.error("FATAL:", e); process.exit(1); });
