/**
 * DAN-842: Publish "Aggregating 50K+ Product Reviews with AI" at
 * /blog/aggregating-product-reviews-with-ai.
 *
 * Source body adapted from syndicated/devto-article2-review-aggregation.md
 * (dev.to frontmatter stripped, comparison links normalized to relative paths,
 * appended evergreen conclusion). Internal links to existing live comparison
 * pages: airpods-pro-2-vs-sony-wf-1000xm5, chatgpt-vs-claude, anthropic-vs-openai.
 *
 * This is the canonical source post for dev.to Article 2 (DAN-263 syndication
 * queue). Once this returns HTTP 200, Partnerships Manager can publish to dev.to.
 *
 * Run: npx tsx scripts/publish-dan842-aggregating-product-reviews-with-ai.ts
 */
import * as dotenv from "dotenv";
import * as path from "path";
import * as fs from "fs";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SLUG = "aggregating-product-reviews-with-ai";
const TITLE = "Aggregating 50K+ Product Reviews with AI: What We Learned";
const META_TITLE =
  "Aggregating 50K+ Product Reviews with AI | aversusb.net";
const META_DESCRIPTION =
  "How we built a review aggregation pipeline that processes 50K+ reviews from Reddit, Amazon, RTINGS, and 45+ other sources — entity resolution, sentiment extraction, and the guardrails that keep AI honest.";
const EXCERPT =
  "How we built a review aggregation pipeline that processes 50K+ reviews from Reddit, Amazon, RTINGS, and 45+ other sources — entity resolution, sentiment extraction, and the guardrails that keep AI honest.";
const CATEGORY = "technology";
const TAGS = ["ai", "machine-learning", "reviews", "engineering", "comparison"];
const PUBLISH_DATE = new Date("2026-05-28T00:00:00Z");

const RELATED_COMPARISON_SLUGS = [
  "airpods-pro-2-vs-sony-wf-1000xm5",
  "chatgpt-vs-claude",
  "anthropic-vs-openai",
];

async function main() {
  const bodyPath = path.resolve(
    __dirname,
    "data",
    "aggregating-product-reviews-with-ai.md"
  );
  const content = fs.readFileSync(bodyPath, "utf-8");

  if (content.includes("canonical_url:") || content.includes("published: true")) {
    throw new Error(
      "Body still contains dev.to frontmatter — strip it before publishing"
    );
  }
  if (content.length < 4000) {
    throw new Error(
      `Body looks too short (got ${content.length} chars) — verify content`
    );
  }

  const result = await prisma.blogArticle.upsert({
    where: { slug: SLUG },
    create: {
      slug: SLUG,
      title: TITLE,
      excerpt: EXCERPT,
      content,
      category: CATEGORY,
      tags: TAGS,
      metaTitle: META_TITLE,
      metaDescription: META_DESCRIPTION,
      relatedComparisonSlugs: RELATED_COMPARISON_SLUGS,
      status: "published",
      isAutoGenerated: false,
      publishedAt: PUBLISH_DATE,
    },
    update: {
      title: TITLE,
      excerpt: EXCERPT,
      content,
      category: CATEGORY,
      tags: TAGS,
      metaTitle: META_TITLE,
      metaDescription: META_DESCRIPTION,
      relatedComparisonSlugs: RELATED_COMPARISON_SLUGS,
      status: "published",
      publishedAt: PUBLISH_DATE,
    },
  });
  console.log(`upserted BlogArticle id=${result.id} slug=${result.slug}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
