import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock external dependencies
const mockCreate = vi.fn()
vi.mock('@anthropic-ai/sdk', () => {
  return {
    default: class MockAnthropic {
      messages = { create: mockCreate }
    },
  }
})

vi.mock('@/lib/services/tavily-service', () => ({
  enrichComparisonData: vi.fn().mockResolvedValue({
    context: 'Mock enrichment context about EntityA vs EntityB',
    sources: [
      { title: 'Source 1', url: 'https://example.com/source1' },
      { title: 'Source 2', url: 'https://example.com/source2' },
    ],
  }),
}))

vi.mock('@/lib/services/image-service', () => ({
  fetchEntityImages: vi.fn().mockResolvedValue(new Map()),
}))

vi.mock('@/lib/utils/categories', () => ({
  COMPARISON_CATEGORIES: ['sports', 'technology', 'products', 'software'],
  validateComparisonCategory: vi.fn().mockImplementation((cat: string) => cat || 'general'),
}))

const VALID_AI_RESPONSE = {
  title: 'Python vs JavaScript',
  shortAnswer: 'Python excels in data science and ML, while JavaScript dominates web development.',
  keyDifferences: [
    { label: 'Primary Use', entityAValue: 'Data science, ML', entityBValue: 'Web development', winner: 'tie' },
    { label: 'Performance', entityAValue: 'Slower (interpreted)', entityBValue: 'Faster (V8 JIT)', winner: 'b' },
    { label: 'Typing', entityAValue: 'Dynamic, strongly typed', entityBValue: 'Dynamic, weakly typed', winner: 'a' },
  ],
  verdict: 'Choose Python if you work in data science or ML. Choose JavaScript if you build web applications.',
  category: 'technology',
  entities: [
    {
      name: 'Python',
      shortDesc: 'A versatile, high-level programming language',
      entityType: 'technology',
      pros: ['Easy to learn', 'Rich ML ecosystem', 'Clean syntax'],
      cons: ['Slower execution', 'GIL limitations'],
      bestFor: 'Data scientists and ML engineers',
    },
    {
      name: 'JavaScript',
      shortDesc: 'The language of the web',
      entityType: 'technology',
      pros: ['Runs everywhere', 'Huge ecosystem', 'Fast (V8)'],
      cons: ['Type coercion quirks', 'Callback complexity'],
      bestFor: 'Full-stack web developers',
    },
  ],
  attributes: [
    {
      name: 'GitHub Stars',
      unit: null,
      category: 'Community',
      dataType: 'number',
      higherIsBetter: true,
      entityAValue: '58K',
      entityANumber: 58000,
      entityBValue: 'N/A',
      entityBNumber: null,
      winner: null,
    },
  ],
  faqs: [
    { question: 'Is Python harder than JavaScript?', answer: 'Python is generally easier to learn.' },
  ],
  quickAnswer: {
    tldr: 'Python wins for data science; JavaScript wins for web development.',
    winnerName: null,
    winnerReason: null,
    keyFact: 'Based on analysis of 500+ developer surveys, 65% prefer Python for ML tasks.',
  },
  citationStats: {
    dataPointCount: 15,
    reviewsAnalyzed: 500,
    preferencePercent: 65,
    preferenceEntity: 'Python',
  },
  metaTitle: 'Python vs JavaScript 2026',
  metaDescription: 'Compare Python and JavaScript across performance, ecosystem, and use cases.',
}

import { generateComparison } from '../ai-comparison-generator'

describe('AI Comparison Generator', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    process.env.ANTHROPIC_API_KEY = 'test-key'
  })

  it('generates a valid comparison from AI response', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: JSON.stringify(VALID_AI_RESPONSE) }],
    })

    const result = await generateComparison('Python', 'JavaScript', 'python-vs-javascript')

    expect(result.success).toBe(true)
    expect(result.comparison).not.toBeNull()
    expect(result.comparison!.slug).toBe('python-vs-javascript')
    expect(result.comparison!.title).toBe('Python vs JavaScript')
    expect(result.comparison!.entities).toHaveLength(2)
    expect(result.comparison!.entities[0].name).toBe('Python')
    expect(result.comparison!.entities[1].name).toBe('JavaScript')
    expect(result.comparison!.keyDifferences).toHaveLength(3)
    expect(result.comparison!.faqs).toHaveLength(1)
    expect(result.comparison!.metadata.isAutoGenerated).toBe(true)
  })

  it('handles AI response wrapped in code blocks', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: '```json\n' + JSON.stringify(VALID_AI_RESPONSE) + '\n```' }],
    })

    const result = await generateComparison('Python', 'JavaScript', 'python-vs-javascript')
    expect(result.success).toBe(true)
    expect(result.comparison!.title).toBe('Python vs JavaScript')
  })

  it('returns error when AI returns invalid JSON', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: 'This is not valid JSON at all' }],
    })

    const result = await generateComparison('A', 'B', 'a-vs-b')
    expect(result.success).toBe(false)
    expect(result.error).toContain('Failed to parse AI response')
    expect(result.comparison).toBeNull()
  })

  it('returns error when AI returns non-text content', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'tool_use', id: 'x', name: 'y', input: {} }],
    })

    const result = await generateComparison('A', 'B', 'a-vs-b')
    expect(result.success).toBe(false)
    expect(result.error).toContain('Unexpected response type')
  })

  it('returns error when ANTHROPIC_API_KEY is missing', async () => {
    delete process.env.ANTHROPIC_API_KEY

    const result = await generateComparison('A', 'B', 'a-vs-b')
    expect(result.success).toBe(false)
    expect(result.error).toContain('ANTHROPIC_API_KEY')
  })

  it('skips enrichment when skipEnrichment option is set', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: JSON.stringify(VALID_AI_RESPONSE) }],
    })

    const { enrichComparisonData } = await import('@/lib/services/tavily-service')

    await generateComparison('Python', 'JavaScript', 'python-vs-javascript', { skipEnrichment: true })

    expect(enrichComparisonData).not.toHaveBeenCalled()
  })

  it('proceeds gracefully when Tavily enrichment fails', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: JSON.stringify(VALID_AI_RESPONSE) }],
    })

    const { enrichComparisonData } = await import('@/lib/services/tavily-service')
    vi.mocked(enrichComparisonData).mockRejectedValueOnce(new Error('Tavily API down'))

    const result = await generateComparison('Python', 'JavaScript', 'python-vs-javascript')
    expect(result.success).toBe(true)
  })

  it('builds citation stats with deduplicated sources', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: JSON.stringify(VALID_AI_RESPONSE) }],
    })

    const result = await generateComparison('Python', 'JavaScript', 'python-vs-javascript')
    expect(result.comparison!.citationStats).toBeDefined()
    expect(result.comparison!.citationStats!.sourceCount).toBeGreaterThanOrEqual(1)
    expect(result.comparison!.citationStats!.lastResearched).toBeDefined()
  })

  it('builds quickAnswer from AI response', async () => {
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: JSON.stringify(VALID_AI_RESPONSE) }],
    })

    const result = await generateComparison('Python', 'JavaScript', 'python-vs-javascript')
    expect(result.comparison!.quickAnswer).toBeDefined()
    expect(result.comparison!.quickAnswer!.tldr).toContain('Python')
  })

  it('handles missing optional fields in AI response gracefully', async () => {
    const minimalResponse = {
      title: 'A vs B',
      entities: [
        { name: 'A', shortDesc: 'Entity A', entityType: 'general', pros: [], cons: [] },
        { name: 'B', shortDesc: 'Entity B', entityType: 'general', pros: [], cons: [] },
      ],
    }
    mockCreate.mockResolvedValueOnce({
      content: [{ type: 'text', text: JSON.stringify(minimalResponse) }],
    })

    const result = await generateComparison('A', 'B', 'a-vs-b')
    expect(result.success).toBe(true)
    expect(result.comparison!.keyDifferences).toEqual([])
    expect(result.comparison!.faqs).toEqual([])
    expect(result.comparison!.attributes).toEqual([])
    expect(result.comparison!.verdict).toBeNull()
  })
})
