import { describe, it, expect } from 'vitest'
import { scoreComparison } from '../content-quality'
import type { ComparisonPageData } from '@/types'

const FULL_ENTITY_A = {
  id: 'ent-a',
  slug: 'test-a',
  name: 'Test A',
  shortDesc: 'A high-performance solution for demanding workloads',
  imageUrl: 'https://example.com/a.png',
  entityType: 'product',
  position: 0,
  pros: ['Fast processing', 'Scalable architecture', 'Enterprise support'],
  cons: ['Higher price', 'Steeper learning curve'],
  bestFor: 'Enterprise teams needing raw performance',
}

const FULL_ENTITY_B = {
  id: 'ent-b',
  slug: 'test-b',
  name: 'Test B',
  shortDesc: 'An easy-to-use solution focused on developer experience',
  imageUrl: 'https://example.com/b.png',
  entityType: 'product',
  position: 1,
  pros: ['Easy setup', 'Lower cost', 'Great documentation'],
  cons: ['Slower performance', 'Limited scalability'],
  bestFor: 'Startups and small teams who want simplicity',
}

function makeAttr(id: string, name: string): ComparisonPageData['attributes'][0] {
  return {
    id, slug: name.toLowerCase(), name, unit: null, category: 'Test',
    dataType: 'number', higherIsBetter: true,
    values: [
      { entityId: 'ent-a', valueText: '100', valueNumber: 100, valueBoolean: null },
      { entityId: 'ent-b', valueText: '200', valueNumber: 200, valueBoolean: null },
    ],
  }
}

function makeFullComparison(): ComparisonPageData {
  return {
    id: 'test-1',
    slug: 'test-a-vs-test-b',
    title: 'Test A vs Test B: Complete Comparison',
    shortAnswer: 'Test A is better for performance while Test B excels in usability and design quality.',
    keyDifferences: [
      { label: 'Speed', entityAValue: '100ms', entityBValue: '200ms', winner: 'a' as const },
      { label: 'Price', entityAValue: '$99', entityBValue: '$49', winner: 'b' as const },
      { label: 'Ease', entityAValue: 'Moderate', entityBValue: 'Easy', winner: 'b' as const },
    ],
    verdict: 'Choose Test A if you need raw performance and scalability. Choose Test B if you value simplicity and lower cost.',
    category: 'technology',
    entities: [FULL_ENTITY_A, FULL_ENTITY_B],
    attributes: [
      makeAttr('a1', 'Speed'), makeAttr('a2', 'Memory'), makeAttr('a3', 'Storage'),
      makeAttr('a4', 'Battery'), makeAttr('a5', 'Display'),
    ],
    faqs: [
      { question: 'Which is faster?', answer: 'Test A is faster with 100ms response time.' },
      { question: 'Which is cheaper?', answer: 'Test B at $49 vs $99 for Test A.' },
      { question: 'Which is easier?', answer: 'Test B has a lower learning curve.' },
    ],
    relatedComparisons: [
      { slug: 'c-vs-d', title: 'C vs D', category: 'technology' },
      { slug: 'e-vs-f', title: 'E vs F', category: 'technology' },
      { slug: 'g-vs-h', title: 'G vs H', category: 'technology' },
    ],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: 'Test A vs Test B 2026',
      metaDescription: 'Compare Test A and Test B across performance, price, and usability.',
      publishedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      isAutoGenerated: true,
      isHumanReviewed: false,
      viewCount: 100,
    },
  }
}

describe('Content Quality Scorer', () => {
  it('gives high score to a complete comparison', () => {
    const result = scoreComparison(makeFullComparison())
    expect(result.totalScore).toBeGreaterThanOrEqual(70)
    expect(result.grade).toMatch(/^[AB]$/)
    expect(result.completeness).toBeGreaterThan(30)
    expect(result.depth).toBeGreaterThan(20)
    expect(result.freshness).toBeGreaterThan(10)
  })

  it('scores lower when entities are empty', () => {
    const full = scoreComparison(makeFullComparison())
    const comp = makeFullComparison()
    comp.entities = []
    const result = scoreComparison(comp)
    expect(result.completeness).toBeLessThan(full.completeness)
    expect(result.depth).toBeLessThan(full.depth)
    expect(result.issues.length).toBeGreaterThan(0)
  })

  it('scores lower when verdict is missing', () => {
    const full = scoreComparison(makeFullComparison())
    const comp = makeFullComparison()
    comp.verdict = null
    const result = scoreComparison(comp)
    expect(result.completeness).toBeLessThan(full.completeness)
    expect(result.issues.length).toBeGreaterThan(0)
  })

  it('scores lower when FAQs are empty', () => {
    const full = scoreComparison(makeFullComparison())
    const comp = makeFullComparison()
    comp.faqs = []
    const result = scoreComparison(comp)
    expect(result.completeness).toBeLessThan(full.completeness)
    expect(result.issues.length).toBeGreaterThan(0)
  })

  it('scores lower when key differences are empty', () => {
    const full = scoreComparison(makeFullComparison())
    const comp = makeFullComparison()
    comp.keyDifferences = []
    const result = scoreComparison(comp)
    expect(result.completeness).toBeLessThan(full.completeness)
  })

  it('scores lower when attributes are empty', () => {
    const full = scoreComparison(makeFullComparison())
    const comp = makeFullComparison()
    comp.attributes = []
    const result = scoreComparison(comp)
    expect(result.completeness).toBeLessThan(full.completeness)
    expect(result.depth).toBeLessThan(full.depth)
  })

  it('gives low grade to minimal comparison', () => {
    const comp = makeFullComparison()
    comp.shortAnswer = null
    comp.verdict = null
    comp.keyDifferences = []
    comp.attributes = []
    comp.faqs = []
    comp.entities = []
    comp.relatedComparisons = []
    comp.metadata.updatedAt = new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString()
    const result = scoreComparison(comp)
    expect(result.grade).toMatch(/^[DF]$/)
    expect(result.totalScore).toBeLessThan(30)
    expect(result.issues.length).toBeGreaterThan(5)
  })

  it('detects stale content (180+ days old)', () => {
    const comp = makeFullComparison()
    comp.metadata.updatedAt = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString()
    const fresh = scoreComparison(makeFullComparison())
    const result = scoreComparison(comp)
    expect(result.freshness).toBeLessThan(fresh.freshness)
  })

  it('returns correct slug and title in result', () => {
    const result = scoreComparison(makeFullComparison())
    expect(result.slug).toBe('test-a-vs-test-b')
    expect(result.title).toBe('Test A vs Test B: Complete Comparison')
    expect(result.category).toBe('technology')
  })

  it('score components add up to totalScore', () => {
    const result = scoreComparison(makeFullComparison())
    const sum = result.completeness + result.depth + result.seoReadiness + result.freshness
    expect(result.totalScore).toBe(sum)
  })
})
