/**
 * A published legacy DB row for an in-repo editorial slug must not leak
 * auto-generated attributes, scores, ratings, or a winner into the page.
 * The editorial pack is the whole comparison. The DB row's status stays a
 * linkability signal and is not what this test covers.
 */
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { ComparisonPageData } from "@/types";
import { BRAVE_VS_CHROME } from "@/lib/data/editorial-compares/brave-vs-chrome";
import { assembleCompareJsonLd } from "@/lib/seo/compare-jsonld";

const mocks = vi.hoisted(() => ({
  findUnique: vi.fn(),
  attributeValueDeleteMany: vi.fn(),
  comparisonEntityFindMany: vi.fn(),
}));

vi.mock("@/lib/services/redis", () => ({ getRedis: () => null }));
vi.mock("@/lib/services/internal-linking-engine", () => ({
  getLinkedComparisons: vi.fn().mockResolvedValue([
    { slug: "legacy-related", title: "Legacy Related", category: "technology" },
  ]),
  getRelatedBlogPosts: vi.fn().mockResolvedValue([
    { slug: "legacy-blog", title: "Legacy Blog", category: "technology" },
  ]),
}));
vi.mock("@/lib/seo/indexnow", () => ({
  submitComparisonToIndexNow: vi.fn(() => Promise.resolve({ submitted: 0, ok: true })),
}));

vi.mock("@/lib/db/prisma", () => ({
  getPrisma: () => ({
    comparison: {
      findUnique: mocks.findUnique,
      upsert: vi.fn(async () => ({ id: "cmp-brave" })),
    },
    entityType: {
      upsert: vi.fn(async ({ where }: { where: { slug: string } }) => ({ id: `type-${where.slug}` })),
    },
    entity: {
      upsert: vi.fn(async ({ where }: { where: { slug: string } }) => ({ id: `db-${where.slug}` })),
    },
    comparisonEntity: {
      deleteMany: vi.fn(async () => ({ count: 0 })),
      create: vi.fn(async () => ({ id: "ce" })),
      findMany: mocks.comparisonEntityFindMany,
    },
    fAQ: {
      deleteMany: vi.fn(async () => ({ count: 0 })),
      create: vi.fn(async () => ({ id: "faq" })),
    },
    attribute: {
      upsert: vi.fn(async ({ where }: { where: { slug_entityTypeId: { slug: string } } }) => ({
        id: `attr-${where.slug_entityTypeId.slug}`,
      })),
    },
    attributeValue: {
      upsert: vi.fn(async () => ({ id: "av" })),
      deleteMany: mocks.attributeValueDeleteMany,
    },
    changeLog: {
      create: vi.fn(async () => ({ id: "log" })),
    },
  }),
}));

import { getComparisonBySlug, saveComparison } from "../comparison-service";

function legacyRow() {
  const attribute = (
    slug: string,
    name: string,
    valueText: string | null,
    valueNumber: number | null,
    higherIsBetter: boolean | null,
  ) => ({
    id: `av-${slug}`,
    valueText,
    valueNumber,
    valueBoolean: null,
    attribute: {
      id: `attr-${slug}`,
      slug,
      name,
      unit: valueNumber != null ? "score" : null,
      category: "Legacy",
      dataType: valueNumber != null ? "number" : "text",
      higherIsBetter,
    },
  });

  return {
    id: "db-legacy-brave",
    slug: "brave-vs-chrome",
    title: "Brave vs Chrome",
    shortAnswer: "Google Chrome leads on market share.",
    keyDifferences: [
      {
        label: "Market Share",
        entityAValue: "5%",
        entityBValue: "65%",
        winner: "b",
      },
    ],
    verdict: "Google Chrome leads",
    category: "technology",
    metaTitle: "Brave vs Chrome | A Versus B",
    metaDescription: "Chrome wins.",
    publishedAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-06-01T00:00:00Z"),
    isAutoGenerated: true,
    isHumanReviewed: false,
    viewCount: 4200,
    status: "published",
    relatedComparisonIds: ["legacy-related"],
    schemaMarkup: {
      "@context": "https://schema.org",
      "@graph": [
        { "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Who wins?", acceptedAnswer: { "@type": "Answer", text: "Chrome" } }] },
        { "@type": "ClaimReview", claimReviewed: "Google Chrome leads" },
      ],
    },
    content: {
      quickAnswer: {
        tldr: "Google Chrome leads",
        winnerName: "Google Chrome",
        winnerReason: "Market share",
        keyFact: "Score 50",
      },
      expertAnalysis: "Legacy analysis crowns Chrome.",
      citationStats: { sourceCount: 1, sources: [] },
    },
    entities: [
      {
        id: "ce-brave",
        position: 0,
        pros: ["Old pro"],
        cons: ["Old con"],
        bestFor: "Nobody",
        entity: {
          id: "ent-brave",
          slug: "brave",
          name: "Brave",
          shortDesc: "Legacy brave",
          imageUrl: null,
          entityType: { slug: "software" },
          attributeValues: [
            attribute("privacy-rating", "Privacy Rating", "Low", null, null),
            attribute("market-share", "Market Share", "65%", 65, true),
            attribute("score", "Score", null, 50, true),
          ],
        },
      },
      {
        id: "ce-chrome",
        position: 1,
        pros: ["Old chrome pro"],
        cons: [],
        bestFor: "Everyone",
        entity: {
          id: "ent-chrome",
          slug: "chrome",
          name: "Google Chrome",
          shortDesc: "Legacy chrome",
          imageUrl: null,
          entityType: { slug: "software" },
          attributeValues: [
            attribute("privacy-rating", "Privacy Rating", "High", null, null),
            attribute("market-share", "Market Share", "65%", 65, true),
            attribute("score", "Score", null, 90, true),
          ],
        },
      },
    ],
    faqs: [{ question: "Does Chrome win?", answer: "Yes. Google Chrome leads." }],
  };
}

function collectTypes(node: unknown, types: string[] = []): string[] {
  if (Array.isArray(node)) {
    for (const item of node) collectTypes(item, types);
    return types;
  }
  if (!node || typeof node !== "object") return types;
  const record = node as Record<string, unknown>;
  const type = record["@type"];
  if (typeof type === "string") types.push(type);
  else if (Array.isArray(type)) {
    for (const item of type) if (typeof item === "string") types.push(item);
  }
  for (const child of Object.values(record)) collectTypes(child, types);
  return types;
}

function plainPage(overrides: Partial<ComparisonPageData> = {}): ComparisonPageData {
  return {
    id: "plain",
    slug: "alpha-widget-vs-beta-widget",
    title: "Alpha Widget vs Beta Widget",
    shortAnswer: "Both widgets exist.",
    verdict: "It depends.",
    keyDifferences: [],
    category: "products",
    entities: [
      {
        id: "alpha",
        slug: "alpha-widget",
        name: "Alpha Widget",
        shortDesc: null,
        imageUrl: null,
        entityType: "product",
        position: 0,
        pros: [],
        cons: [],
        bestFor: null,
      },
      {
        id: "beta",
        slug: "beta-widget",
        name: "Beta Widget",
        shortDesc: null,
        imageUrl: null,
        entityType: "product",
        position: 1,
        pros: [],
        cons: [],
        bestFor: null,
      },
    ],
    attributes: [
      {
        id: "weight",
        slug: "weight",
        name: "Weight",
        unit: "g",
        category: "Physical",
        dataType: "number",
        higherIsBetter: false,
        values: [
          { entityId: "alpha", valueText: null, valueNumber: 10, valueBoolean: null },
          { entityId: "beta", valueText: null, valueNumber: 12, valueBoolean: null },
        ],
      },
    ],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: "Alpha Widget vs Beta Widget",
      metaDescription: "Compared.",
      publishedAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-01-01T00:00:00.000Z",
      isAutoGenerated: true,
      isHumanReviewed: false,
      viewCount: 0,
      status: "published",
    },
    ...overrides,
  };
}

describe("editorial compare ignores a legacy published DB row", () => {
  beforeEach(() => {
    mocks.findUnique.mockReset();
    mocks.attributeValueDeleteMany.mockReset();
    mocks.comparisonEntityFindMany.mockReset();
    mocks.findUnique.mockResolvedValue(legacyRow());
    mocks.attributeValueDeleteMany.mockResolvedValue({ count: 3 });
    mocks.comparisonEntityFindMany.mockResolvedValue([]);
  });

  it("assembles the editorial pack with no legacy attributes, winner, rating, or score", async () => {
    const page = await getComparisonBySlug("brave-vs-chrome");
    expect(page).not.toBeNull();

    expect(page!.id).toBe("db-legacy-brave");
    expect(page!.metadata.viewCount).toBe(4200);
    expect(page!.metadata.status).toBe("published");
    expect(page!.quickAnswer?.winnerName).toBeNull();
    expect(page!.verdict).toBe(BRAVE_VS_CHROME.verdict);
    expect(page!.shortAnswer).toBe(BRAVE_VS_CHROME.shortAnswer);
    expect(page!.attributes.map((attribute) => attribute.slug)).toEqual(
      BRAVE_VS_CHROME.attributes.map((attribute) => attribute.slug),
    );
    expect(page!.faqs.map((faq) => faq.question)).toEqual(
      BRAVE_VS_CHROME.faqs.map((faq) => faq.question),
    );
    expect(page!.relatedComparisons.map((item) => item.slug)).toEqual(
      BRAVE_VS_CHROME.relatedComparisons.map((item) => item.slug),
    );
    expect(page!.keyDifferences).toEqual(BRAVE_VS_CHROME.keyDifferences);

    const dumped = JSON.stringify(page);
    expect(dumped).not.toMatch(/Privacy Rating|Market Share|privacy-rating|market-share/);
    expect(dumped).not.toContain("Google Chrome leads");
    expect(dumped).not.toContain("65%");
    expect(page!.attributes.some((attribute) => /score|rating/i.test(attribute.slug))).toBe(false);
    expect(page!.attributes.some((attribute) => /score|rating/i.test(attribute.name))).toBe(false);
    expect(page!.attributes.some((attribute) => attribute.values.some((value) => value.valueNumber != null))).toBe(
      false,
    );

    const assembled = assembleCompareJsonLd({
      comparison: page!,
      voteData: null,
      videoNode: null,
      fallbackDescription: page!.shortAnswer || page!.title,
    });
    const documents = [assembled.document, assembled.claimReview].filter(Boolean);
    const types = documents.flatMap((doc) => collectTypes(doc));
    expect(types.filter((type) => type === "FAQPage")).toHaveLength(1);
    expect(types.filter((type) => type === "ClaimReview")).toHaveLength(1);
    expect(JSON.stringify(documents)).not.toContain("Google Chrome leads");
    expect(JSON.stringify(documents)).not.toContain("Privacy Rating");
  });
});

describe("saveComparison replaces editorial attribute rows", () => {
  beforeEach(() => {
    mocks.attributeValueDeleteMany.mockReset();
    mocks.comparisonEntityFindMany.mockReset();
    mocks.attributeValueDeleteMany.mockResolvedValue({ count: 1 });
    mocks.comparisonEntityFindMany.mockResolvedValue([]);
  });

  it("deletes stale attribute values for an editorial slug and keeps the pack's slugs", async () => {
    const saved = await saveComparison(BRAVE_VS_CHROME);
    expect(saved).not.toBeNull();

    const deletedEntityIds = mocks.attributeValueDeleteMany.mock.calls.map(
      (call) => (call[0] as { where: { entityId: string } }).where.entityId,
    );
    expect(deletedEntityIds.sort()).toEqual(["db-brave", "db-chrome"]);

    const braveCall = mocks.attributeValueDeleteMany.mock.calls.find(
      (call) => (call[0] as { where: { entityId: string } }).where.entityId === "db-brave",
    );
    const braveKeep = (braveCall![0] as { where: { attribute: { slug: { notIn: string[] } } } }).where.attribute
      .slug.notIn;
    expect(braveKeep).not.toContain("privacy-rating");
    expect(braveKeep).not.toContain("market-share");
    expect(braveKeep).not.toContain("score");
    for (const attribute of BRAVE_VS_CHROME.attributes) {
      expect(braveKeep).toContain(attribute.slug);
    }

    const again = await saveComparison(BRAVE_VS_CHROME);
    expect(again).not.toBeNull();
    expect(mocks.attributeValueDeleteMany).toHaveBeenCalledTimes(4);
  });

  it("does not delete attribute values on an entity shared with a non-editorial compare", async () => {
    mocks.comparisonEntityFindMany.mockResolvedValue([
      { entityId: "db-chrome", comparison: { slug: "chrome-vs-firefox" } },
    ]);

    const saved = await saveComparison(BRAVE_VS_CHROME);
    expect(saved).not.toBeNull();

    const deletedEntityIds = mocks.attributeValueDeleteMany.mock.calls.map(
      (call) => (call[0] as { where: { entityId: string } }).where.entityId,
    );
    expect(deletedEntityIds).toEqual(["db-brave"]);
    expect(deletedEntityIds).not.toContain("db-chrome");
  });

  it("does not delete attribute values when the slug is not editorial", async () => {
    const saved = await saveComparison(plainPage());
    expect(saved).not.toBeNull();
    expect(mocks.attributeValueDeleteMany).not.toHaveBeenCalled();
    expect(mocks.comparisonEntityFindMany).not.toHaveBeenCalled();
  });
});
