/**
 * A published legacy DB row for an in-repo editorial slug must not leak
 * auto-generated attributes, scores, ratings, or a winner into the page.
 * The editorial pack is the whole comparison. The DB row's status stays a
 * linkability signal and is not what this test covers.
 */
import { beforeEach, describe, expect, it, vi } from "vitest";
import { BRAVE_VS_CHROME } from "@/lib/data/editorial-compares/brave-vs-chrome";
import { assembleCompareJsonLd } from "@/lib/seo/compare-jsonld";

const mocks = vi.hoisted(() => ({
  findUnique: vi.fn(),
}));

vi.mock("@/lib/services/redis", () => ({ getRedis: () => null }));
vi.mock("@/lib/services/internal-linking-engine", () => ({
  getLinkedComparisons: vi.fn().mockResolvedValue([
    { slug: "legacy-related", title: "Legacy Related", category: "technology" },
  ]),
  getRelatedBlogPosts: vi.fn().mockResolvedValue([
    { slug: "legacy-blog", title: "Legacy Blog", category: "technology" },
  ]),
}));
vi.mock("@/lib/seo/indexnow", () => ({
  submitComparisonToIndexNow: vi.fn(() => Promise.resolve({ submitted: 0, ok: true })),
}));

vi.mock("@/lib/db/prisma", () => ({
  getPrisma: () => ({
    comparison: {
      findUnique: mocks.findUnique,
    },
  }),
}));

import { getComparisonBySlug } from "../comparison-service";

function legacyRow() {
  const attribute = (
    slug: string,
    name: string,
    valueText: string | null,
    valueNumber: number | null,
    higherIsBetter: boolean | null,
  ) => ({
    id: `av-${slug}`,
    valueText,
    valueNumber,
    valueBoolean: null,
    attribute: {
      id: `attr-${slug}`,
      slug,
      name,
      unit: valueNumber != null ? "score" : null,
      category: "Legacy",
      dataType: valueNumber != null ? "number" : "text",
      higherIsBetter,
    },
  });

  return {
    id: "db-legacy-brave",
    slug: "brave-vs-chrome",
    title: "Brave vs Chrome",
    shortAnswer: "Google Chrome leads on market share.",
    keyDifferences: [
      {
        label: "Market Share",
        entityAValue: "5%",
        entityBValue: "65%",
        winner: "b",
      },
    ],
    verdict: "Google Chrome leads",
    category: "technology",
    metaTitle: "Brave vs Chrome | A Versus B",
    metaDescription: "Chrome wins.",
    publishedAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-06-01T00:00:00Z"),
    isAutoGenerated: true,
    isHumanReviewed: false,
    viewCount: 4200,
    status: "published",
    relatedComparisonIds: ["legacy-related"],
    schemaMarkup: {
      "@context": "https://schema.org",
      "@graph": [
        { "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Who wins?", acceptedAnswer: { "@type": "Answer", text: "Chrome" } }] },
        { "@type": "ClaimReview", claimReviewed: "Google Chrome leads" },
      ],
    },
    content: {
      quickAnswer: {
        tldr: "Google Chrome leads",
        winnerName: "Google Chrome",
        winnerReason: "Market share",
        keyFact: "Score 50",
      },
      expertAnalysis: "Legacy analysis crowns Chrome.",
      citationStats: { sourceCount: 1, sources: [] },
    },
    entities: [
      {
        id: "ce-brave",
        position: 0,
        pros: ["Old pro"],
        cons: ["Old con"],
        bestFor: "Nobody",
        entity: {
          id: "ent-brave",
          slug: "brave",
          name: "Brave",
          shortDesc: "Legacy brave",
          imageUrl: null,
          entityType: { slug: "software" },
          attributeValues: [
            attribute("privacy-rating", "Privacy Rating", "Low", null, null),
            attribute("market-share", "Market Share", "65%", 65, true),
            attribute("score", "Score", null, 50, true),
          ],
        },
      },
      {
        id: "ce-chrome",
        position: 1,
        pros: ["Old chrome pro"],
        cons: [],
        bestFor: "Everyone",
        entity: {
          id: "ent-chrome",
          slug: "chrome",
          name: "Google Chrome",
          shortDesc: "Legacy chrome",
          imageUrl: null,
          entityType: { slug: "software" },
          attributeValues: [
            attribute("privacy-rating", "Privacy Rating", "High", null, null),
            attribute("market-share", "Market Share", "65%", 65, true),
            attribute("score", "Score", null, 90, true),
          ],
        },
      },
    ],
    faqs: [{ question: "Does Chrome win?", answer: "Yes. Google Chrome leads." }],
  };
}

function collectTypes(node: unknown, types: string[] = []): string[] {
  if (Array.isArray(node)) {
    for (const item of node) collectTypes(item, types);
    return types;
  }
  if (!node || typeof node !== "object") return types;
  const record = node as Record<string, unknown>;
  const type = record["@type"];
  if (typeof type === "string") types.push(type);
  else if (Array.isArray(type)) {
    for (const item of type) if (typeof item === "string") types.push(item);
  }
  for (const child of Object.values(record)) collectTypes(child, types);
  return types;
}

describe("editorial compare ignores a legacy published DB row", () => {
  beforeEach(() => {
    mocks.findUnique.mockReset();
    mocks.findUnique.mockResolvedValue(legacyRow());
  });

  it("assembles the editorial pack with no legacy attributes, winner, rating, or score", async () => {
    const page = await getComparisonBySlug("brave-vs-chrome");
    expect(page).not.toBeNull();

    expect(page!.id).toBe("db-legacy-brave");
    expect(page!.metadata.viewCount).toBe(4200);
    expect(page!.metadata.status).toBe("published");
    expect(page!.quickAnswer?.winnerName).toBeNull();
    expect(page!.verdict).toBe(BRAVE_VS_CHROME.verdict);
    expect(page!.shortAnswer).toBe(BRAVE_VS_CHROME.shortAnswer);
    expect(page!.attributes.map((attribute) => attribute.slug)).toEqual(
      BRAVE_VS_CHROME.attributes.map((attribute) => attribute.slug),
    );
    expect(page!.faqs.map((faq) => faq.question)).toEqual(
      BRAVE_VS_CHROME.faqs.map((faq) => faq.question),
    );
    expect(page!.relatedComparisons.map((item) => item.slug)).toEqual(
      BRAVE_VS_CHROME.relatedComparisons.map((item) => item.slug),
    );
    expect(page!.keyDifferences).toEqual(BRAVE_VS_CHROME.keyDifferences);

    const dumped = JSON.stringify(page);
    expect(dumped).not.toMatch(/Privacy Rating|Market Share|privacy-rating|market-share/);
    expect(dumped).not.toContain("Google Chrome leads");
    expect(dumped).not.toContain("65%");
    expect(page!.attributes.some((attribute) => /score|rating/i.test(attribute.slug))).toBe(false);
    expect(page!.attributes.some((attribute) => /score|rating/i.test(attribute.name))).toBe(false);
    expect(page!.attributes.some((attribute) => attribute.values.some((value) => value.valueNumber != null))).toBe(
      false,
    );

    const assembled = assembleCompareJsonLd({
      comparison: page!,
      voteData: null,
      videoNode: null,
      fallbackDescription: page!.shortAnswer || page!.title,
    });
    const documents = [assembled.document, assembled.claimReview].filter(Boolean);
    const types = documents.flatMap((doc) => collectTypes(doc));
    expect(types.filter((type) => type === "FAQPage")).toHaveLength(1);
    expect(types.filter((type) => type === "ClaimReview")).toHaveLength(1);
    expect(JSON.stringify(documents)).not.toContain("Google Chrome leads");
    expect(JSON.stringify(documents)).not.toContain("Privacy Rating");
  });
});
