// DAN-1266 — regression tests for empty-entity guards.
//
// Root cause: generateComparison/generateMultiComparison could return
// `{ success: true, comparison }` with `comparison.entities = []` when the
// model returned a parseable-but-empty JSON response.  saveComparison would
// then persist an empty-entity row, causing SSR to throw a 500 on read.
//
// Fix: (1) both generator paths return success:false when entities.length < 2;
//      (2) saveComparison refuses to upsert when entities.length < 2.

import { describe, it, expect, vi, beforeAll, afterAll } from 'vitest'

// ── saveComparison guard (no DB needed) ──────────────────────────────────────

vi.mock('@/lib/db/prisma', () => ({ getPrismaClient: () => null }))
vi.mock('@/lib/services/redis', () => ({ getRedis: () => null }))
vi.mock('@/lib/services/internal-linking-engine', () => ({
  getLinkedComparisons: vi.fn().mockResolvedValue([]),
}))

import { saveComparison } from '../comparison-service'

function makeComparisonData(entities: unknown[]) {
  return {
    id: 'test-id',
    slug: 'test-a-vs-test-b',
    title: 'Test A vs Test B',
    shortAnswer: null,
    keyDifferences: [],
    verdict: null,
    category: 'technology',
    entities,
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    metadata: {
      metaTitle: 'Test',
      metaDescription: 'Test',
      publishedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      isAutoGenerated: true,
      isHumanReviewed: false,
      viewCount: 0,
    },
    citationStats: null,
    quickAnswer: null,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any
}

describe('DAN-1266 — saveComparison empty-entity guard', () => {
  it('returns null and does not persist when entities is empty', async () => {
    const result = await saveComparison(makeComparisonData([]))
    expect(result).toBeNull()
  })

  it('returns null and does not persist when entities has only 1 entry', async () => {
    const result = await saveComparison(makeComparisonData([{ slug: 'only-one' }]))
    expect(result).toBeNull()
  })

  it('does not throw when entities is undefined', async () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data = makeComparisonData([]) as any
    data.entities = undefined
    await expect(saveComparison(data)).resolves.toBeNull()
  })
})

// ── generateComparison guard (mock Anthropic) ────────────────────────────────

const EMPTY_ENTITIES_JSON = JSON.stringify({
  title: 'Test A vs Test B',
  shortAnswer: 'Short',
  entities: [],
  keyDifferences: [],
  attributes: [],
  faqs: [],
  verdict: null,
  category: 'technology',
  metaTitle: 'Test A vs Test B',
  metaDescription: 'Compare Test A and Test B.',
})

const ONE_ENTITY_JSON = JSON.stringify({
  title: 'Test A vs Test B',
  shortAnswer: 'Short',
  entities: [{ name: 'Test A', shortDesc: 'desc', entityType: 'general', pros: [], cons: [] }],
  keyDifferences: [],
  attributes: [],
  faqs: [],
  verdict: null,
  category: 'technology',
  metaTitle: 'Test A vs Test B',
  metaDescription: 'Compare Test A and Test B.',
})

const mockMessagesCreate = vi.fn()

vi.mock('@anthropic-ai/sdk', () => {
  // Must use regular function (not arrow) so it can be called with `new`.
  function MockAnthropic() {
    return { messages: { create: mockMessagesCreate } }
  }
  return { default: MockAnthropic }
})

vi.mock('@/lib/services/tavily', () => ({
  enrichComparisonData: vi.fn().mockResolvedValue({ context: '', sources: [] }),
}))

vi.mock('@/lib/services/entity-image-fetcher', () => ({
  fetchEntityImages: vi.fn().mockResolvedValue(new Map()),
}))

import { generateComparison } from '../ai-comparison-generator'

describe('DAN-1266 — generateComparison empty-entity guard', () => {
  beforeAll(() => { process.env.ANTHROPIC_API_KEY = 'test-key-stub' })
  afterAll(() => { delete process.env.ANTHROPIC_API_KEY })

  it('returns success:false when model response has entities:[]', async () => {
    mockMessagesCreate.mockResolvedValueOnce({ content: [{ type: 'text', text: EMPTY_ENTITIES_JSON }] })
    const result = await generateComparison('Test A', 'Test B', 'test-a-vs-test-b', { skipEnrichment: true })
    expect(result.success).toBe(false)
    expect(result.comparison).toBeNull()
    expect(result.errorStage).toBe('parse')
    expect(result.error).toMatch(/fewer than 2 entities/i)
  })

  it('returns success:false when model response has only 1 entity', async () => {
    mockMessagesCreate.mockResolvedValueOnce({ content: [{ type: 'text', text: ONE_ENTITY_JSON }] })
    const result = await generateComparison('Test A', 'Test B', 'test-a-vs-test-b', { skipEnrichment: true })
    expect(result.success).toBe(false)
    expect(result.comparison).toBeNull()
    expect(result.errorStage).toBe('parse')
  })
})
