import type {
  ComparisonAttribute,
  ComparisonEntityData,
  ComparisonResource,
  FAQData,
  KeyDifference,
} from "@/types";
import { clampDescription } from "@/lib/seo/metadata";
import {
  EDITORIAL_COMPARE_PUBLISHED_AT,
  EDITORIAL_COMPARE_UPDATED_AT,
  type EditorialComparison,
} from "./types";

/** N-entity text row. Set `winner: true` on exactly one cell to crown that spec. */
export function textAttrN(
  slug: string,
  name: string,
  category: string,
  cells: { entityId: string; text: string; winner?: boolean }[]
): ComparisonAttribute {
  return {
    id: slug,
    slug,
    name,
    unit: null,
    category,
    dataType: "text",
    higherIsBetter: null,
    values: cells.map((cell) => ({
      entityId: cell.entityId,
      valueText: cell.text,
      valueNumber: null,
      valueBoolean: null,
      winner: cell.winner,
    })),
  };
}

export function textAttr(
  slug: string,
  name: string,
  category: string,
  entityAId: string,
  entityBId: string,
  a: string,
  b: string,
  winner?: "a" | "b"
): ComparisonAttribute {
  return {
    id: slug,
    slug,
    name,
    unit: null,
    category,
    dataType: "text",
    higherIsBetter: null,
    values: [
      {
        entityId: entityAId,
        valueText: a,
        valueNumber: null,
        valueBoolean: null,
        winner: winner === "a" ? true : winner === "b" ? false : undefined,
      },
      {
        entityId: entityBId,
        valueText: b,
        valueNumber: null,
        valueBoolean: null,
        winner: winner === "b" ? true : winner === "a" ? false : undefined,
      },
    ],
  };
}

export function buildEditorialComparison(opts: {
  slug: string;
  title: string;
  shortAnswer: string;
  verdict: string;
  category?: string;
  entities: ComparisonEntityData[];
  keyDifferences: KeyDifference[];
  attributes: ComparisonAttribute[];
  faqs: FAQData[];
  relatedComparisons: { slug: string; title: string; category: string | null }[];
  expertAnalysis: string;
  quickAnswer: NonNullable<EditorialComparison["quickAnswer"]>;
  citationStats: NonNullable<EditorialComparison["citationStats"]>;
  metaTitle: string;
  publishedAt?: string;
  updatedAt?: string;
  resources?: ComparisonResource[];
}): EditorialComparison {
  return {
    id: opts.slug,
    slug: opts.slug,
    title: opts.title,
    shortAnswer: opts.shortAnswer,
    verdict: opts.verdict,
    category: opts.category ?? "technology",
    entities: opts.entities,
    keyDifferences: opts.keyDifferences,
    attributes: opts.attributes,
    faqs: opts.faqs,
    relatedComparisons: opts.relatedComparisons,
    relatedBlogPosts: [],
    expertAnalysis: opts.expertAnalysis,
    quickAnswer: opts.quickAnswer,
    citationStats: opts.citationStats,
    resources: opts.resources,
    metadata: {
      metaTitle: opts.metaTitle,
      metaDescription: clampDescription(opts.shortAnswer),
      publishedAt: opts.publishedAt ?? EDITORIAL_COMPARE_PUBLISHED_AT,
      updatedAt: opts.updatedAt ?? EDITORIAL_COMPARE_UPDATED_AT,
      isAutoGenerated: false,
      isHumanReviewed: true,
      viewCount: 0,
      status: "published",
    },
  };
}
