/**
 * Comparison Service
 * Handles all comparison CRUD and query operations.
 * Uses Prisma when DATABASE_URL is set, falls back to mock data otherwise.
 */

import type {
  ComparisonPageData,
  ComparisonEntityData,
  ComparisonAttribute,
  FAQData,
  RelatedComparison,
  TrendingComparison,
} from "@/types";
import {
  getMockComparison,
  getMockTrending,
  getMockRelated,
  getAllMockSlugs,
  getMockComparisonsByCategory,
  getMockLatest,
} from "./mock-data";

import { getRedis } from "./redis";

// Lazy-import prisma to avoid crash when DATABASE_URL is not set
function getPrismaClient() {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { getPrisma } = require("@/lib/db/prisma");
    return getPrisma();
  } catch {
    return null;
  }
}

// Cache TTLs in seconds
const CACHE_TTL_COMPARISON = 300; // 5 min for individual comparisons
const CACHE_TTL_TRENDING = 120;   // 2 min for trending lists
const CACHE_TTL_SEARCH = 60;      // 1 min for search results

async function getFromCache<T>(key: string): Promise<T | null> {
  const redis = getRedis();
  if (!redis) return null;
  try {
    return await redis.get<T>(key);
  } catch {
    return null;
  }
}

async function setCache(key: string, value: unknown, ttl: number): Promise<void> {
  const redis = getRedis();
  if (!redis) return;
  try {
    await redis.set(key, value, { ex: ttl });
  } catch {
    // Silently fail — cache is optional
  }
}

async function invalidateCache(pattern: string): Promise<void> {
  const redis = getRedis();
  if (!redis) return;
  try {
    // Delete specific keys — pattern-based scan not used to keep it simple
    await redis.del(pattern);
  } catch {
    // Silently fail
  }
}

// ---------------------------------------------------------------------------
// Helpers: transform Prisma rows into ComparisonPageData
// ---------------------------------------------------------------------------

interface PrismaComparisonRow {
  id: string;
  slug: string;
  title: string;
  shortAnswer: string | null;
  keyDifferences: unknown;
  verdict: string | null;
  category: string | null;
  metaTitle: string | null;
  metaDescription: string | null;
  publishedAt: Date | null;
  updatedAt: Date;
  isAutoGenerated: boolean;
  isHumanReviewed: boolean;
  viewCount: number;
  relatedComparisonIds: string[];
  entities: {
    id: string;
    position: number;
    pros: string[];
    cons: string[];
    bestFor: string | null;
    entity: {
      id: string;
      slug: string;
      name: string;
      shortDesc: string | null;
      imageUrl: string | null;
      entityType: { slug: string };
      attributeValues: {
        id: string;
        valueText: string | null;
        valueNumber: number | null;
        valueBoolean: boolean | null;
        attribute: {
          id: string;
          slug: string;
          name: string;
          unit: string | null;
          category: string | null;
          dataType: string;
          higherIsBetter: boolean | null;
        };
      }[];
    };
  }[];
  faqs: { question: string; answer: string }[];
}

function transformToPageData(
  row: PrismaComparisonRow,
  relatedComps: RelatedComparison[] = []
): ComparisonPageData {
  // Build entities
  const entities: ComparisonEntityData[] = row.entities
    .sort((a, b) => a.position - b.position)
    .map((ce) => ({
      id: ce.entity.id,
      slug: ce.entity.slug,
      name: ce.entity.name,
      shortDesc: ce.entity.shortDesc,
      imageUrl: ce.entity.imageUrl,
      entityType: ce.entity.entityType.slug,
      position: ce.position,
      pros: ce.pros,
      cons: ce.cons,
      bestFor: ce.bestFor,
    }));

  // Build attributes from entity attribute values
  const attributeMap = new Map<
    string,
    {
      attr: {
        id: string;
        slug: string;
        name: string;
        unit: string | null;
        category: string | null;
        dataType: string;
        higherIsBetter: boolean | null;
      };
      values: {
        entityId: string;
        valueText: string | null;
        valueNumber: number | null;
        valueBoolean: boolean | null;
        winner?: boolean;
      }[];
    }
  >();

  for (const ce of row.entities) {
    for (const av of ce.entity.attributeValues) {
      if (!attributeMap.has(av.attribute.id)) {
        attributeMap.set(av.attribute.id, {
          attr: av.attribute,
          values: [],
        });
      }
      const entry = attributeMap.get(av.attribute.id)!;
      entry.values.push({
        entityId: ce.entity.id,
        valueText: av.valueText,
        valueNumber: av.valueNumber,
        valueBoolean: av.valueBoolean,
      });
    }
  }

  // Determine winners for numeric comparable attributes
  const attributes: ComparisonAttribute[] = Array.from(
    attributeMap.values()
  ).map(({ attr, values }) => {
    // Set winner flags for numeric attributes
    if (
      attr.higherIsBetter !== null &&
      values.length === 2 &&
      values[0].valueNumber !== null &&
      values[1].valueNumber !== null
    ) {
      const [v0, v1] = values;
      const higher = attr.higherIsBetter;
      if (v0.valueNumber! > v1.valueNumber!) {
        v0.winner = higher;
        v1.winner = !higher;
      } else if (v1.valueNumber! > v0.valueNumber!) {
        v1.winner = higher;
        v0.winner = !higher;
      }
    }
    return {
      id: attr.id,
      slug: attr.slug,
      name: attr.name,
      unit: attr.unit,
      category: attr.category,
      dataType: attr.dataType,
      higherIsBetter: attr.higherIsBetter,
      values,
    };
  });

  const faqs: FAQData[] = row.faqs.map((f) => ({
    question: f.question,
    answer: f.answer,
  }));

  const keyDifferences = Array.isArray(row.keyDifferences)
    ? (row.keyDifferences as ComparisonPageData["keyDifferences"])
    : [];

  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    shortAnswer: row.shortAnswer,
    keyDifferences,
    verdict: row.verdict,
    category: row.category,
    entities,
    attributes,
    faqs,
    relatedComparisons: relatedComps,
    metadata: {
      metaTitle:
        row.metaTitle || `${row.title}: Complete Comparison | Comparison`,
      metaDescription:
        row.metaDescription || row.shortAnswer?.slice(0, 155) || "",
      publishedAt: row.publishedAt?.toISOString() ?? null,
      updatedAt: row.updatedAt.toISOString(),
      isAutoGenerated: row.isAutoGenerated,
      isHumanReviewed: row.isHumanReviewed,
      viewCount: row.viewCount,
    },
  };
}

const COMPARISON_INCLUDE = {
  entities: {
    include: {
      entity: {
        include: {
          entityType: true,
          attributeValues: {
            include: { attribute: true },
          },
        },
      },
    },
  },
  faqs: true,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function getComparisonBySlug(
  slug: string
): Promise<ComparisonPageData | null> {
  // Check cache first
  const cacheKey = `comparison:${slug}`;
  const cached = await getFromCache<ComparisonPageData>(cacheKey);
  if (cached) return cached;

  const prisma = getPrismaClient();
  if (prisma) {
    try {
      const row = await prisma.comparison.findUnique({
        where: { slug },
        include: COMPARISON_INCLUDE,
      });
      if (row) {
        const related = await getRelatedFromDb(prisma, row);
        const result = transformToPageData(row as PrismaComparisonRow, related);
        await setCache(cacheKey, result, CACHE_TTL_COMPARISON);
        return result;
      }
    } catch (e) {
      console.warn("Prisma query failed for getComparisonBySlug, falling back to mock:", e);
    }
  }
  const mock = getMockComparison(slug);
  if (mock) await setCache(cacheKey, mock, CACHE_TTL_COMPARISON);
  return mock;
}

/**
 * Batch check which slugs exist in the comparisons table.
 * Returns only the slugs that have matching records — single query, no N+1.
 */
export async function getComparisonSlugsExisting(
  slugs: string[]
): Promise<string[]> {
  if (slugs.length === 0) return [];

  const prisma = getPrismaClient();
  if (!prisma) {
    // Fall back to mock data check
    return slugs.filter((slug) => getMockComparison(slug) !== null);
  }

  try {
    const rows = await prisma.comparison.findMany({
      where: { slug: { in: slugs } },
      select: { slug: true },
    });
    const dbSlugs = rows.map((r: { slug: string }) => r.slug);
    // Also check mock data for any slugs not in DB
    const mockSlugs = slugs.filter(
      (s) => !dbSlugs.includes(s) && getMockComparison(s) !== null
    );
    return [...dbSlugs, ...mockSlugs];
  } catch {
    return slugs.filter((slug) => getMockComparison(slug) !== null);
  }
}

export async function getTrendingComparisons(
  limit: number = 10
): Promise<TrendingComparison[]> {
  const cacheKey = `trending:${limit}`;
  const cached = await getFromCache<TrendingComparison[]>(cacheKey);
  if (cached) return cached;

  const prisma = getPrismaClient();
  if (prisma) {
    try {
      const rows = await prisma.comparison.findMany({
        where: { status: "published" },
        orderBy: { viewCount: "desc" },
        take: limit,
        include: {
          entities: {
            include: {
              entity: { select: { imageUrl: true } },
            },
            orderBy: { position: "asc" },
          },
        },
      });
      if (rows.length > 0) {
        const result = rows.map(
          (r: {
            slug: string;
            title: string;
            category: string | null;
            viewCount: number;
            entities: { entity: { imageUrl: string | null } }[];
          }) => ({
            slug: r.slug,
            title: r.title,
            category: r.category || "general",
            viewCount: r.viewCount,
            entityImages: r.entities
              .map((e: { entity: { imageUrl: string | null } }) => e.entity.imageUrl)
              .filter(Boolean) as string[],
          })
        );
        await setCache(cacheKey, result, CACHE_TTL_TRENDING);
        return result;
      }
    } catch (e) {
      console.warn("Prisma query failed for getTrendingComparisons, falling back to mock:", e);
    }
  }
  const mock = getMockTrending(limit);
  await setCache(cacheKey, mock, CACHE_TTL_TRENDING);
  return mock;
}

export type TrendingSortOption = "views" | "newest" | "score";

export interface TrendingPaginatedResult {
  items: TrendingComparison[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export async function getTrendingComparisonsPaginated(options: {
  page?: number;
  pageSize?: number;
  category?: string;
  sort?: TrendingSortOption;
} = {}): Promise<TrendingPaginatedResult> {
  const page = Math.max(1, options.page || 1);
  const pageSize = Math.min(100, Math.max(1, options.pageSize || 20));
  const category = options.category || "all";
  const sort = options.sort || "views";

  const cacheKey = `trending:paginated:${category}:${sort}:${page}:${pageSize}`;
  const cached = await getFromCache<TrendingPaginatedResult>(cacheKey);
  if (cached) return cached;

  const prisma = getPrismaClient();
  if (prisma) {
    try {
      const where: Record<string, unknown> = { status: "published" };
      if (category !== "all") {
        where.category = category;
      }

      const orderBy: Record<string, string> =
        sort === "newest" ? { createdAt: "desc" } :
        sort === "score" ? { contentScore: "desc" } :
        { viewCount: "desc" };

      const [rows, total] = await Promise.all([
        prisma.comparison.findMany({
          where,
          orderBy,
          skip: (page - 1) * pageSize,
          take: pageSize,
          include: {
            entities: {
              include: {
                entity: { select: { imageUrl: true } },
              },
              orderBy: { position: "asc" },
            },
          },
        }),
        prisma.comparison.count({ where }),
      ]);

      if (rows.length > 0 || total > 0) {
        const result: TrendingPaginatedResult = {
          items: rows.map(
            (r: {
              slug: string;
              title: string;
              category: string | null;
              viewCount: number;
              updatedAt: Date;
              entities: { entity: { imageUrl: string | null } }[];
            }) => ({
              slug: r.slug,
              title: r.title,
              category: r.category || "general",
              viewCount: r.viewCount,
              updatedAt: r.updatedAt?.toISOString() ?? null,
              entityImages: r.entities
                .map((e: { entity: { imageUrl: string | null } }) => e.entity.imageUrl)
                .filter(Boolean) as string[],
            })
          ),
          total,
          page,
          pageSize,
          totalPages: Math.ceil(total / pageSize),
        };
        await setCache(cacheKey, result, CACHE_TTL_TRENDING);
        return result;
      }
    } catch (e) {
      console.warn("Prisma query failed for getTrendingComparisonsPaginated, falling back to mock:", e);
    }
  }

  // Mock fallback: simulate pagination from full mock list
  const allMock = getMockTrending(200);
  const filtered = category === "all" ? allMock : allMock.filter(m => m.category === category);
  const sorted = sort === "newest" ? [...filtered].reverse() : filtered; // mock is already sorted by views
  const total = sorted.length;
  const items = sorted.slice((page - 1) * pageSize, page * pageSize);
  const result: TrendingPaginatedResult = { items, total, page, pageSize, totalPages: Math.ceil(total / pageSize) };
  await setCache(cacheKey, result, CACHE_TTL_TRENDING);
  return result;
}

export async function getRelatedComparisons(
  comparisonId: string,
  limit: number = 8
): Promise<RelatedComparison[]> {
  const cacheKey = `related:${comparisonId}:${limit}`;
  const cached = await getFromCache<RelatedComparison[]>(cacheKey);
  if (cached) return cached;

  const prisma = getPrismaClient();
  if (prisma) {
    try {
      const comp = await prisma.comparison.findUnique({
        where: { id: comparisonId },
        select: { category: true, relatedComparisonIds: true },
      });
      if (comp) {
        const result = await getRelatedFromDb(prisma, comp, limit);
        await setCache(cacheKey, result, CACHE_TTL_TRENDING);
        return result;
      }
    } catch (e) {
      console.warn("Prisma query failed for getRelatedComparisons, falling back to mock:", e);
    }
  }
  const mock = getMockRelated(comparisonId, limit);
  await setCache(cacheKey, mock, CACHE_TTL_TRENDING);
  return mock;
}

async function getRelatedFromDb(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  prisma: any,
  comp: { category?: string | null; relatedComparisonIds?: string[] },
  limit: number = 8
): Promise<RelatedComparison[]> {
  // First try explicit related IDs
  if (comp.relatedComparisonIds && comp.relatedComparisonIds.length > 0) {
    const related = await prisma.comparison.findMany({
      where: { id: { in: comp.relatedComparisonIds } },
      select: { slug: true, title: true, category: true },
      take: limit,
    });
    if (related.length > 0) return related;
  }
  // Fallback: same category
  if (comp.category) {
    const related = await prisma.comparison.findMany({
      where: { category: comp.category, status: "published" },
      select: { slug: true, title: true, category: true },
      take: limit,
    });
    return related;
  }
  return [];
}

export async function searchComparisons(
  query: string,
  limit: number = 20
): Promise<{ slug: string; title: string; category: string; viewCount: number }[]> {
  const searchCacheKey = `search:${query.toLowerCase().trim()}:${limit}`;
  const cached = await getFromCache<{ slug: string; title: string; category: string; viewCount: number }[]>(searchCacheKey);
  if (cached) return cached;

  const prisma = getPrismaClient();
  if (prisma) {
    try {
      const lower = query.toLowerCase();
      const rows = await prisma.comparison.findMany({
        where: {
          OR: [
            { title: { contains: lower, mode: "insensitive" } },
            { slug: { contains: lower.replace(/\s+/g, "-") } },
            { category: { contains: lower, mode: "insensitive" } },
          ],
        },
        select: {
          slug: true,
          title: true,
          category: true,
          viewCount: true,
        },
        orderBy: { viewCount: "desc" },
        take: limit,
      });
      if (rows.length > 0) {
        return rows.map(
          (r: { slug: string; title: string; category: string | null; viewCount: number }) => ({
            slug: r.slug,
            title: r.title,
            category: r.category || "general",
            viewCount: r.viewCount,
          })
        );
      }
    } catch (e) {
      console.warn("Prisma query failed for searchComparisons, falling back to mock:", e);
    }
  }

  // Mock fallback
  const allSlugs = getAllMockSlugs();
  const lower = query.toLowerCase();
  const results: { slug: string; title: string; category: string; viewCount: number }[] = [];

  for (const slug of allSlugs) {
    const comp = getMockComparison(slug);
    if (!comp) continue;
    const titleLower = comp.title.toLowerCase();
    const catLower = (comp.category || "").toLowerCase();
    if (
      titleLower.includes(lower) ||
      catLower.includes(lower) ||
      slug.includes(lower.replace(/\s+/g, "-")) ||
      comp.entities.some((e) => e.name.toLowerCase().includes(lower))
    ) {
      results.push({
        slug: comp.slug,
        title: comp.title,
        category: comp.category || "general",
        viewCount: comp.metadata.viewCount,
      });
    }
  }

  results.sort((a, b) => {
    const aExact = a.title.toLowerCase().includes(lower) ? 1 : 0;
    const bExact = b.title.toLowerCase().includes(lower) ? 1 : 0;
    if (aExact !== bExact) return bExact - aExact;
    return b.viewCount - a.viewCount;
  });

  const finalResults = results.slice(0, limit);
  await setCache(searchCacheKey, finalResults, CACHE_TTL_SEARCH);
  return finalResults;
}

export async function incrementViewCount(comparisonId: string): Promise<void> {
  const prisma = getPrismaClient();
  if (prisma) {
    try {
      await prisma.comparison.update({
        where: { id: comparisonId },
        data: { viewCount: { increment: 1 } },
      });
      return;
    } catch (e) {
      console.warn("Prisma incrementViewCount failed:", e);
    }
  }
  console.log(`View count incremented for ${comparisonId} (mock)`);
}

export async function getComparisonsByCategory(
  category: string,
  limit: number = 20,
  offset: number = 0
): Promise<{ comparisons: RelatedComparison[]; total: number }> {
  const prisma = getPrismaClient();
  if (prisma) {
    try {
      const [rows, total] = await Promise.all([
        prisma.comparison.findMany({
          where: { category: { equals: category, mode: "insensitive" } },
          select: { slug: true, title: true, category: true },
          orderBy: { viewCount: "desc" },
          skip: offset,
          take: limit,
        }),
        prisma.comparison.count({
          where: { category: { equals: category, mode: "insensitive" } },
        }),
      ]);
      if (rows.length > 0 || total > 0) {
        return { comparisons: rows, total };
      }
    } catch (e) {
      console.warn("Prisma getComparisonsByCategory failed:", e);
    }
  }

  const all = getMockComparisonsByCategory(category);
  const comparisons = all.map((comp) => ({
    slug: comp.slug,
    title: comp.title,
    category: comp.category,
  }));
  return {
    comparisons: comparisons.slice(offset, offset + limit),
    total: comparisons.length,
  };
}

// ---------------------------------------------------------------------------
// saveComparison — persist AI-generated (or mock) comparison to DB
// ---------------------------------------------------------------------------

export async function saveComparison(
  data: ComparisonPageData
): Promise<{ id: string } | null> {
  const prisma = getPrismaClient();
  if (!prisma) {
    console.warn("saveComparison: no database connection, skipping persist");
    return null;
  }

  try {
    // Determine entity type slug from data (default to "general")
    const entityTypeSlugs = [
      ...new Set(data.entities.map((e) => e.entityType || "general")),
    ];

    // Upsert EntityTypes
    const entityTypeMap = new Map<string, string>();
    for (const slug of entityTypeSlugs) {
      const et = await prisma.entityType.upsert({
        where: { slug },
        create: {
          slug,
          name: slug.charAt(0).toUpperCase() + slug.slice(1),
        },
        update: {},
      });
      entityTypeMap.set(slug, et.id);
    }

    // Upsert Entities
    const entityIdMap = new Map<string, string>(); // old id -> new db id
    for (const ent of data.entities) {
      const typeId = entityTypeMap.get(ent.entityType || "general")!;
      const dbEntity = await prisma.entity.upsert({
        where: { slug: ent.slug },
        create: {
          slug: ent.slug,
          name: ent.name,
          shortDesc: ent.shortDesc,
          imageUrl: ent.imageUrl,
          entityTypeId: typeId,
          status: "published",
        },
        update: {
          name: ent.name,
          shortDesc: ent.shortDesc,
          imageUrl: ent.imageUrl,
        },
      });
      entityIdMap.set(ent.id, dbEntity.id);
    }

    // Upsert Comparison
    const comparison = await prisma.comparison.upsert({
      where: { slug: data.slug },
      create: {
        slug: data.slug,
        title: data.title,
        shortAnswer: data.shortAnswer,
        keyDifferences: data.keyDifferences as unknown as object,
        verdict: data.verdict,
        category: data.category,
        metaTitle: data.metadata.metaTitle,
        metaDescription: data.metadata.metaDescription,
        status: "published",
        isAutoGenerated: data.metadata.isAutoGenerated,
        isHumanReviewed: data.metadata.isHumanReviewed,
        viewCount: data.metadata.viewCount || 0,
        publishedAt: data.metadata.publishedAt
          ? new Date(data.metadata.publishedAt)
          : new Date(),
        relatedComparisonIds: data.relatedComparisons.map((r) => r.slug),
      },
      update: {
        title: data.title,
        shortAnswer: data.shortAnswer,
        keyDifferences: data.keyDifferences as unknown as object,
        verdict: data.verdict,
        category: data.category,
        metaTitle: data.metadata.metaTitle,
        metaDescription: data.metadata.metaDescription,
        isAutoGenerated: data.metadata.isAutoGenerated,
        isHumanReviewed: data.metadata.isHumanReviewed,
        viewCount: data.metadata.viewCount || 0,
      },
    });

    // Clear existing join records for this comparison (to avoid duplicates on update)
    await prisma.comparisonEntity.deleteMany({
      where: { comparisonId: comparison.id },
    });
    await prisma.fAQ.deleteMany({
      where: { comparisonId: comparison.id },
    });

    // Create ComparisonEntity join records
    for (const ent of data.entities) {
      const dbEntityId = entityIdMap.get(ent.id)!;
      await prisma.comparisonEntity.create({
        data: {
          comparisonId: comparison.id,
          entityId: dbEntityId,
          position: ent.position,
          pros: ent.pros,
          cons: ent.cons,
          bestFor: ent.bestFor,
        },
      });
    }

    // Create Attributes and AttributeValues
    for (const attr of data.attributes) {
      // Find the entity type for this attribute (use first entity's type)
      const firstEntityTypeSlug =
        data.entities[0]?.entityType || "general";
      const typeId = entityTypeMap.get(firstEntityTypeSlug)!;

      const dbAttr = await prisma.attribute.upsert({
        where: {
          slug_entityTypeId: {
            slug: attr.slug,
            entityTypeId: typeId,
          },
        },
        create: {
          slug: attr.slug,
          name: attr.name,
          unit: attr.unit,
          category: attr.category,
          dataType: attr.dataType,
          higherIsBetter: attr.higherIsBetter,
          entityTypeId: typeId,
        },
        update: {
          name: attr.name,
          unit: attr.unit,
          category: attr.category,
          higherIsBetter: attr.higherIsBetter,
        },
      });

      // Create attribute values for each entity
      for (const val of attr.values) {
        const dbEntityId = entityIdMap.get(val.entityId);
        if (!dbEntityId) continue;

        await prisma.attributeValue.upsert({
          where: {
            entityId_attributeId: {
              entityId: dbEntityId,
              attributeId: dbAttr.id,
            },
          },
          create: {
            entityId: dbEntityId,
            attributeId: dbAttr.id,
            valueText: val.valueText,
            valueNumber: val.valueNumber,
            valueBoolean: val.valueBoolean,
          },
          update: {
            valueText: val.valueText,
            valueNumber: val.valueNumber,
            valueBoolean: val.valueBoolean,
          },
        });
      }
    }

    // Create FAQ records
    for (const faq of data.faqs) {
      await prisma.fAQ.create({
        data: {
          question: faq.question,
          answer: faq.answer,
          comparisonId: comparison.id,
        },
      });
    }

    // Create ChangeLog entry
    await prisma.changeLog.create({
      data: {
        entityType: "comparison",
        entityId: comparison.id,
        action: "created",
        changes: {
          title: data.title,
          slug: data.slug,
          category: data.category,
          entityCount: data.entities.length,
          attributeCount: data.attributes.length,
          faqCount: data.faqs.length,
        },
        comparisonId: comparison.id,
      },
    });

    // Invalidate cached comparison and trending list
    await invalidateCache(`comparison:${data.slug}`);
    await invalidateCache(`trending:10`);

    return { id: comparison.id };
  } catch (e) {
    console.error("saveComparison failed:", e);
    return null;
  }
}

// ---------------------------------------------------------------------------
// getComparisonHistory — get change log for a comparison
// ---------------------------------------------------------------------------

export async function getComparisonHistory(
  slug: string
): Promise<
  {
    id: string;
    action: string;
    changes: unknown;
    performedBy: string | null;
    createdAt: string;
  }[]
> {
  const prisma = getPrismaClient();
  if (!prisma) return [];

  try {
    const comp = await prisma.comparison.findUnique({
      where: { slug },
      select: { id: true },
    });
    if (!comp) return [];

    const logs = await prisma.changeLog.findMany({
      where: { comparisonId: comp.id },
      orderBy: { createdAt: "desc" },
    });

    return logs.map(
      (l: {
        id: string;
        action: string;
        changes: unknown;
        performedBy: string | null;
        createdAt: Date;
      }) => ({
        id: l.id,
        action: l.action,
        changes: l.changes,
        performedBy: l.performedBy,
        createdAt: l.createdAt.toISOString(),
      })
    );
  } catch (e) {
    console.warn("getComparisonHistory failed:", e);
    return [];
  }
}

export async function getLatestComparisons(
  limit: number = 8
): Promise<TrendingComparison[]> {
  // Always use mock data for latest — it contains all curated + scheduled content
  // DB comparisons are merged into mock via the pipeline, so mock is the source of truth
  return getMockLatest(limit);
}

export async function getTotalComparisonsCount(): Promise<number> {
  const prisma = getPrismaClient();
  if (!prisma) return 107; // fallback
  try {
    return await prisma.comparison.count({
      where: { status: "published" },
    });
  } catch {
    return 107;
  }
}
