/**
 * Content Refresh Service (DAN-1027)
 *
 * Redirects the content pipeline from net-new generic brand-pair generation
 * toward DEPTH: re-enriching and re-publishing pages that already rank, with
 * fresh 2026 data, richer attributes/FAQs, and updated verdicts.
 *
 * Why: live-site dedup showed the generic "X vs Y" seam is mined out — 55/55 of
 * the top-CPC opportunities were already published, and new generic pages land
 * in positions 21–50 with no incremental value. Refreshing the ~174 pages that
 * already rank is where the marginal SEO return now lives.
 *
 * Affiliate CTAs (DAN-365) are injected at render time in
 * `compare/[slug]/page.tsx` via `enrichEntitiesWithAffiliateLinks`, so
 * regenerating the comparison content here never touches them — they stay live.
 */

import { generateComparison } from "./ai-comparison-generator";
import {
  saveComparison,
  getComparisonsForRefresh,
  markComparisonRefreshed,
  type RefreshCandidate,
} from "./comparison-service";
import { warmCacheForSlug } from "./cache-warming";

export interface RefreshResult {
  refreshed: string[];
  skipped: string[];
  errors: string[];
}

/**
 * Refresh a single comparison in place: regenerate its content with fresh
 * enrichment and re-save (the upsert preserves slug, publishedAt and viewCount),
 * then stamp lastRefreshedAt / nextRefreshAt.
 */
export async function refreshComparison(
  candidate: RefreshCandidate,
  cooldownDays = 90
): Promise<{ success: boolean; error?: string }> {
  try {
    const result = await generateComparison(
      candidate.entityA,
      candidate.entityB,
      candidate.slug
    );
    if (!result.success || !result.comparison) {
      return { success: false, error: result.error || "Generation returned no comparison" };
    }

    // Mark as auto-generated but flag it as a refresh, not a brand-new page.
    result.comparison.metadata.isAutoGenerated = true;

    await saveComparison(result.comparison);
    await markComparisonRefreshed(candidate.slug, cooldownDays);

    // Warm ISR cache so the fresher content is served immediately.
    warmCacheForSlug(candidate.slug).catch(() => {});

    return { success: true };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" };
  }
}

/**
 * Refresh a batch of the stalest already-ranking comparisons.
 *
 * @param limit       how many pages to refresh this run
 * @param onlySlugs   optional explicit slug allow-list (e.g. SEO Specialist's
 *                    174 ranking pages); when omitted we auto-select by ranking
 *                    signal + staleness.
 */
export async function refreshStaleComparisons(
  limit = 15,
  onlySlugs?: string[]
): Promise<RefreshResult> {
  const out: RefreshResult = { refreshed: [], skipped: [], errors: [] };

  const candidates = await getComparisonsForRefresh(limit, { onlySlugs });
  if (candidates.length === 0) return out;

  for (const candidate of candidates) {
    const res = await refreshComparison(candidate);
    if (res.success) {
      out.refreshed.push(candidate.slug);
    } else {
      out.errors.push(`${candidate.slug}: ${res.error}`);
    }
  }

  return out;
}
