import { getRedis } from "@/lib/services/redis";

export interface ChangeLogEntry {
  id: string;
  version: number;
  action: string; // "created" | "updated" | "refreshed" | "reviewed"
  changes: {
    field: string;
    summary: string;
  }[];
  performedBy: string; // "system" | "ai" | "human"
  createdAt: string;
}

const HISTORY_KEY_PREFIX = "history:";

export async function recordChange(params: {
  comparisonId: string;
  comparisonSlug: string;
  action: string;
  changes: Record<string, unknown>;
  performedBy: string;
}): Promise<void> {
  const redis = getRedis();
  if (!redis) {
    console.warn("[version-service] Redis not available, skipping change recording");
    return;
  }

  const key = `${HISTORY_KEY_PREFIX}${params.comparisonSlug}`;

  // Get existing history to determine version number
  const existing = await redis.lrange(key, 0, -1);
  const version = (existing?.length || 0) + 1;

  const entry: ChangeLogEntry = {
    id: `${params.comparisonSlug}-v${version}-${Date.now()}`,
    version,
    action: params.action,
    changes: Object.entries(params.changes).map(([field, value]) => ({
      field,
      summary: typeof value === "string" ? value : JSON.stringify(value),
    })),
    performedBy: params.performedBy,
    createdAt: new Date().toISOString(),
  };

  await redis.rpush(key, JSON.stringify(entry));
}

export async function getComparisonHistory(slug: string): Promise<ChangeLogEntry[]> {
  const redis = getRedis();
  if (!redis) {
    return [];
  }

  const key = `${HISTORY_KEY_PREFIX}${slug}`;
  const rawEntries = await redis.lrange(key, 0, -1);

  if (!rawEntries || rawEntries.length === 0) {
    return [];
  }

  return rawEntries.map((entry) => {
    if (typeof entry === "string") {
      return JSON.parse(entry) as ChangeLogEntry;
    }
    return entry as ChangeLogEntry;
  });
}

/**
 * Generate synthetic history from comparison metadata when no real history exists.
 * This provides a baseline timeline until real change tracking is in place.
 */
export function generateSyntheticHistory(metadata: {
  publishedAt?: string;
  updatedAt: string;
  isAutoGenerated: boolean;
  isHumanReviewed: boolean;
}): ChangeLogEntry[] {
  const entries: ChangeLogEntry[] = [];
  let version = 1;

  // Entry 1: Creation
  const createdAt = metadata.publishedAt || metadata.updatedAt;
  entries.push({
    id: `synthetic-v${version}`,
    version,
    action: "created",
    changes: [
      {
        field: "comparison",
        summary: metadata.isAutoGenerated
          ? "Comparison auto-generated by AI analysis"
          : "Comparison created and published",
      },
    ],
    performedBy: metadata.isAutoGenerated ? "ai" : "system",
    createdAt,
  });
  version++;

  // Entry 2: Human review (if applicable)
  if (metadata.isHumanReviewed) {
    const reviewDate = new Date(createdAt);
    reviewDate.setDate(reviewDate.getDate() + 1);
    const reviewDateStr =
      reviewDate < new Date(metadata.updatedAt)
        ? reviewDate.toISOString()
        : metadata.updatedAt;

    entries.push({
      id: `synthetic-v${version}`,
      version,
      action: "reviewed",
      changes: [
        {
          field: "accuracy",
          summary: "Content reviewed and verified by human editor",
        },
        {
          field: "quality",
          summary: "Facts and comparisons checked for accuracy",
        },
      ],
      performedBy: "human",
      createdAt: reviewDateStr,
    });
    version++;
  }

  // Entry 3: Update (if updatedAt differs from createdAt)
  if (metadata.updatedAt !== createdAt) {
    entries.push({
      id: `synthetic-v${version}`,
      version,
      action: "updated",
      changes: [
        {
          field: "content",
          summary: "Comparison data refreshed with latest information",
        },
      ],
      performedBy: metadata.isAutoGenerated ? "ai" : "system",
      createdAt: metadata.updatedAt,
    });
  }

  return entries;
}
