/**
 * Video Service — Maps comparison slugs to YouTube video data.
 * Reads from the upload-log.json generated by the daily video pipeline.
 */

import fs from "fs";
import path from "path";

interface VideoUpload {
  slug: string;
  title: string;
  entityA: string;
  entityB: string;
  category: string;
  videoFile: string;
  youtubeTitle: string;
  youtubeDescription: string;
  youtubeVideoId: string | null;
  youtubeUrl: string | null;
  uploadedAt: string;
}

interface UploadLog {
  uploads: VideoUpload[];
}

let cachedLog: UploadLog | null = null;
let cacheTime = 0;
const CACHE_TTL = 60_000; // 1 minute

function loadUploadLog(): UploadLog {
  const now = Date.now();
  if (cachedLog && now - cacheTime < CACHE_TTL) return cachedLog;

  const logPath = path.join(process.cwd(), "Videos For Website", "upload-log.json");
  try {
    const raw = fs.readFileSync(logPath, "utf-8");
    cachedLog = JSON.parse(raw);
    cacheTime = now;
    return cachedLog!;
  } catch {
    return { uploads: [] };
  }
}

/**
 * Get the YouTube video ID for a comparison slug.
 * Returns the most recent successful upload for that slug.
 */
export function getYouTubeVideoId(slug: string): string | null {
  const log = loadUploadLog();
  // Find the most recent upload with a YouTube video ID for this slug
  const uploads = log.uploads
    .filter((u) => u.slug === slug && u.youtubeVideoId)
    .sort((a, b) => new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime());

  return uploads[0]?.youtubeVideoId || null;
}

/**
 * Get full video metadata for a comparison slug.
 */
export function getVideoMetadata(slug: string): VideoUpload | null {
  const log = loadUploadLog();
  const uploads = log.uploads
    .filter((u) => u.slug === slug && u.youtubeVideoId)
    .sort((a, b) => new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime());

  return uploads[0] || null;
}

/**
 * Check if a comparison has a video (either YouTube or local MP4).
 */
export function hasVideo(slug: string): boolean {
  // Check YouTube
  if (getYouTubeVideoId(slug)) return true;

  // Check local MP4
  const mp4Path = path.join(process.cwd(), "public", "videos", `${slug}.mp4`);
  try {
    return fs.existsSync(mp4Path);
  } catch {
    return false;
  }
}
