/**
 * Whether a visitor-requested comparison may be indexed.
 *
 * Passing pages are `published` (sitemap + indexable). Failing pages stay
 * `provisional`: live at the permanent URL, robots noindex, absent from the
 * sitemap. Cron and batch saves do not use this — they keep DAN-1886
 * (`archived` for auto-generated pages).
 *
 * The bar is the existing quality gate, the numeric self-contradiction guard,
 * and a minimum-sources/data check defined here:
 *   - at least 2 distinct sources on citationStats
 *   - at least one numeric data point in attributes or key differences
 */

import { assessComparisonQuality } from "@/lib/services/comparison-quality";
import { describeContradictions, findSelfContradictions } from "@/lib/services/numeric-claim-guard";

export const MIN_USER_GENERATION_SOURCES = 2;

export type SaveOrigin = "batch" | "user";
export type PersistedComparisonStatus = "published" | "archived" | "provisional";

export interface PromotionDecision {
  pass: boolean;
  reasons: string[];
  score: number;
}

function sourceCountOf(comparison: {
  citationStats?: { sourceCount?: number; sources?: unknown[] } | null;
}): number {
  const stats = comparison.citationStats;
  if (!stats) return 0;
  if (typeof stats.sourceCount === "number" && Number.isFinite(stats.sourceCount)) {
    return stats.sourceCount;
  }
  return Array.isArray(stats.sources) ? stats.sources.length : 0;
}

function hasNumericDataPoint(comparison: {
  attributes?: unknown;
  keyDifferences?: unknown;
}): boolean {
  const attributes = Array.isArray(comparison.attributes) ? comparison.attributes : [];
  for (const attr of attributes) {
    const values = Array.isArray((attr as { values?: unknown[] })?.values)
      ? (attr as { values: unknown[] }).values
      : [];
    for (const value of values) {
      const row = value as { valueNumber?: unknown; valueText?: unknown };
      if (typeof row?.valueNumber === "number" && Number.isFinite(row.valueNumber)) return true;
      if (/\d/.test(String(row?.valueText ?? ""))) return true;
    }
  }
  const diffs = Array.isArray(comparison.keyDifferences) ? comparison.keyDifferences : [];
  for (const diff of diffs) {
    const row = diff as { entityAValue?: unknown; entityBValue?: unknown; values?: unknown[] };
    const cells = Array.isArray(row.values) ? row.values : [row.entityAValue, row.entityBValue];
    if (cells.some((cell) => /\d/.test(String(cell ?? "")))) return true;
  }
  return false;
}

export function assessUserGenerationPromotion(comparison: {
  keyDifferences?: unknown;
  attributes?: unknown;
  entities?: unknown;
  verdict?: string | null;
  shortAnswer?: string | null;
  citationStats?: { sourceCount?: number; sources?: unknown[] } | null;
  faqs?: { question?: string; answer?: string }[] | null;
  quickAnswer?: { tldr?: string | null; keyFact?: string | null } | null;
}): PromotionDecision {
  const quality = assessComparisonQuality(comparison);
  const reasons = [...quality.reasons];
  const contradictions = findSelfContradictions(comparison);
  if (contradictions.length > 0) {
    reasons.push(`self-contradictory numbers (${describeContradictions(contradictions)})`);
  }
  const sources = sourceCountOf(comparison);
  if (sources < MIN_USER_GENERATION_SOURCES) {
    reasons.push(`only ${sources} sources (need ${MIN_USER_GENERATION_SOURCES})`);
  }
  if (!hasNumericDataPoint(comparison)) {
    reasons.push("no numeric data points");
  }
  return { pass: reasons.length === 0, reasons, score: quality.score };
}

export function decidePersistedStatus(
  metadata: { isAutoGenerated?: boolean; isHumanReviewed?: boolean },
  origin: SaveOrigin,
  promotionPass: boolean,
): PersistedComparisonStatus {
  if (origin === "user") {
    return promotionPass ? "published" : "provisional";
  }
  // DAN-1886 stays in force for cron, batch, and admin writes.
  if (metadata.isAutoGenerated && !metadata.isHumanReviewed) return "archived";
  return "published";
}
