/**
 * AI analysis is labeled as analysis, not as Daniel's reviewed work,
 * unless the slug is on HUMAN_REVIEWED_SLUGS.
 */
import { afterEach, beforeAll, describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import type { ComparisonPageData } from "@/types";
import { ExpertAnalysis } from "@/components/comparison/ExpertAnalysis";
import { ComparisonHero } from "@/components/comparison/ComparisonHero";
import { assembleCompareJsonLd } from "@/lib/seo/compare-jsonld";
import { HUMAN_REVIEWED_SLUGS } from "@/lib/editorial/human-reviewed";
import { SITE_URL } from "@/lib/utils/constants";

beforeAll(() => {
  const view = window as Window & {
    matchMedia: typeof window.matchMedia;
    IntersectionObserver: typeof IntersectionObserver;
  };
  if (!view.matchMedia) {
    view.matchMedia = ((query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: () => {},
      removeListener: () => {},
      addEventListener: () => {},
      removeEventListener: () => {},
      dispatchEvent: () => false,
    })) as unknown as typeof window.matchMedia;
  }
  if (!view.IntersectionObserver) {
    class Observer {
      observe() {}
      unobserve() {}
      disconnect() {}
    }
    view.IntersectionObserver = Observer as unknown as typeof IntersectionObserver;
  }
});

afterEach(() => {
  HUMAN_REVIEWED_SLUGS.length = 0;
});

function page(slug: string): ComparisonPageData {
  return {
    id: "cmp-1",
    slug,
    title: "Alpha Widget vs Beta Widget",
    shortAnswer: "Alpha Widget is the better pick for most people.",
    verdict: "Alpha Widget",
    keyDifferences: [],
    category: "products",
    entities: [
      {
        id: "a",
        slug: "alpha-widget",
        name: "Alpha Widget",
        shortDesc: "A widget",
        imageUrl: null,
        entityType: "product",
        position: 0,
        pros: ["Light"],
        cons: ["Slow"],
        bestFor: "Everyday use",
      },
      {
        id: "b",
        slug: "beta-widget",
        name: "Beta Widget",
        shortDesc: "Another widget",
        imageUrl: null,
        entityType: "product",
        position: 1,
        pros: ["Fast"],
        cons: ["Heavy"],
        bestFor: "Power users",
      },
    ],
    attributes: [],
    faqs: [],
    relatedComparisons: [],
    relatedBlogPosts: [],
    expertAnalysis: "First paragraph of the analysis.\n\nSecond paragraph with a sourced figure.",
    metadata: {
      metaTitle: "Alpha Widget vs Beta Widget",
      metaDescription: "Compare the two widgets.",
      publishedAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-06-01T00:00:00.000Z",
      isAutoGenerated: true,
      // Scripts set this automatically. Labeling must ignore it.
      isHumanReviewed: true,
      viewCount: 0,
      status: "published",
    },
    schemaMarkup: {
      "@context": "https://schema.org",
      "@type": "Article",
      headline: "Alpha Widget vs Beta Widget",
      author: {
        "@type": "Person",
        "@id": `${SITE_URL}/authors/daniel-rozin#person`,
        name: "Daniel Rozin",
        url: `${SITE_URL}/authors/daniel-rozin`,
      },
      reviewedBy: { "@type": "Person", name: "Daniel Rozin" },
      lastReviewed: "2026-06-01",
      publisher: {
        "@type": "Organization",
        name: "A Versus B",
        founder: {
          "@type": "Person",
          name: "Daniel Rozin",
          url: `${SITE_URL}/authors/daniel-rozin`,
        },
      },
    },
  };
}

function articleAuthor(document: Record<string, unknown>): unknown {
  return (document as { author?: unknown }).author;
}

describe("analysis labeling", () => {
  it("shows Analysis, the AI disclosure, and no Daniel byline or reviewed schema by default", () => {
    const comparison = page("alpha-widget-vs-beta-widget");
    render(
      <>
        <ComparisonHero comparison={comparison} />
        <ExpertAnalysis
          analysis={comparison.expertAnalysis!}
          slug={comparison.slug}
          entityAName="Alpha Widget"
          entityBName="Beta Widget"
          updatedAt={comparison.metadata.updatedAt}
        />
      </>,
    );

    expect(screen.getByRole("heading", { name: "Analysis: Alpha Widget vs Beta Widget" })).toBeInTheDocument();
    expect(screen.getByText(/Drafted with AI from web research/)).toBeInTheDocument();
    const research = screen.getByRole("link", { name: "How we research" });
    expect(research).toHaveAttribute("href", `${SITE_URL}/how-we-write-verdicts`);
    expect(screen.queryByText(/Daniel Rozin/)).not.toBeInTheDocument();
    expect(screen.queryByText(/Human reviewed/)).not.toBeInTheDocument();
    expect(screen.getByText("A Versus B")).toBeInTheDocument();

    const stored = assembleCompareJsonLd({
      comparison,
      voteData: null,
      videoNode: null,
      fallbackDescription: comparison.shortAnswer!,
    });
    const storedJson = JSON.stringify(stored.document);
    expect(articleAuthor(stored.document)).toMatchObject({
      "@type": "Organization",
      name: "A Versus B",
    });
    expect(storedJson).not.toContain("reviewedBy");
    expect(storedJson).not.toContain("lastReviewed");
    expect(storedJson).not.toContain("isHumanReviewed");
    const storedDoc = stored.document as {
      publisher?: { founder?: { name?: string } };
    };
    expect(storedDoc.publisher?.founder?.name).toBe("Daniel Rozin");

    const generated = assembleCompareJsonLd({
      comparison: { ...comparison, schemaMarkup: undefined },
      voteData: null,
      videoNode: null,
      fallbackDescription: comparison.shortAnswer!,
    });
    const generatedJson = JSON.stringify(generated.document);
    expect(generatedJson).not.toContain("Daniel Rozin");
    expect(generatedJson).not.toContain("reviewedBy");
    expect(generatedJson).not.toContain("lastReviewed");
    const article = (generated.document["@graph"] as Array<Record<string, unknown>>).find(
      (node) => node["@type"] === "Article",
    );
    expect(article?.author).toMatchObject({ "@type": "Organization", name: "A Versus B" });
  });

  it("shows Daniel's byline and reviewed schema when the slug is allowlisted", () => {
    const slug = "alpha-widget-vs-beta-widget";
    HUMAN_REVIEWED_SLUGS.push(slug);
    const comparison = page(slug);
    // Stored markup would still name Daniel; the allowlist keeps that claim.
    comparison.schemaMarkup = undefined;

    render(
      <ExpertAnalysis
        analysis={comparison.expertAnalysis!}
        slug={slug}
        entityAName="Alpha Widget"
        entityBName="Beta Widget"
        updatedAt={comparison.metadata.updatedAt}
      />,
    );

    expect(screen.getByRole("heading", { name: "Analysis: Alpha Widget vs Beta Widget" })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Daniel Rozin, Editor-in-Chief" })).toHaveAttribute(
      "href",
      "/authors/daniel-rozin",
    );
    expect(screen.getByText("Human reviewed")).toBeInTheDocument();

    const assembled = assembleCompareJsonLd({
      comparison,
      voteData: null,
      videoNode: null,
      fallbackDescription: comparison.shortAnswer!,
    });
    const json = JSON.stringify(assembled.document);
    expect(json).toContain("Daniel Rozin");
    expect(json).toContain("reviewedBy");
    expect(json).toContain("lastReviewed");
    const article = JSON.parse(json)["@graph"].find(
      (node: { "@type"?: string }) => node["@type"] === "Article",
    );
    const authors = Array.isArray(article.author) ? article.author : [article.author];
    expect(authors.some((author: { name?: string }) => author.name === "Daniel Rozin")).toBe(true);
    expect(authors.some((author: { "@type"?: string; name?: string }) => author["@type"] === "Organization")).toBe(true);
  });
});
