// DAN-2065 — /compare/* must have a boundary.
//
// Before this, `/compare/{anything}` returned HTTP 200. getStaticProps had no
// "does this page exist?" gate: an unknown slug fell through to an on-demand AI
// generator (DAN-1146) that generated a full comparison, PERSISTED it, and
// rendered it 200; if generation failed it still returned a `kind:"dynamic"`
// client shell — also 200. So banana-vs-stapler rendered a page, Google had an
// unbounded soft-404 crawl space, and 2,859 crawler-minted rows accumulated in
// prod.
//
// The gate is now: render iff there is a DB row with status "published" and >=2
// entities — the same predicate the sitemap uses. These tests drive the real
// getStaticProps and assert that everything outside the published set 404s.

import { describe, it, expect, vi, beforeEach } from 'vitest'

const getComparisonBySlug = vi.fn()
const isComparisonDbConfigured = vi.fn()
const isComparisonDbReachable = vi.fn()

vi.mock('@/lib/services/comparison-service', () => ({
  getComparisonBySlug: (slug: string) => getComparisonBySlug(slug),
  getTrendingComparisons: vi.fn().mockResolvedValue([]),
  isComparisonDbConfigured: () => isComparisonDbConfigured(),
  isComparisonDbReachable: () => isComparisonDbReachable(),
}))

// The generator must be unreachable from a page request. Any call here is the
// bug reappearing: an inbound URL minting content.
const generateComparison = vi.fn()
vi.mock('@/lib/services/ai-comparison-generator', () => ({
  generateComparison: (...a: unknown[]) => generateComparison(...a),
  generateMultiComparison: (...a: unknown[]) => generateComparison(...a),
}))

import { getStaticProps } from '@/pages/compare/[slug]'

type Ctx = Parameters<typeof getStaticProps>[0]
const run = (slug: string) => getStaticProps({ params: { slug } } as unknown as Ctx)

const comparison = (slug: string, status: string) => ({
  id: `id-${slug}`,
  slug,
  title: slug,
  category: 'software',
  shortAnswer: 'A short answer.',
  verdict: 'A verdict.',
  faqs: [],
  keyDifferences: [],
  attributes: [],
  relatedComparisons: [],
  relatedBlogPosts: [],
  entities: [
    { id: 'a', name: 'A', slug: 'a', pros: [], cons: [] },
    { id: 'b', name: 'B', slug: 'b', pros: [], cons: [] },
  ],
  metadata: { status, metaTitle: 'A vs B', metaDescription: 'A vs B compared.' },
})

// A bundled mock fixture: same shape as a DB-backed comparison, but with no
// `status` — fixtures are not rows, which is exactly why the gate must judge them.
const mockFixture = (slug: string) => {
  const c = comparison(slug, 'published') as Record<string, unknown>
  c.metadata = {
    metaTitle: 'A vs B',
    metaDescription: 'A vs B compared.',
    publishedAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    isAutoGenerated: false,
    isHumanReviewed: true,
    viewCount: 1,
  }
  return c
}

beforeEach(() => {
  getComparisonBySlug.mockReset()
  generateComparison.mockReset()
  isComparisonDbConfigured.mockReset()
  isComparisonDbReachable.mockReset()
  getComparisonBySlug.mockResolvedValue(null)
  generateComparison.mockRejectedValue(new Error('generator must not run on a page request'))
  // Default: prod-like — a real DB, and it is answering.
  isComparisonDbConfigured.mockReturnValue(true)
  isComparisonDbReachable.mockResolvedValue(true)
})

describe('DAN-2065: /compare/[slug] renders only published comparisons', () => {
  it('404s an invented slug instead of generating a page for it', async () => {
    const result = await run('banana-vs-stapler')

    expect(result).toMatchObject({ notFound: true })
    // The critical assertion: no content was minted for a slug someone made up.
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('404s a slug that exists in the DB but was never published', async () => {
    // chatgpt-vs-google / copilot-vs-stack-overflow were exactly this: rows the
    // old SSR fallback minted (saved as "archived"), still served 200.
    for (const status of ['archived', 'draft', 'review']) {
      getComparisonBySlug.mockResolvedValue(comparison('chatgpt-vs-google', status))

      expect(await run('chatgpt-vs-google')).toMatchObject({ notFound: true })
    }
  })

  it('404s a published-but-corrupt row with fewer than 2 entities', async () => {
    // These rows hard-500'd the SSR layout before (DAN-1201/DAN-1262).
    getComparisonBySlug.mockResolvedValue({
      ...comparison('a-vs-b', 'published'),
      entities: [{ id: 'a', name: 'A', slug: 'a' }],
    })

    expect(await run('a-vs-b')).toMatchObject({ notFound: true })
  })

  it('still renders a published comparison', async () => {
    getComparisonBySlug.mockResolvedValue(comparison('clickup-vs-notion', 'published'))

    const result = await run('clickup-vs-notion')

    expect(result).not.toMatchObject({ notFound: true })
    expect(result).toHaveProperty('props')
  })

  it('keeps folding a non-canonical B-vs-A ordering into its published canonical (DAN-1265)', async () => {
    getComparisonBySlug.mockImplementation(async (slug: string) =>
      slug === 'clickup-vs-notion' ? comparison(slug, 'published') : null
    )

    expect(await run('notion-vs-clickup')).toMatchObject({
      redirect: { destination: '/compare/clickup-vs-notion', permanent: true },
    })
  })

  it('404s a reordering whose canonical target is not published, rather than 308ing to a dead URL', async () => {
    getComparisonBySlug.mockResolvedValue(null)

    expect(await run('notion-vs-clickup')).toMatchObject({ notFound: true })
  })

  it('404s a mock-fixture row in prod — fixtures are not the catalog', async () => {
    // getComparisonBySlug degrades to bundled fixtures on a DB miss. ~30 of them
    // (f-35-vs-su-57, medicaid-vs-medicare, …) are archived or absent from the DB
    // yet were serving 200s. Fixtures carry no status, so the gate rejects them
    // wherever a real DB exists.
    getComparisonBySlug.mockResolvedValue(mockFixture('f-35-vs-su-57'))

    expect(await run('f-35-vs-su-57')).toMatchObject({ notFound: true })
  })

  it('still renders fixtures where no database is configured (local dev / DB-less CI)', async () => {
    isComparisonDbConfigured.mockReturnValue(false)
    getComparisonBySlug.mockResolvedValue(mockFixture('f-35-vs-su-57'))

    expect(await run('f-35-vs-su-57')).toHaveProperty('props')
  })

  it('throws rather than 404ing when the DB is unreachable, so ISR keeps the live page', async () => {
    // getStaticProps also runs on ISR revalidation. If an outage (every lookup
    // returns empty) produced a notFound, all 491 published comparisons would be
    // replaced by 404s in the ISR cache. Throwing keeps the last good render.
    isComparisonDbReachable.mockResolvedValue(false)
    getComparisonBySlug.mockResolvedValue(null)

    await expect(run('clickup-vs-notion')).rejects.toThrow(/unreachable/)
  })
})
