// DAN-2065 — /compare/* must have a boundary.
//
// Before this, `/compare/{anything}` returned HTTP 200. getStaticProps had no
// "does this page exist?" gate: an unknown slug fell through to an on-demand AI
// generator (DAN-1146) that generated a full comparison, PERSISTED it, and
// rendered it 200; if generation failed it still returned a `kind:"dynamic"`
// client shell — also 200. So banana-vs-stapler rendered a page, Google had an
// unbounded soft-404 crawl space, and 2,859 crawler-minted rows accumulated in
// prod.
//
// The gate is now: render iff there is a DB row with status "published" and >=2
// entities — the same predicate the sitemap uses. These tests drive the real
// getStaticProps and assert that everything outside the published set 404s.

import { describe, it, expect, vi, beforeEach } from 'vitest'

const getComparisonBySlug = vi.fn()
const isComparisonDbConfigured = vi.fn()
const isComparisonDbReachable = vi.fn()

vi.mock('@/lib/services/comparison-service', () => ({
  getComparisonBySlug: (slug: string) => getComparisonBySlug(slug),
  getTrendingComparisons: vi.fn().mockResolvedValue([]),
  isComparisonDbConfigured: () => isComparisonDbConfigured(),
  isComparisonDbReachable: () => isComparisonDbReachable(),
  // ROO-29: getStaticProps → buildCompareNextChips → filterLiveCompareSlugs
  resolveCanonicalComparisonSlugs: async (slugs: string[]) => new Set(slugs),
}))

// The generator must be unreachable from a page request. Any call here is the
// bug reappearing: an inbound URL minting content.
const generateComparison = vi.fn()
vi.mock('@/lib/services/ai-comparison-generator', () => ({
  generateComparison: (...a: unknown[]) => generateComparison(...a),
  generateMultiComparison: (...a: unknown[]) => generateComparison(...a),
}))

import { getStaticProps } from '@/pages/compare/[slug]'

type Ctx = Parameters<typeof getStaticProps>[0]
const run = (slug: string) => getStaticProps({ params: { slug } } as unknown as Ctx)

const comparison = (slug: string, status: string) => ({
  id: `id-${slug}`,
  slug,
  title: slug,
  category: 'software',
  shortAnswer: 'A short answer.',
  verdict: 'A verdict.',
  faqs: [],
  keyDifferences: [],
  attributes: [],
  relatedComparisons: [],
  relatedBlogPosts: [],
  entities: [
    { id: 'a', name: 'A', slug: 'a', pros: [], cons: [] },
    { id: 'b', name: 'B', slug: 'b', pros: [], cons: [] },
  ],
  metadata: { status, metaTitle: 'A vs B', metaDescription: 'A vs B compared.' },
})

// A bundled mock fixture: same shape as a DB-backed comparison, but with no
// `status` — fixtures are not rows, which is exactly why the gate must judge them.
const mockFixture = (slug: string) => {
  const c = comparison(slug, 'published') as Record<string, unknown>
  c.metadata = {
    metaTitle: 'A vs B',
    metaDescription: 'A vs B compared.',
    publishedAt: '2024-01-15T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    isAutoGenerated: false,
    isHumanReviewed: true,
    viewCount: 1,
  }
  return c
}

beforeEach(() => {
  getComparisonBySlug.mockReset()
  generateComparison.mockReset()
  isComparisonDbConfigured.mockReset()
  isComparisonDbReachable.mockReset()
  getComparisonBySlug.mockResolvedValue(null)
  generateComparison.mockRejectedValue(new Error('generator must not run on a page request'))
  // Default: prod-like — a real DB, and it is answering.
  isComparisonDbConfigured.mockReturnValue(true)
  isComparisonDbReachable.mockResolvedValue(true)
})

describe('DAN-2065: /compare/[slug] renders only published comparisons', () => {
  it('404s an invented slug instead of generating a page for it', async () => {
    const result = await run('banana-vs-stapler')

    expect(result).toMatchObject({ notFound: true })
    // The critical assertion: no content was minted for a slug someone made up.
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('404s a slug that exists in the DB but was never published', async () => {
    // chatgpt-vs-google / copilot-vs-stack-overflow were exactly this: rows the
    // old SSR fallback minted (saved as "archived"), still served 200.
    for (const status of ['archived', 'draft', 'review']) {
      getComparisonBySlug.mockResolvedValue(comparison('chatgpt-vs-google', status))

      expect(await run('chatgpt-vs-google')).toMatchObject({ notFound: true })
    }
  })

  it('404s a published-but-corrupt row with fewer than 2 entities', async () => {
    // These rows hard-500'd the SSR layout before (DAN-1201/DAN-1262).
    getComparisonBySlug.mockResolvedValue({
      ...comparison('a-vs-b', 'published'),
      entities: [{ id: 'a', name: 'A', slug: 'a' }],
    })

    expect(await run('a-vs-b')).toMatchObject({ notFound: true })
  })

  it('still renders a published comparison', async () => {
    getComparisonBySlug.mockResolvedValue(comparison('clickup-vs-notion', 'published'))

    const result = await run('clickup-vs-notion')

    expect(result).not.toMatchObject({ notFound: true })
    expect(result).toHaveProperty('props')
  })

  it('keeps folding a non-canonical B-vs-A ordering into its published canonical (DAN-1265)', async () => {
    getComparisonBySlug.mockImplementation(async (slug: string) =>
      slug === 'clickup-vs-notion' ? comparison(slug, 'published') : null
    )

    expect(await run('notion-vs-clickup')).toMatchObject({
      // DAN-2518: explicit 301 rather than `permanent: true` (Next's 308).
      redirect: { destination: '/compare/clickup-vs-notion', statusCode: 301 },
    })
  })

  it('301s a mapped ordering even when the DB row is missing, and 404s an unmapped reordering', async () => {
    // notion-vs-clickup is an explicit edge consolidation, not an unknown slug:
    // DAN-1265's ordering map and DAN-2518's batch-archive map both fold it
    // into clickup-vs-notion. getStaticProps applies getConsolidatedCompareSlug
    // before the published-row gate (the same map next.config redirects()
    // emits), so a missing DB row still 301s. That redirect is intentional —
    // the edge map survives even if the archived source row is later deleted.
    getComparisonBySlug.mockResolvedValue(null)

    expect(await run('notion-vs-clickup')).toMatchObject({
      redirect: { destination: '/compare/clickup-vs-notion', statusCode: 301 },
    })

    // stapler-vs-banana is not in the edge map, and banana-vs-stapler is not
    // live. Stay on the requested URL. A 301 to the sorted slug would 404.
    expect(await run('stapler-vs-banana')).toMatchObject({ notFound: true })
    expect(await run('stapler-vs-banana')).not.toHaveProperty('redirect')
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('404s a missing pair at the requested URL instead of 301ing to a dead sorted slug', async () => {
    // Invented pairs. The NBA slugs this used to list are live pages now,
    // and their reversed forms 301 to those pages.
    for (const slug of [
      'stapler-vs-banana',
      'banana-vs-stapler',
      'zzz-test-a-vs-zzz-test-b',
      'zzz-test-b-vs-zzz-test-a',
    ]) {
      const result = await run(slug)
      expect(result, slug).toMatchObject({ notFound: true })
      expect(result, slug).not.toHaveProperty('redirect')
    }
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('301s to the sorted slug only when that page is live', async () => {
    getComparisonBySlug.mockImplementation(async (slug: string) =>
      slug === 'banana-vs-stapler' ? comparison(slug, 'published') : null
    )

    expect(await run('stapler-vs-banana')).toMatchObject({
      redirect: { destination: '/compare/banana-vs-stapler', statusCode: 301 },
    })
    const live = await run('banana-vs-stapler')
    expect(live).toHaveProperty('props')
    expect(live).not.toHaveProperty('redirect')
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('keeps reversed-slug 301s that land on a live page', async () => {
    // Edge map. The target does not have to be in this lookup.
    expect(await run('kobe-vs-lebron')).toMatchObject({
      redirect: { destination: '/compare/kobe-bryant-vs-lebron-james', statusCode: 301 },
    })

    getComparisonBySlug.mockImplementation(async (slug: string) => {
      if (
        slug === 'knicks-vs-76ers' ||
        slug === 'shai-gilgeous-alexander-vs-victor-wembanyama' ||
        slug === 'flagg-vs-wembanyama' ||
        slug === 'oklahoma-city-thunder-vs-spurs' ||
        slug === 'knicks-vs-spurs'
      ) {
        return comparison(slug, 'published')
      }
      return null
    })

    expect(await run('76ers-vs-knicks')).toMatchObject({
      redirect: { destination: '/compare/knicks-vs-76ers', statusCode: 301 },
    })
    expect(await run('victor-wembanyama-vs-shai-gilgeous-alexander')).toMatchObject({
      redirect: { destination: '/compare/shai-gilgeous-alexander-vs-victor-wembanyama', statusCode: 301 },
    })
    expect(await run('wembanyama-vs-flagg')).toMatchObject({
      redirect: { destination: '/compare/flagg-vs-wembanyama', statusCode: 301 },
    })
    expect(await run('spurs-vs-oklahoma-city-thunder')).toMatchObject({
      redirect: { destination: '/compare/oklahoma-city-thunder-vs-spurs', statusCode: 301 },
    })
    expect(await run('spurs-vs-knicks')).toMatchObject({
      redirect: { destination: '/compare/knicks-vs-spurs', statusCode: 301 },
    })
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('treats a provisional auto row with no visitor table as missing', async () => {
    getComparisonBySlug.mockResolvedValue({
      ...comparison('canoe-vs-kayak', 'provisional'),
      metadata: {
        status: 'provisional',
        isAutoGenerated: true,
        visitorTableSaved: false,
        metaTitle: 'Canoe vs Kayak',
        metaDescription: 'Canoe vs Kayak',
      },
    })
    const result = await run('canoe-vs-kayak')
    expect(result).toMatchObject({ notFound: true, revalidate: 30 })
  })

  it('renders a provisional comparison and keeps archived rows as 404s', async () => {
    getComparisonBySlug.mockResolvedValue(comparison('clickup-vs-notion', 'provisional'))
    const result = await run('clickup-vs-notion')
    expect(result).toHaveProperty('props')
    if (!('props' in result)) throw new Error('expected props')
    expect(result.props.meta.indexable).toBe(false)
  })

  it('renders a published non-alphabetical slug and does not loop its reverse', async () => {
    getComparisonBySlug.mockImplementation(async (slug: string) =>
      slug === 'marvel-vs-dc' ? comparison(slug, 'published') : null
    )

    const live = await run('marvel-vs-dc')
    expect(live).toHaveProperty('props')
    expect(live).not.toHaveProperty('redirect')

    expect(await run('dc-vs-marvel')).toMatchObject({
      redirect: { destination: '/compare/marvel-vs-dc', statusCode: 301 },
    })
  })

  it('keeps alias-shaped published pages and only redirects to that live slug', async () => {
    getComparisonBySlug.mockImplementation(async (slug: string) =>
      slug === 'usa-vs-china' || slug === 'chrome-vs-firefox' || slug === 'disney-plus-vs-hulu'
        ? comparison(slug, 'published')
        : null
    )

    for (const slug of ['usa-vs-china', 'chrome-vs-firefox', 'disney-plus-vs-hulu']) {
      const result = await run(slug)
      expect(result, slug).toHaveProperty('props')
      expect(result, slug).not.toHaveProperty('redirect')
    }

    expect(await run('china-vs-united-states')).toMatchObject({
      redirect: { destination: '/compare/usa-vs-china', statusCode: 301 },
    })
    expect(await run('firefox-vs-google-chrome')).toMatchObject({
      redirect: { destination: '/compare/chrome-vs-firefox', statusCode: 301 },
    })
    expect(await run('disney-vs-hulu')).toMatchObject({
      redirect: { destination: '/compare/disney-plus-vs-hulu', statusCode: 301 },
    })
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('sends a missing canonical URL to the live reverse ordering', async () => {
    getComparisonBySlug.mockImplementation(async (slug: string) =>
      slug === 'stapler-vs-banana' ? comparison(slug, 'provisional') : null
    )
    expect(await run('banana-vs-stapler')).toMatchObject({
      redirect: { destination: '/compare/stapler-vs-banana', statusCode: 301 },
    })
    expect(generateComparison).not.toHaveBeenCalled()
  })

  it('404s a mock-fixture row in prod — fixtures are not the catalog', async () => {
    // getComparisonBySlug degrades to bundled fixtures on a DB miss. ~30 of them
    // (f-35-vs-su-57, medicaid-vs-medicare, …) are archived or absent from the DB
    // yet were serving 200s. Fixtures carry no status, so the gate rejects them
    // wherever a real DB exists.
    getComparisonBySlug.mockResolvedValue(mockFixture('f-35-vs-su-57'))

    expect(await run('f-35-vs-su-57')).toMatchObject({ notFound: true })
  })

  it('still renders fixtures where no database is configured (local dev / DB-less CI)', async () => {
    isComparisonDbConfigured.mockReturnValue(false)
    getComparisonBySlug.mockResolvedValue(mockFixture('f-35-vs-su-57'))

    expect(await run('f-35-vs-su-57')).toHaveProperty('props')
  })

  it('throws rather than 404ing when the DB is unreachable, so ISR keeps the live page', async () => {
    // getStaticProps also runs on ISR revalidation. If an outage (every lookup
    // returns empty) produced a notFound, all 491 published comparisons would be
    // replaced by 404s in the ISR cache. Throwing keeps the last good render.
    isComparisonDbReachable.mockResolvedValue(false)
    getComparisonBySlug.mockResolvedValue(null)

    await expect(run('clickup-vs-notion')).rejects.toThrow(/unreachable/)
  })
})
