/**
 * DAN-1265 — A-vs-B / B-vs-A ordering-duplicate consolidations (GENERATED).
 *
 * aversusb.net generated a /compare/ page for BOTH entity orderings of many
 * comparisons (e.g. \`roomba-vs-roborock\` AND \`roborock-vs-roomba\`), splitting
 * link equity and confusing Google's canonical selection across the footprint.
 *
 * A read-only audit (scripts/dan-1265-audit-duplicate-orderings.ts, run against
 * prod 2026-06-21) found 166 duplicate ordering clusters out of 2093
 * /compare/ rows. For each cluster the SURVIVOR is the page with real traffic
 * (viewCount); when both sides have 0 views the alphabetically-sorted slug wins
 * (deterministic, matches the going-forward generation order in comparisonSlug()).
 *
 * Map: retired slug -> survivor slug. Consumed by compare-redirects.ts which emits
 * permanent (301/308) edge redirects via next.config.ts redirects(). The retired
 * DB rows are set status="archived" so they drop out of the sitemap; the redirect
 * survives even if the row is later deleted.
 *
 * Regenerate: npx dotenv -e .env.<prod> -- npx tsx scripts/dan-1265-audit-duplicate-orderings.ts
 * Do not hand-edit — add one-off / alias consolidations to compare-redirects.ts instead.
 */

export const ORDERING_CONSOLIDATIONS: Record<string, string> = {
  "dashlane-vs-1password": "1password-vs-dashlane",
  "brevo-vs-activecampaign": "activecampaign-vs-brevo",
  "klaviyo-vs-activecampaign": "activecampaign-vs-klaviyo",
  "calendly-vs-acuity-scheduling": "acuity-scheduling-vs-calendly",
  "figma-vs-adobe-xd": "adobe-xd-vs-figma",
  "trader-joes-vs-aldi": "aldi-vs-trader-joes",
  "shein-vs-amazon-haul": "amazon-haul-vs-shein",
  "shopify-vs-amazon": "amazon-vs-shopify",
  "temu-vs-amazon": "amazon-vs-temu",
  "iphone-vs-android": "android-vs-iphone",
  "vue-vs-angular": "angular-vs-vue",
  "openai-vs-anthropic": "anthropic-vs-openai",
  "spotify-vs-apple-music": "apple-music-vs-spotify",
  "youtube-music-vs-apple-music": "apple-music-vs-youtube-music",
  "disney-plus-vs-apple-tv-plus": "apple-tv-plus-vs-disney-plus",
  "netflix-vs-apple-tv-plus": "apple-tv-plus-vs-netflix",
  "google-vs-apple": "apple-vs-google",
  "microsoft-vs-apple": "apple-vs-microsoft",
  "clickup-vs-asana": "asana-vs-clickup",
  "monday-vs-asana": "asana-vs-monday",
  "notion-vs-asana": "asana-vs-notion",
  "lever-vs-ashby": "ashby-vs-lever",
  "lululemon-vs-athleta": "athleta-vs-lululemon",
  "bmw-7-series-vs-audi-a8": "audi-a8-vs-bmw-7-series",
  "bmw-vs-audi": "audi-vs-bmw",
  "azure-vs-aws": "aws-vs-azure",
  "greenhouse-vs-bamboohr": "bamboohr-vs-greenhouse",
  "chase-vs-bank-of-america": "bank-of-america-vs-chase",
  "shopify-vs-bigcommerce": "bigcommerce-vs-shopify",
  "coinbase-vs-binance": "binance-vs-coinbase",
  "mcafee-vs-bitdefender": "bitdefender-vs-mcafee",
  "norton-vs-bitdefender": "bitdefender-vs-norton",
  "mercedes-c-class-vs-bmw-3-series": "bmw-3-series-vs-mercedes-c-class",
  "mercedes-s-class-vs-bmw-7-series": "bmw-7-series-vs-mercedes-s-class",
  "genesis-vs-bmw": "bmw-vs-genesis",
  "mercedes-gle-vs-bmw-x5": "bmw-x5-vs-mercedes-gle",
  "khan-academy-vs-brilliant": "brilliant-vs-khan-academy",
  "rollbar-vs-bugsnag": "bugsnag-vs-rollbar",
  "chase-vs-capital-one": "capital-one-vs-chase",
  "prefect-vs-celery": "celery-vs-prefect",
  "fidelity-vs-charles-schwab": "charles-schwab-vs-fidelity",
  "claude-vs-chatgpt": "chatgpt-vs-claude",
  "copilot-vs-chatgpt": "chatgpt-vs-copilot",
  "gemini-vs-chatgpt": "chatgpt-vs-gemini",
  "perplexity-vs-chatgpt": "chatgpt-vs-perplexity",
  "ford-f-150-vs-chevy-silverado": "chevy-silverado-vs-ford-f-150",
  "mcdonalds-vs-chick-fil-a": "chick-fil-a-vs-mcdonalds",
  "popeyes-vs-chick-fil-a": "chick-fil-a-vs-popeyes",
  "us-vs-china-gdp": "china-gdp-vs-us",
  "india-vs-china": "china-vs-india",
  "us-economy-vs-chinese-economy": "chinese-economy-vs-us-economy",
  "gemini-vs-claude": "claude-vs-gemini",
  "perplexity-vs-claude": "claude-vs-perplexity",
  "druid-vs-clickhouse": "clickhouse-vs-druid",
  "duckdb-vs-clickhouse": "clickhouse-vs-duckdb",
  "pinot-vs-clickhouse": "clickhouse-vs-pinot",
  "monday-vs-clickup": "clickup-vs-monday",
  "notion-vs-clickup": "clickup-vs-notion",
  "planetscale-vs-cockroachdb": "cockroachdb-vs-planetscale",
  "postgresql-vs-cockroachdb": "cockroachdb-vs-postgresql",
  "notion-vs-coda": "coda-vs-notion",
  "mailchimp-vs-convertkit": "convertkit-vs-mailchimp",
  "walmart-vs-costco": "costco-vs-walmart",
  "github-copilot-vs-cursor": "cursor-vs-github-copilot",
  "windsurf-vs-cursor": "cursor-vs-windsurf",
  "prefect-vs-dagster": "dagster-vs-prefect",
  "midjourney-vs-dall-e": "dall-e-vs-midjourney",
  "prefect-vs-dbt": "dbt-vs-prefect",
  "macbook-air-vs-dell-xps-13": "dell-xps-13-vs-macbook-air",
  "slack-vs-discord": "discord-vs-slack",
  "hulu-vs-disney-plus": "disney-plus-vs-hulu",
  "peacock-vs-disney-plus": "disney-plus-vs-peacock",
  "netflix-vs-disney": "disney-vs-netflix",
  "grubhub-vs-doordash": "doordash-vs-grubhub",
  "instacart-vs-doordash": "doordash-vs-instacart",
  "pinot-vs-druid": "druid-vs-pinot",
  "safari-vs-edge": "edge-vs-safari",
  "shopify-vs-etsy": "etsy-vs-shopify",
  "notion-vs-evernote": "evernote-vs-notion",
  "nordvpn-vs-expressvpn": "expressvpn-vs-nordvpn",
  "f-35-vs-f-22": "f-22-vs-f-35",
  "robinhood-vs-fidelity": "fidelity-vs-robinhood",
  "vanguard-vs-fidelity": "fidelity-vs-vanguard",
  "mongodb-vs-firebase": "firebase-vs-mongodb",
  "safari-vs-firefox": "firefox-vs-safari",
  "kafka-vs-flink": "flink-vs-kafka",
  "squarespace-vs-framer": "framer-vs-squarespace",
  "quickbooks-vs-freshbooks": "freshbooks-vs-quickbooks",
  "wave-vs-freshbooks": "freshbooks-vs-wave",
  "microsoft-clarity-vs-fullstory": "fullstory-vs-microsoft-clarity",
  "mixpanel-vs-fullstory": "fullstory-vs-mixpanel",
  "java-vs-golang": "golang-vs-java",
  "python-vs-golang": "golang-vs-python",
  "matomo-vs-google-analytics": "google-analytics-vs-matomo",
  "mixpanel-vs-google-analytics": "google-analytics-vs-mixpanel",
  "plausible-vs-google-analytics": "google-analytics-vs-plausible",
  "webex-vs-google-meet": "google-meet-vs-webex",
  "zoom-vs-google-meet": "google-meet-vs-zoom",
  "prometheus-vs-grafana": "grafana-vs-prometheus",
  "uber-eats-vs-grubhub": "grubhub-vs-uber-eats",
  "netflix-vs-hbo-max": "hbo-max-vs-netflix",
  "mixpanel-vs-heap": "heap-vs-mixpanel",
  "pandadoc-vs-hellosign": "hellosign-vs-pandadoc",
  "toyota-camry-vs-honda-accord": "honda-accord-vs-toyota-camry",
  "toyota-rav4-vs-honda-cr-v": "honda-cr-v-vs-toyota-rav4",
  "toyota-vs-honda": "honda-vs-toyota",
  "microsoft-clarity-vs-hotjar": "hotjar-vs-microsoft-clarity",
  "mailchimp-vs-hubspot": "hubspot-vs-mailchimp",
  "pipedrive-vs-hubspot": "hubspot-vs-pipedrive",
  "salesforce-vs-hubspot": "hubspot-vs-salesforce",
  "youtube-tv-vs-hulu-live-tv": "hulu-live-tv-vs-youtube-tv",
  "peacock-vs-hulu": "hulu-vs-peacock",
  "macbook-air-vs-ipad-pro": "ipad-pro-vs-macbook-air",
  "samsung-galaxy-tab-vs-ipad": "ipad-vs-samsung-galaxy-tab",
  "oneplus-vs-iphone": "iphone-vs-oneplus",
  "kotlin-vs-java": "java-vs-kotlin",
  "typescript-vs-javascript": "javascript-vs-typescript",
  "linear-vs-jira": "jira-vs-linear",
  "popeyes-vs-kfc": "kfc-vs-popeyes",
  "sprout-social-vs-later": "later-vs-sprout-social",
  "uber-vs-lyft": "lyft-vs-uber",
  "visa-vs-mastercard": "mastercard-vs-visa",
  "norton-vs-mcafee": "mcafee-vs-norton",
  "zoom-vs-microsoft-teams": "microsoft-teams-vs-zoom",
  "weights-biases-vs-mlflow": "mlflow-vs-weights-biases",
  "postgresql-vs-mongodb": "mongodb-vs-postgresql",
  "supabase-vs-mongodb": "mongodb-vs-supabase",
  "disney-plus-vs-netflix": "netflix-vs-disney-plus",
  "hulu-vs-netflix": "netflix-vs-hulu",
  "vercel-vs-netlify": "netlify-vs-vercel",
  "nike-vs-new-balance": "new-balance-vs-nike",
  "sentry-vs-new-relic": "new-relic-vs-sentry",
  "adidas-vs-nike": "nike-vs-adidas",
  "peloton-vs-nordictrack": "nordictrack-vs-peloton",
  "surfshark-vs-nordvpn": "nordvpn-vs-surfshark",
  "wegovy-vs-ozempic": "ozempic-vs-wegovy",
  "salesforce-vs-pipedrive": "pipedrive-vs-salesforce",
  "zoho-crm-vs-pipedrive": "pipedrive-vs-zoho-crm",
  "supabase-vs-planetscale": "planetscale-vs-supabase",
  "rust-vs-python": "python-vs-rust",
  "typescript-vs-python": "python-vs-typescript",
  "wave-vs-quickbooks": "quickbooks-vs-wave",
  "xero-vs-quickbooks": "quickbooks-vs-xero",
  "svelte-vs-react": "react-vs-svelte",
  "tesla-vs-rivian": "rivian-vs-tesla",
  "roomba-vs-roborock": "roborock-vs-roomba",
  "steam-deck-vs-rog-ally": "rog-ally-vs-steam-deck",
  "walmart-vs-sams-club": "sams-club-vs-walmart",
  "temu-vs-shein": "shein-vs-temu",
  "microsoft-teams-vs-slack": "slack-vs-microsoft-teams",
  "youtube-tv-vs-sling-tv": "sling-tv-vs-youtube-tv",
  "japan-vs-south-korea": "south-korea-vs-japan",
  "tidal-vs-spotify": "spotify-vs-tidal",
  "whole-foods-vs-sprouts": "sprouts-vs-whole-foods",
  "wix-vs-squarespace": "squarespace-vs-wix",
  "wordpress-vs-squarespace": "squarespace-vs-wordpress",
  "dunkin-vs-starbucks": "starbucks-vs-dunkin",
  "xbox-series-x-vs-steam-deck": "steam-deck-vs-xbox-series-x",
  "vue-vs-svelte": "svelte-vs-vue",
  "whatsapp-vs-telegram": "telegram-vs-whatsapp",
  "bmw-i4-vs-tesla-model-3": "tesla-model-3-vs-bmw-i4",
  "ford-vs-tesla": "tesla-vs-ford",
  "toyota-vs-tesla": "tesla-vs-toyota",
  "whole-foods-vs-trader-joes": "trader-joes-vs-whole-foods",
  "china-vs-usa": "usa-vs-china",
  "wix-vs-wordpress": "wordpress-vs-wix",
};
