/**
 * DAN-2045 — redirect sources whose destination is not a live page.
 *
 * GENERATED by scripts/dan2045-generate-dead-redirects.ts. Do not hand-edit:
 * re-run the generator instead, then re-run scripts/dan2045-verify.ts.
 *
 * Every slug here 308'd onto a 404. Both ends of each pair are archived, so dropping
 * the redirect turns a wasted hop into a direct 404 and changes no page's status.
 * Because every source is archived, removing these from the consolidation map does
 * NOT change the canonical corpus count — archived rows are already excluded by
 * `canonicalComparisonWhere()`.
 *
 * Generated 2026-07-16 against prod: 163 of 286 redirects were broken.
 */
export const DEAD_REDIRECT_SOURCES_DAN2045: string[] = [
  // -> airpods-4-vs-airpods-pro-2 (archived); source is archived
  "airpods-pro-2-vs-airpods-4",
  // -> mercedes-e-class-vs-audi-a6 (archived); source is archived
  "audi-a6-vs-mercedes-e-class",
  // -> wells-fargo-vs-bank-of-america (archived); source is archived
  "bank-of-america-vs-wells-fargo",
  // -> audi-a8-vs-bmw-7-series (archived); source is archived
  "bmw-7-series-vs-audi-a8",
  // -> activecampaign-vs-brevo (archived); source is archived
  "brevo-vs-activecampaign",
  // -> acuity-scheduling-vs-calendly (archived); source is archived
  "calendly-vs-acuity-scheduling",
  // -> asana-vs-clickup (archived); source is archived
  "clickup-vs-asana",
  // -> basecamp-vs-clickup (archived); source is archived
  "clickup-vs-basecamp",
  // -> aws-vs-cloudflare (archived); source is archived
  "cloudflare-vs-aws",
  // -> airtable-vs-coda (archived); source is archived
  "coda-vs-airtable",
  // -> binance-vs-coinbase (archived); source is archived
  "coinbase-vs-binance",
  // -> codeium-vs-continue (archived); source is archived
  "continue-vs-codeium",
  // -> beehiiv-vs-convertkit (archived); source is archived
  "convertkit-vs-beehiiv",
  // -> airflow-vs-dagster (archived); source is archived
  "dagster-vs-airflow",
  // -> 1password-vs-dashlane (archived); source is archived
  "dashlane-vs-1password",
  // -> bitwarden-vs-dashlane (archived); source is archived
  "dashlane-vs-bitwarden",
  // -> apple-tv-plus-vs-disney-plus (archived); source is archived
  "disney-plus-vs-apple-tv-plus",
  // -> adobe-sign-vs-docusign (archived); source is archived
  "docusign-vs-adobe-sign",
  // -> icloud-vs-dropbox (archived); source is archived
  "dropbox-vs-icloud",
  // -> clickhouse-vs-druid (archived); source is archived
  "druid-vs-clickhouse",
  // -> clickhouse-vs-duckdb (archived); source is archived
  "duckdb-vs-clickhouse",
  // -> datadog-vs-dynatrace (archived); source is archived
  "dynatrace-vs-datadog",
  // -> blue-apron-vs-everyplate (archived); source is archived
  "everyplate-vs-blue-apron",
  // -> adobe-xd-vs-figma (archived); source is archived
  "figma-vs-adobe-xd",
  // -> fastapi-vs-flask (archived); source is archived
  "flask-vs-fastapi",
  // -> apache-spark-vs-flink (archived); source is archived
  "flink-vs-apache-spark",
  // -> argocd-vs-flux (archived); source is archived
  "flux-vs-argocd",
  // -> chatgpt-vs-gemini (archived); source is archived
  "gemini-vs-chatgpt",
  // -> claude-vs-gemini (archived); source is archived
  "gemini-vs-claude",
  // -> bmw-vs-genesis (archived); source is archived
  "genesis-vs-bmw",
  // -> codeium-vs-github-copilot (archived); source is archived
  "github-copilot-vs-codeium",
  // -> cursor-vs-github-copilot (archived); source is archived
  "github-copilot-vs-cursor",
  // -> bitbucket-vs-gitlab (archived); source is archived
  "gitlab-vs-bitbucket",
  // -> bmw-x5-vs-gle (archived); source is archived
  "gle-vs-bmw-x5",
  // -> amplitude-vs-google-analytics (archived); source is archived
  "google-analytics-vs-amplitude",
  // -> apple-vs-google (archived); source is archived
  "google-vs-apple",
  // -> bamboohr-vs-greenhouse (archived); source is archived
  "greenhouse-vs-bamboohr",
  // -> apache-spark-vs-hadoop (archived); source is archived
  "hadoop-vs-apache-spark",
  // -> bluehost-vs-hostinger (archived); source is archived
  "hostinger-vs-bluehost",
  // -> freshdesk-vs-intercom (archived); source is archived
  "intercom-vs-freshdesk",
  // -> android-vs-iphone (archived); source is archived
  "iphone-vs-android",
  // -> south-korea-vs-japan (archived); source is archived
  "japan-vs-south-korea",
  // -> golang-vs-java (archived); source is archived
  "java-vs-golang",
  // -> flink-vs-kafka (archived); source is archived
  "kafka-vs-flink",
  // -> activecampaign-vs-klaviyo (archived); source is archived
  "klaviyo-vs-activecampaign",
  // -> java-vs-kotlin (archived); source is archived
  "kotlin-vs-java",
  // -> hugging-face-vs-langchain (archived); source is archived
  "langchain-vs-hugging-face",
  // -> dashlane-vs-lastpass (archived); source is archived
  "lastpass-vs-dashlane",
  // -> hootsuite-vs-later (archived); source is archived
  "later-vs-hootsuite",
  // -> ashby-vs-lever (archived); source is archived
  "lever-vs-ashby",
  // -> github-issues-vs-linear (archived); source is archived
  "linear-vs-github-issues",
  // -> jira-vs-linear (archived); source is archived
  "linear-vs-jira",
  // -> domo-vs-looker (archived); source is archived
  "looker-vs-domo",
  // -> zoom-vs-loom (archived); source is archived
  "loom-vs-zoom",
  // -> dell-xps-vs-macbook-air (archived); source is archived
  "macbook-air-vs-dell-xps",
  // -> macbook-air-vs-macbook-pro-14 (archived); source is archived
  "macbook-pro-14-vs-macbook-air",
  // -> dell-xps-vs-macbook-pro (archived); source is archived
  "macbook-pro-vs-dell-xps",
  // -> google-analytics-vs-matomo (archived); source is archived
  "matomo-vs-google-analytics",
  // -> bitdefender-vs-mcafee (archived); source is archived
  "mcafee-vs-bitdefender",
  // -> lebron-james-vs-michael-jordan (archived); source is archived
  "michael-jordan-vs-lebron-james",
  // -> fullstory-vs-microsoft-clarity (archived); source is archived
  "microsoft-clarity-vs-fullstory",
  // -> hotjar-vs-microsoft-clarity (archived); source is archived
  "microsoft-clarity-vs-hotjar",
  // -> apple-vs-microsoft (archived); source is archived
  "microsoft-vs-apple",
  // -> dall-e-vs-midjourney (archived); source is archived
  "midjourney-vs-dall-e",
  // -> fullstory-vs-mixpanel (archived); source is archived
  "mixpanel-vs-fullstory",
  // -> google-analytics-vs-mixpanel (archived); source is archived
  "mixpanel-vs-google-analytics",
  // -> heap-vs-mixpanel (archived); source is archived
  "mixpanel-vs-heap",
  // -> airtable-vs-monday-com (archived); source is archived
  "monday-com-vs-airtable",
  // -> jira-vs-monday-com (archived); source is archived
  "monday-com-vs-jira",
  // -> notion-vs-monday-com (archived); source is archived
  "monday-com-vs-notion",
  // -> asana-vs-monday (archived); source is archived
  "monday-vs-asana",
  // -> firebase-vs-mongodb (archived); source is archived
  "mongodb-vs-firebase",
  // -> express-vs-nestjs (archived); source is archived
  "nestjs-vs-express",
  // -> dynatrace-vs-new-relic (archived); source is archived
  "new-relic-vs-dynatrace",
  // -> new-balance-vs-nike (archived); source is archived
  "nike-vs-new-balance",
  // -> expressvpn-vs-nordvpn (archived); source is archived
  "nordvpn-vs-expressvpn",
  // -> bitdefender-vs-norton (archived); source is archived
  "norton-vs-bitdefender",
  // -> coda-vs-notion (archived); source is archived
  "notion-vs-coda",
  // -> evernote-vs-notion (archived); source is archived
  "notion-vs-evernote",
  // -> dropbox-vs-onedrive (archived); source is archived
  "onedrive-vs-dropbox",
  // -> iphone-vs-oneplus (archived); source is archived
  "oneplus-vs-iphone",
  // -> anthropic-vs-openai (archived); source is archived
  "openai-vs-anthropic",
  // -> hellosign-vs-pandadoc (archived); source is archived
  "pandadoc-vs-hellosign",
  // -> disney-plus-vs-peacock (archived); source is archived
  "peacock-vs-disney-plus",
  // -> amplitude-vs-pendo (archived); source is archived
  "pendo-vs-amplitude",
  // -> chatgpt-vs-perplexity (archived); source is archived
  "perplexity-vs-chatgpt",
  // -> claude-vs-perplexity (archived); source is archived
  "perplexity-vs-claude",
  // -> google-vs-perplexity (archived); source is archived
  "perplexity-vs-google",
  // -> chewy-vs-petco (archived); source is archived
  "petco-vs-chewy",
  // -> chroma-vs-pinecone (archived); source is archived
  "pinecone-vs-chroma",
  // -> clickhouse-vs-pinot (archived); source is archived
  "pinot-vs-clickhouse",
  // -> druid-vs-pinot (archived); source is archived
  "pinot-vs-druid",
  // -> cockroachdb-vs-planetscale (archived); source is archived
  "planetscale-vs-cockroachdb",
  // -> neon-vs-planetscale (archived); source is archived
  "planetscale-vs-neon",
  // -> google-analytics-vs-plausible (archived); source is archived
  "plausible-vs-google-analytics",
  // -> cockroachdb-vs-postgresql (archived); source is archived
  "postgresql-vs-cockroachdb",
  // -> mongodb-vs-postgresql (archived); source is archived
  "postgresql-vs-mongodb",
  // -> amplitude-vs-posthog (archived); source is archived
  "posthog-vs-amplitude",
  // -> airflow-vs-prefect (archived); source is archived
  "prefect-vs-airflow",
  // -> celery-vs-prefect (archived); source is archived
  "prefect-vs-celery",
  // -> dagster-vs-prefect (archived); source is archived
  "prefect-vs-dagster",
  // -> dbt-vs-prefect (archived); source is archived
  "prefect-vs-dbt",
  // -> grafana-vs-prometheus (archived); source is archived
  "prometheus-vs-grafana",
  // -> golang-vs-python (archived); source is archived
  "python-vs-golang",
  // -> laravel-vs-rails (archived); source is archived
  "rails-vs-laravel",
  // -> hibob-vs-rippling (archived); source is archived
  "rippling-vs-hibob",
  // -> bear-vs-roam-research (archived); source is archived
  "roam-research-vs-bear",
  // -> obsidian-vs-roam-research (archived); source is archived
  "roam-research-vs-obsidian",
  // -> bugsnag-vs-rollbar (archived); source is archived
  "rollbar-vs-bugsnag",
  // -> rtx-4090-vs-rtx-4080 (archived); source is archived
  "rtx-4080-vs-rtx-4090",
  // -> python-vs-rust (archived); source is archived
  "rust-vs-python",
  // -> edge-vs-safari (archived); source is archived
  "safari-vs-edge",
  // -> quickbooks-vs-sage (archived); source is archived
  "sage-vs-quickbooks",
  // -> pipedrive-vs-salesforce (archived); source is archived
  "salesforce-vs-pipedrive",
  // -> ipad-vs-samsung-galaxy-tab (archived); source is archived
  "samsung-galaxy-tab-vs-ipad",
  // -> new-relic-vs-sentry (archived); source is archived
  "sentry-vs-new-relic",
  // -> amazon-vs-shopify (archived); source is archived
  "shopify-vs-amazon",
  // -> bigcommerce-vs-shopify (archived); source is archived
  "shopify-vs-bigcommerce",
  // -> etsy-vs-shopify (archived); source is archived
  "shopify-vs-etsy",
  // -> nest-vs-simplisafe (archived); source is archived
  "simplisafe-vs-nest",
  // -> hostinger-vs-siteground (archived); source is archived
  "siteground-vs-hostinger",
  // -> adobe-xd-vs-sketch (archived); source is archived
  "sketch-vs-adobe-xd",
  // -> discord-vs-slack (archived); source is archived
  "slack-vs-discord",
  // -> later-vs-sprout-social (archived); source is archived
  "sprout-social-vs-later",
  // -> bigcommerce-vs-squarespace (archived); source is archived
  "squarespace-vs-bigcommerce",
  // -> framer-vs-squarespace (archived); source is archived
  "squarespace-vs-framer",
  // -> hydro-flask-vs-stanley (archived); source is archived
  "stanley-vs-hydro-flask",
  // -> rog-ally-vs-steam-deck (archived); source is archived
  "steam-deck-vs-rog-ally",
  // -> firebase-vs-supabase (archived); source is archived
  "supabase-vs-firebase",
  // -> mongodb-vs-supabase (archived); source is archived
  "supabase-vs-mongodb",
  // -> neon-vs-supabase (archived); source is archived
  "supabase-vs-neon",
  // -> planetscale-vs-supabase (archived); source is archived
  "supabase-vs-planetscale",
  // -> react-vs-svelte (archived); source is archived
  "svelte-vs-react",
  // -> att-vs-t-mobile (archived); source is archived
  "t-mobile-vs-att",
  // -> amazon-vs-temu (archived); source is archived
  "temu-vs-amazon",
  // -> tesla-vs-toyota (archived); source is archived
  "toyota-vs-tesla",
  // -> aldi-vs-trader-joes (archived); source is archived
  "trader-joes-vs-aldi",
  // -> javascript-vs-typescript (archived); source is archived
  "typescript-vs-javascript",
  // -> python-vs-typescript (archived); source is archived
  "typescript-vs-python",
  // -> grubhub-vs-uber-eats (archived); source is archived
  "uber-eats-vs-grubhub",
  // -> chinese-economy-vs-us-economy (archived); source is archived
  "us-economy-vs-chinese-economy",
  // -> netlify-vs-vercel (archived); source is archived
  "vercel-vs-netlify",
  // -> att-vs-verizon (archived); source is archived
  "verizon-vs-att",
  // -> mastercard-vs-visa (archived); source is archived
  "visa-vs-mastercard",
  // -> angular-vs-vue (archived); source is archived
  "vue-vs-angular",
  // -> svelte-vs-vue (archived); source is archived
  "vue-vs-svelte",
  // -> costco-vs-walmart (archived); source is archived
  "walmart-vs-costco",
  // -> sams-club-vs-walmart (archived); source is archived
  "walmart-vs-sams-club",
  // -> freshbooks-vs-wave (archived); source is archived
  "wave-vs-freshbooks",
  // -> chroma-vs-weaviate (archived); source is archived
  "weaviate-vs-chroma",
  // -> google-meet-vs-webex (archived); source is archived
  "webex-vs-google-meet",
  // -> ozempic-vs-wegovy (archived); source is archived
  "wegovy-vs-ozempic",
  // -> mlflow-vs-weights-biases (archived); source is archived
  "weights-biases-vs-mlflow",
  // -> telegram-vs-whatsapp (archived); source is archived
  "whatsapp-vs-telegram",
  // -> apple-watch-vs-whoop (archived); source is archived
  "whoop-vs-apple-watch",
  // -> fitbit-vs-whoop (archived); source is archived
  "whoop-vs-fitbit",
  // -> cursor-vs-windsurf (archived); source is archived
  "windsurf-vs-cursor",
  // -> github-copilot-vs-windsurf (archived); source is archived
  "windsurf-vs-github-copilot",
  // -> godaddy-vs-wix (archived); source is archived
  "wix-vs-godaddy",
  // -> sage-vs-xero (archived); source is archived
  "xero-vs-sage",
  // -> wave-vs-xero (archived); source is archived
  "xero-vs-wave",
  // -> hulu-live-tv-vs-youtube-tv (archived); source is archived
  "youtube-tv-vs-hulu-live-tv",
  // -> pipedrive-vs-zoho-crm (archived); source is archived
  "zoho-crm-vs-pipedrive",
];
