/**
 * DAN-2078 — rivalry-level duplicate consolidation (retired slug -> survivor).
 *
 * GENERATED by scripts/dan2078-generate-rivalry-redirects.ts. Do not hand-edit:
 * re-run the generator instead, and re-run scripts/dan2065-full-map-audit.ts after.
 *
 * Grouped by ENTITY PAIR (alias-normalised), not slug shape — that is why this map
 * catches duplicates DAN-1265 / DAN-1800 could not see (`us-economy-vs-china-economy`
 * and `china-economy-size-vs-us` share no slug tokens but are the same rivalry).
 *
 * Survivor = highest `searchImpressions` (real GSC data). Never `viewCount` — that is
 * seed data, not traffic (DAN-2037). Impressions at decision time are recorded inline
 * so a future reader can see the call rather than re-derive it.
 *
 * The NFL/NBA (4 pages) and US/China-economy (7 pages) clusters are deliberately absent
 * — their slugs promise facets, so they are held for the DAN-2078 board call.
 */
export const RIVALRY_CONSOLIDATIONS_DAN2078: Record<string, string> = {
  // 2026-bmw-x5 | 2026-mercedes-benz-gle — mercedes-gle-vs-bmw-x5 (96) > mercedes-benz-gle-vs-bmw-x5 (87)
  "mercedes-benz-gle-vs-bmw-x5": "mercedes-gle-vs-bmw-x5",

  // apple-m3 | apple-m4 — apple-m3-vs-apple-m4 (35) > m3-chip-vs-m4-chip (34)
  "m3-chip-vs-m4-chip": "apple-m3-vs-apple-m4",

  // bubly | la-croix — bubly-vs-lacroix (243) > bubly-vs-la-croix (38)
  "bubly-vs-la-croix": "bubly-vs-lacroix",

  // burger-king | mcdonald-s — burger-king-vs-mcdonald-s (211) > mcdonalds-vs-burger-king (65)
  "mcdonalds-vs-burger-king": "burger-king-vs-mcdonald-s",

  // costco | sam-s-club — costco-vs-sam-s-club (52) > costco-vs-sams-club (49)
  "costco-vs-sams-club": "costco-vs-sam-s-club",

  // delta-air-lines | united-airlines — delta-vs-united (148) > united-airlines-vs-delta-air-lines (34)
  "united-airlines-vs-delta-air-lines": "delta-vs-united",

  // disney | netflix — disney-vs-netflix (41) > netflix-vs-disney-plus (39)
  "netflix-vs-disney-plus": "disney-vs-netflix",

  // fc-barcelona | real-madrid — real-madrid-vs-barcelona (921) > barcelona-vc-real-madrid-vs-cups (113)
  "barcelona-vc-real-madrid-vs-cups": "real-madrid-vs-barcelona",

  // hbo-max | netflix — hbo-max-vs-netflix (561) > netflix-vs-max (547)
  "netflix-vs-max": "hbo-max-vs-netflix",

  // home-depot | lowe-s — home-depot-vs-lowes (366) > home-depot-vs-lowe-s (277)
  "home-depot-vs-lowe-s": "home-depot-vs-lowes",

  // korean-war | vietnam-war — vietnam-war-vs-korean-war (514) > korean-war-vs-vietnam-war-comparison (144)
  "korean-war-vs-vietnam-war-comparison": "vietnam-war-vs-korean-war",

  // kylian-mbapp | neymar — neymar-vs-mbappe (411) > neymar-vs-mbape (348)
  "neymar-vs-mbape": "neymar-vs-mbappe",

  // mike-tyson | muhammad-ali — mike-tyson-vs-muhammad-ali (62) > ali-vs-tyson (37)
  "ali-vs-tyson": "mike-tyson-vs-muhammad-ali",

  // playstation-5 | xbox-series-x — ps5-vs-xbox-series-x (2362) > playstation-5-vs-xbox-series-x (112)
  "playstation-5-vs-xbox-series-x": "ps5-vs-xbox-series-x",
};
